\documentclass[preprint, 3p,
authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{Journal} % Sets Journal name

\usepackage{lineno} % add
  \linenumbers % turns line numbering on

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
    \setmainfont{Times New Roman}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Big Spenders: Large-N Measures of Urban Regimes in Japanese Municipalities},
            colorlinks=true,
            urlcolor=blue,
            linkcolor=blue,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{0}
% Pandoc toggle for numbering sections (defaults to be off)
\setcounter{secnumdepth}{0}


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



\usepackage{caption}
\usepackage{setspace}\doublespacing
\usepackage{lscape}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\usepackage{colortbl}
\usepackage{xcolor}
\usepackage{makecell}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}


\begin{frontmatter}

  \title{Big Spenders: Large-N Measures of Urban Regimes in Japanese
Municipalities}
    \author[UNIVERSITY BLINDED]{AUTHOR BLINDED%
  \corref{cor1}%
  \fnref{1}}
   \ead{EMAIL BLINDED} 
      \affiliation[Ezra Systems Postdoctoral Research
Associate]{UNIVERSITY AFFILIATION BLINDED}
    \cortext[cor1]{Corresponding author}
    \fntext[1]{Data Availability: Index data, models, and replication
code will be made available on Github {[}URL BLINDED FOR PEER REVIEW{]}
upon publication.}
  
  \begin{abstract}
  Facing hazards and migration from disasters, many cities might benefit
  from redistributive policies to aid vulnerable residents, requiring
  changes to `urban regimes' - the powerbrokers and networks governing
  local politics. However, to date, changes in urban regimes have been
  difficult to detect systematically. I introduce a method for Large-N
  municipality samples, using relative spending over time to measure
  municipalities' propensities towards each of 4 common urban regime
  types, including (1) developmental, (2) middle-class, (3) social
  welfare, and (4) caretaker regimes, developing 3 indices that
  approximate a municipality's regime type. Using the case of Japan, an
  industrialized democracy and the 3rd largest economy in the world, I
  evaluate change in urban regimes over time, using a sample of 1471
  Japanese municipalities from 2000 to 2018. Using mapping,
  visualization, and panel models over time, this study finds that some
  municipalities' governing coalitions are spending more on
  redistributive policies than others; these social welfare regimes
  increased in prevalence by 17\% from 2000 to 2018. Controlling for
  sociodemographic and political factors, models show that social
  welfare regimes increased much more consistently than alternative
  regime types, and bridging social capital was closely linked to regime
  outcomes.
  \end{abstract}
    \begin{keyword}
    urban regime \sep cities \sep policy \sep social welfare \sep social
capital \sep 
    Japan
  \end{keyword}
  
 \end{frontmatter}

\captionsetup[table]{labelformat=empty}
\captionsetup[figure]{labelformat=empty}
\captionsetup{font=large}

\hypertarget{introduction}{%
\section{1. Introduction}\label{introduction}}

Who governs? As municipalities face increasing threats from climate
change-induced disasters, the coalitions and interests of power brokers
who govern our municipalities are likely changing. Since Dahl's
\citeyearpar{dahl_1961} case study of New Haven's mayor posed the famous
question, ``Who Governs?'', scholars have puzzled over the governance of
municipalities: Much attention has been paid to different types of
coalitions
\citep{munoz_and_henry_1986, stone_1989, stoker_and_mossberger_1994, gilliam_1996, davies_2017, russo_and_scarnato_2018},
mayors
\citep{ramirez_perez_et_al_2008, debenedictis_kessner_and_warshaw_2016, freier_and_thomasius_2016, einstein_and_glick_2018},
and interest groups
\citep{logan_and_rabrenovic_1990, mossberger_and_stoker_2001, cooper_et_al_2005, portney_and_berry_2016, anzia_2019}
that govern local politics.

Urban regime scholars argue that the powerbrokers together constitute an
``urban regime'' \citep{stone_1993}, coined in Clarence Stone's
\citeyearpar{stone_1989} study of Atlanta politics. ``Urban regime''
refers to elected officials and unelected powerbrokers alike, such as
influential firms, NGOs, or citizens groups, who determine what policy
actions a municipality can and cannot take
\citep{mossberger_and_stoker_2001}. As municipalities experience more
disasters, migration, and social change in the face of storms, floods,
fires, hurricanes, and other disasters, one would naturally expect these
urban regimes to change. But to date, these changes have been difficult
to detect systematically, with most work on urban regimes focusing on
single city case studies, or multiple different, unaligned medium-N city
samples (eg. as pointed out by \citep{cheek_chmutina_2022}). To date,
the largest samples of municipalities systematically classified by urban
regime specifically has been De Socio's \citeyearpar{de_socio_2007}
24-city sample and Kilburn's \citeyearpar{kilburn_2004} 14-city sample,
using Stone's \citeyearpar{stone_1993} 4 regime type classification.

This study aims to fill that gap, introducing a framework for measuring
municipalities' propensities towards each of 4 common urban regime
types, and evaluating the change in frequencies of urban regimes over
time. I employ Stone's \citeyearpar{stone_1993} 4-regime classification,
which includes (1) developmental, (2) middle-class, (3) social welfare,
and (4) caretaker regimes, discussed in the literature review.

These categories raise natural questions in the face of disaster: Given
frequent disasters in recent decades, have social welfare regimes become
more common, compared to regimes prioritizing business or middle-class
interests? Or, have local politics stagnated with a rise in caretaker
regimes that simply maintain the status quo? To answer these questions,
I apply this framework to a Large-N sample of 1741 Japanese
municipalities over 20 years from 2000 to 2018. While urban regime
theory originally discussed cities, these 4 urban regime types could
plausibly occur in municipalities large or small, as discussed further
in the methods. The Japan Statistical Bureau reports considerable annual
data for each municipality, allowing scholars to approximate the basic
contours of municipalities' urban regimes by a simple, publicly
available proxy of each municipality's governance priorities:
\emph{spending rates.} While spending cannot tell us specific actors
that govern, it can broadly approximate which of Stone's
\citeyearpar{stone_1993} 4 types of regimes are driving local policy.
Generally speaking, a true developmental regime would spend more
municipal funds in support of business needs; similarly, a true social
welfare regime would spend more in support of social welfare needs. Not
to replace, but to aid qualitative investigations of urban regimes, this
study designs a method to make Large-N comparisons among thousands of
municipalities at a time. I posit that this study can detect measurable
differences among municipalities in terms of their spending rates.

As a preview of my results, I find that even after accounting for
population and inflation, municipal spending rates vary substantially
over time, with certain urban regimes' spending priorities becoming more
common with each passing year while others become less common. In
particular, I document the 20-year rise of the social welfare regime as
a very common type of urban regime, growing from just 0\% of
municipalities in 2000 to 17\% of municipalities in 2018, and to 73\% of
municipalities when including social welfare-\emph{related} regimes. I
also detect geographic patterns, with coastal areas investing more
heavily in social welfare regime priorities over time. These are
exciting and heartening findings, because they indicate that while
national-level governance on disaster resilience has made progress with
starts and stops, municipalities are not unilaterally gridlocked, stuck
in caretaker, status quo regimes. Instead, many municipalities are
transitioning to social welfare regimes, increasing their spending on
social welfare issues like food security, housing, and disaster recovery
above the median level nationwide.

\hypertarget{literature-review}{%
\section{2. Literature Review}\label{literature-review}}

\hypertarget{urban-regime-theory}{%
\subsection{2.1 Urban Regime Theory}\label{urban-regime-theory}}

Since Stone's \citeyearpar{stone_1989} examination of urban regimes in
Atlanta, dozens of case studies have detailed different urban regimes
and governance arrangements throughout the world
\citep{stoker_and_mossberger_1994, mossberger_and_stoker_2001, de_socio_2007, camou_2014, davies_and_blanco_2017, rosol_et_al_2017, russo_and_scarnato_2018}.
Over 30 years since the term's coining, urban regimes received praise
\citep{kilburn_2004, davies_and_imbroscio_2009} and criticism
\citep{sites_1997, davies_2003, imbroscio_2003, imbroscio_2004} for how
easily it can be applied to understand local politics.

Many regimes once thought to be long-standing have come undone and
changed quickly in recent years \citep{stone_2015, stone_et_al_2015},
making the field awash in related terms like ``urban governance''
\citep{pierre_2014, da_cruz_et_al_2019}, governance networks
\citep{gissendanner_2003, davidson_et_al_2019}, policy networks
\citep{bulkeley_and_betsill_2013, hawkins_et_al_2016, wukich_2022},
public-private partnerships
\citep{stoker_1998, davies_2017, guo_and_ho_2019}, and multi-tiered
political orders \citep{stone_2015, weaver_2022}, or a just, socially
equitable city \citep{campbell_1996, fainstein_2010}. Others extended
definitions of urban regimes, applying versions of it to social welfare
crisis in the face of mass displacement and other social crises
\citep{lambelet_2019}.

Nomenclature aside, these frameworks all generally aim to explain ``who
governs,'' but systematic categorizations of many municipalities at once
have been rarer, usually confined to small-to-medium-N analyses
\citep{sellers_2002, kilburn_2004, stone_et_al_2015, davies_and_blanco_2017}.
Below, I synthesize a basic typology of urban regimes for measurement
from the extended literature, and outline the argument for why it
matters `who governs' municipalities in the face of disasters.

\hypertarget{redistributive-politics}{%
\subsection{2.2 Redistributive Politics}\label{redistributive-politics}}

For the purposes of this study, urban regimes also are an effective,
local level tool for thinking about the broader class of politics that
disaster resilience initiatives can exemplify: redistributive policies,
a familiar, long-standing, and particularly pernicious policy challenge
for municipalities
\citep{meltzer_and_scott_1981, pierson_1994, hacker_2004, iversen_and_soskice_2006, mettler_2011, rueda_and_stemueller_2019}.
National, regional, and municipal governments each work with
redistributive policies, aiming to provide en masse specific public
goods (ranging from seawalls and flood protection to social welfare aid)
that are particularly difficult for residents to obtain individually,
especially for vulnerable residents.

Previous literature dealt with electoral (Meltzer \& Richards; Iversen
\& Soskice 2006), institutional
\citep{pierson_1994, hacker_2004, mettler_2011}, or street-level
implementation \citep{lipsky_1980, hupe_and_hill_2007} explanations for
the success and continuity of redistributive policies. However, these
studies dealt less with the community resources available to
municipalities, like partnerships with businesses
\citep{stone_1989, mossberger_and_stoker_2001}, civil society advocacy
groups \citep{portney_and_berry_2016}, neighborhood associations
\citep{logan_and_rabrenovic_1990}, and local networks
\citep{aldrich_and_meyer_2015}. These often overlooked community
resources can play important roles in redistributing resources to
residents in need \citep{aldrich_and_kioyta_2017, klinenberg_2018}.

What kinds of redistributive policies, then, were past scholars writing
about? The classic example of redistributive policy is social welfare
support for low-income families and unemployment insurance
\citep{pierson_1994, hacker_2004}, to abate the health and economic
challenges of entrenched poverty
\citep{ahammer_packham_2020, berkowitz_and_basu_2021}. In addition to
these, governments have tackled many redistributive policy issues in the
past. These include, for example:

\begin{itemize}
\item
  Social security policies aimed to eliminate poverty among the elderly,
  by redistributing the resources of other age groups (Titmus 1965,
  Conde-Ruiz \& Profeta 2007).
\item
  Universal health care, or market solutions, both aim to eliminate loss
  of life and financial ruin due to medical expenses, by redistributing
  the costs of health care issues to the entire population
  \citep{mettler_2011}.
\item
  Public education sought to remedy lack of access of education and
  opportunity in working class families by publicly funding education
  through the taxbase \citep{mettler_2005}.
\item
  Highway systems
  \citep{congleton_and_bennett_1995, zhu_and_brown_2013},
  electrification \citep{baker_and_phillips_2019, breetz_et_al_2018},
  and public transportation \citep{hood_2006} seek to connect citizens
  and expand economic development, important to everyone, but are
  challenging for any one municipality or company to pay for
  \citep{boarnet_and_haughwout_2000}.
\end{itemize}

These redistributive programs frequently develop policy constituencies
if the group benefitting from them is sizable enough
\citep{meltzer_and_richard_1981, campbell_2012}; in some states, these
programs' continuation is conditional, becoming political currency for
pork-barrel politics \citep{fukui_and_fukai_1996, catalinac_et_al_2020},
while in others, they become permanent fixtures in national policy
\citep{pierson_1994}.

However, moving beyond these federal- or state-level examples, in fact,
municipalities have been tackling redistributive issues for generations
\citep{peterson_1981, saiz_1999, tonkiss_2020}. Municipalities use
redistributive policies to remedy unequal access to employment in
neighborhoods by funding public transit for all
\citep{frankena_1973, asensio_et_al_2003, glaeser_et_al_2009, fearnley_and_aarhaug_2019, wiesel_and_liu_2021}.
They may support local businesses that might struggle to secure
consistent customers by providing public venues or markets
\citep{tangires_1997}. Municipalities may use public funds to free up
real estate and housing available in various neighborhoods
\citep{detter_and_folster_2017}, or, in the shameful history of many
municipalities, local governments can be complicit in redlining and
illegally restricting access to housing \citep{rothstein_2017}. Lately,
municipalities' efforts at improving health equity are especially
visible, as municipalities conduct and manage public health campaigns,
like current local efforts to rollout testing and vaccination during the
COVID-19 pandemic \citep{berkowitz_and_basu_2021}. Some national
governments lean on local governments to provide services that
legitimize their state \citep{wallace_2013}. And in many countries,
municipalities play a key role in the disbursement and coordination of
social welfare distribution
\citep{katz_and_allen_2001, weir_and_kind_2021}, and must secure the
necessary funding for these projects \citep{payson_2022}.

Many disaster resilience initiatives, on the other hand, act as a new
form of redistributive policy. These initiatives extend critical
benefits to society, but often struggle to achieve electoral support
because their benefits are diffuse, except to the most vulnerable in
society who need them. However, not all types of urban regimes
prioritize redistributive policies like social welfare support; indeed,
three out of the four regime types discussed below specifically
prioritize other needs. Social welfare's relevance to disaster
resilience makes it especially important to identify whether social
welfare-oriented regimes are increasing or declining.

\hypertarget{types-of-urban-regimes}{%
\subsection{2.3 Types of Urban Regimes}\label{types-of-urban-regimes}}

As discussed above, Clarence Stone \citeyearpar{stone_1993} and later
comparative studies \citep{kilburn_2004, de_socio_2007} primarily relied
on 4 main types of urban regimes, including (1) developmental, (2)
middle-class, (3) social welfare regimes, and (4) caretaker regimes.
Over 30 years, scholars have created numerous other types of urban
regimes, sometimes conflicting or concept stretching, as some have
argued \citep{mossberger_and_stoker_2001}; however, these original 4
regime types are still arguably the main types at play today. I outline
in \textbf{Table \ref{tab:regimelit}} a basic typology.

\newpage
\begin{landscape}

\begin{table}

\caption{\textbf{Table \ref{tab:regimelit}: \label{tab:regimelit}{Typology of Urban Regimes}}}
\centering
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{2cm}>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\toprule
Regime & Definition & Examples & Related & Japanese Examples\\
\midrule
Caretaker & maintains status quo, traditional municipal service provision & New Orleans (Whelan et al. 1994) & Maintenance/Status Quo (Stone 1989)
                 

                 Bystander (Portz 1990)
                 

\cellcolor{gray!6}{                 Austerity (Davies \& Blanco 2017)} & \cellcolor{gray!6}{-}\\
Developmental & promotes economic growth while preventing economic decline & Atlanta (Stone 1989) & Entrepreneurial Regimes (Euchner 1993)
                 

                 Public-Private Partnerships (Davies 2017)
                 

                 Player (Portz 1990)
                 

                 Castle Towns (Funabashi 2006; Hill \& Fujita 1993) & Tokyo (Saito 2003; Tsukamoto 2012; Sorensen et al. 2010)
    

    Kitakyushu (Yeum 2002)
    

    Minamata (Funabashi 2006)
    

    Kobe Post-1995 (Edgington 2010)\\
Middle-Class & promotes egalitarian policies in education, health, environment, and city planning & Santa Cruz (Gendron \& Domhoff 2018) & Progressive (Stone 1989)
                

                'Anti-Regime' (DeLeon 1992) & Mitaka (Takao 2006)
                           

                           Kyoto (Sugiyama \& Takeuchi 2008)
                           

\cellcolor{gray!6}{                           Iida (Fraser et al. 2020)}\\
Social Welfare & improves conditions for working class, expands social safety net & Early Toronto (Mahon 2007) & Opportunist (Stone 1989)
                 

                 Activist (Clark 2001)
                 

                 Stewardship Regimes (Nissen 1995) & Yokohama (Hayashi 2013)
                           
Mikura Ward, Kobe (Yasui 2007)\\
\bottomrule
\end{tabu}
\end{table}

\end{landscape}
\newpage

The first type is (1) \emph{developmental regimes.} These regimes
prioritize economic development and business interests, while preventing
economic decline
\citep{stone_1989, austrian_and_rosentraub_2002, de_socio_2007}. A
robust literature has covered these, starting with archetypes like
Stone's \citeyearpar{stone_1989} Atlanta. Scholars have proposed several
subtypes over the years that group well under developmental regimes,
including entrepreneurial regimes, describing regimes' enticement with
sports industries \citep{euchner_1993}, tourism-focused regimes
\citep{russo_and_scarnato_2018}, public private partnerships
\citep{davies_2017}, and player cities, describing those which advocate
intensely to bring in or keep industry \citep{portz_1990}. A related
concept in the Japanese literature is ``castle towns,'' referring to
municipalities where the entire local government and economy is closely
structured around one industry \citep{hill_and_fujita_1993}. Famous
examples include Minamata, which suffered considerable environmental
pollution due to the Chisso corporation in the 1950s
\citep{funabashi_2006}; more recent examples of castle towns are nuclear
power plant host communities, such as Onagawa or Satsumasendai
\citep{aldrich_and_fraser_2017}.

Developmental regimes and related types have received considerable
attention in Japan, with studies emphasizing the neoliberal,
developmental priorities of property development in post-Bubble Tokyo
\citep{saito_2003, tsukamoto_2012, sorensen_et_al_2010}, developmental
priorities in reconstruction plans from the Kobe Earthquake
\citep{edgington_2010}, and early efforts to reduce air pollution in
industrial cities like Kitakyushu \citep{yeum_2002}.

The second common type is (2) \emph{middle-class regimes} (a.k.a.
progressive regimes\^{}{[}Usually called progressive regimes, I term
these `middle-class' regimes to avoid confusion with the next type,
which support progressive, redistributive policies.{]}). These regimes
support middle-class, progressive interests like environmentalism,
health care, education, and quality city planning
\citep{deleon_1992, gendron_and_domhoff_2018, rosdil_2016}. Past
examples include politically left-wing city politics in Santa Cruz, San
Francisco, and Seattle, among others \citep{gendron_and_domhoff_2018}.
These regimes focus on a specific type of progressivism, namely
egalitarian ideals, such as environmental conservation and
sustainability \citep{rosol_et_al_2017}, but these regimes tend to
support middle-class interests, rather than working class interests
\citep{kilburn_2004}.

Famous Japanese examples include Mitaka City, a Tokyo suburb known for
progressive environmental policy, quality of life, and citizen
engagement \citep{takao_2006}. Similarly, large cities like Kyoto
\citep{sugiyama_and_takeuchi_2008} and smaller municipalities like Iida
in Nagano Prefecture \citep{fraser_et_al_2020} have both received
attention for their municipalities' emphasis and leadership on
environmentalism.

The third type refers to (3) \emph{social welfare regimes} (a.k.a.
opportunist regimes\emph{\^{}{[}*Sometimes called ``opportunist''
regimes, referring to aims to expand the social safety net, this study
re-terms this category `social welfare regimes', to more respectfully
characterize these policies.{]})}*. These regimes prioritize social
welfare support for the working class and related redistributive
policies, such as unemployment insurance, public housing, and financial
support for families in need, eg. after crisis
\citep{stone_1993, thompson_2005, camou_2014, lai_and_chui_2014, arbaci_2019}.Related
monikers include `opportunist regimes,' as in those aiming to expand the
social safety net \citep{stone_1989}, activist regimes
\citep{clark_2001}, which use neighborhood coalitions and activist
groups to push for social equity \citep{thompson_2005}, labor coalitions
\citep{camou_2014}, and stewardship regimes \citep{nissen_1995}, which
negotiate with businesses for fair treatment of workers. While the shape
of social welfare policy varies by city and country, Canadian and UK
municipalities are particularly known for efforts to expand social
safety nets \citep{saraceno_2002}, like Toronto's early work expanding
childcare \citep{mahon_2007}, although Toronto has shifted over time to
a developmental/progressive regime. Japanese urban studies research has
highlighted Yokohama for its particularly expansive support for the
homeless \citep{hayashi_2013}, as well as specific city wards like the
working class neighborhood of Mikura in Kobe for its robust advocacy for
social equity in the reconstruction process after the 1995 Kobe
Earthquake \citep{yasui_2007}.

Finally, the fourth type is (4) \emph{caretaker regimes}. In these
municipalities, the incumbent regime seeks to maintain a municipality's
status quo \citep{turner_1992, whelan_et_al_1994}. The municipality
provides basic services, but avoids expanding. Past studies labeled the
city of Kalamazoo, MI \citep{sanders_1987} and pre-Katrina New Orleans,
LA \citep{whelan_et_al_1994}, as potential caretaker regimes (although
New Orleans has changed significantly over time). Other terms capture
the same approximate meaning, including maintenance regimes
\citep{stone_1989} or bystander regimes \citep{portz_1990}, which refer
to regimes that played no major role when industrial firms closed shop
in the US rustbelt. Relatedly, some municipalities have also organized
under austerity regimes, focused on cutting expenses, rather than
expanding policies; this subtype lies somewhere between caretaker
regimes and developmental regimes, as they usually cut expenditures on
social welfare or progressive causes, but not necessarily economic
interests \citep{davies_and_blanco_2017}. To the author's knowledge, few
studies have tracked caretaker regimes in Japan; this study aims to help
remedy that.

\hypertarget{correlates-of-urban-regimes}{%
\subsection{2.4 Correlates of Urban
Regimes}\label{correlates-of-urban-regimes}}

Given how useful social welfare regimes can be in an era of increasingly
frequent disasters, what kinds of municipalities develop social welfare
regimes, and which do not? While little literature directly tackles this
question, past studies summarized below suggest several likely
correlates.

\hypertarget{demographic-and-financial-correlates-of-urban-regimes}{%
\subsubsection{2.4.1 Demographic and Financial Correlates of Urban
Regimes}\label{demographic-and-financial-correlates-of-urban-regimes}}

Second, I expect some municipalities are predisposed towards certain
types of urban regimes. Highly populated municipalities, municipalities
with higher income per capita, municipalities with more revenue per
capita, and municipalities with better balanced budgets have more funds
and other resources to spend on advancing a social welfare regime (or a
developmental or middle-class regime, for that matter). But
municipalities who receive a larger share of their annual budget from
the national or prefectural government may face more pressure to conform
with national or prefectural objectives, which often come in the shape
of economic development policy. Such municipalities might invest
\emph{less} in social welfare.

\hypertarget{partisanship-and-urban-regimes}{%
\subsubsection{2.4.2 Partisanship and Urban
Regimes}\label{partisanship-and-urban-regimes}}

Third, party interests may push some municipalities towards or against
social welfare spending. The Liberal Democratic Party is, despite its
name, Japan's long-time conservative party, and traditionally promotes
business interests and economic development. While LDP social welfare
advocates do exist, they are not typically at the center of power.
Instead, past studies explain that when the LDP accepts social welfare
policies, it usually does so to counter any competitive advantage that
policy gives left-leaning opposition parties prior to elections
\citep{estevez_2020}. This has especially been the case since electoral
reform in 1994 pushed the LDP to use more universal policies to cater to
swing districts \citep{shinada_2018}; examples include universal health
care in the 1990s \citep{peng_2002}, elder care under Prime Minister
(PM) Hashimoto \citep{estevez_2020}, child care under PM Koizumi
\citep{nishioka_2018}, and paid parental leave under PM Abe
\citep{dalton_2017}. Municipalities where the Liberal Democratic Party
performed well in recently elections thus likely have little incentive
to adopt social welfare policies; their local officials and prefectural
party machine are more likely to push for developmental policies.

\hypertarget{timing-and-path-dependence}{%
\subsubsection{2.4.3 Timing and Path
Dependence}\label{timing-and-path-dependence}}

First, timing matters. First, social welfare regimes (and spending in
general) is notoriously path dependent, where once governments
institutionalize certain spending programs, they tend to stick around.
Second, regimes may shift according to the social constraints of the
time. After the 2011 triple disaster, a surge of disaster recovery
spending occurred in the Tohoku region
\citep{mochizuki_2014, aldrich_2019, noy_2023}. One might expect this
disaster pushed some municipalities towards social welfare regimes in
order to provide better for vulnerable families and elders in the
aftermath. Conversely, some municipalities rebuild primarily according
to central government instructions, spending primarily on infrastructure
while neglecting community spending
\citep{cheek_2020, aldrich_2019, fraser_et_al_2021_GEC}. As a result,
the impact of the disaster on social welfare regime evolution is
currently unclear.

Similarly, local and national rhetoric on spending has changed over time
\citep{catalinac_2018, estevez_2020}; concepts like the 1980s'
Washington Consensus, the 1992 economic bubble burst in Japan, the 1994
electoral reforms \citep{shinada_2018}, the 1995 Kobe Earthquake
\citep{edgington_2011}, the 2008 Great Recession, and the 2011 disaster
each greatly shifted the conversation on spending \citep{cheek_2020}.
For example, after electoral reform in the 1990s, Kyoto switched from
being a stronghold for the Japanese Communist Party to being a
center-right governed city, then eventually went bankrupt
\citep{sugiyama_takeuchi_2008}. Some governments post-recession
advocated austerity, while the 2011 disaster highlighted great need and
vulnerability of residents to crisis, both in Tohoku and elsewhere,
leading to the 2015 Sendai Framework, which advocated a need for
investment in local communities to `build back better' after crisis so
as not to leave communities vulnerable again
\citep{maly_2020, cheek_2022}. Each of these influences could propel or
hinder the growth of social welfare regimes. Given this, which direction
have Japanese municipalities moved over time?

\hypertarget{social-capital-and-urban-regimes}{%
\subsubsection{2.4.4 Social Capital and Urban
Regimes}\label{social-capital-and-urban-regimes}}

However, municipalities with greater collective action potential might
be more likely to adopt social welfare regimes, if local residents have
strong social capital. Past literature highlights that social capital,
the social ties that bind residents \citep{putnam_2000, woolcock_2010},
come in three different forms with distinct impacts on public
participation and policymaking: bonding, bridging, and linking social
capital \citep{aldrich_and_meyer_2015}.

\hypertarget{bonding-social-capital}{%
\paragraph{Bonding Social Capital}\label{bonding-social-capital}}

Bonding social capital refers to strong in-group ties between members of
the same social strata (eg. race, ethnicity, age, gender, income)
\citep{mcpherson_et_al_2001, mouw_2006}. One might expect bonding social
ties to help residents petition for more middle class interests, which
benefit a broad swath of residents, but fail to organize broad,
cross-community coalitions to support social welfare
\citep{tsai_2007, cox_2011, alcorta_et_al_2020}.

\hypertarget{bridging-social-capital}{%
\paragraph{Bridging Social Capital}\label{bridging-social-capital}}

In contrast, bridging social capital refers to strong inter-group ties
connecting members of different social strata (eg. members of different
racial, ethnic, age, gender, or income backgrounds)
\citep{putnam_2000, aldrich_2019}. A vast literature suggests that
stronger bridging social ties help residents organize to improve access
to public goods for the \emph{entire} community, because they build
strong inter-group trust and reciprocity that encourages folks to
mobilize, vote, and participate in civil society.

\hypertarget{linking-social-capital}{%
\paragraph{Linking Social Capital}\label{linking-social-capital}}

Finally, linking social capital refers to vertical ties connecting
residents to local officials \citep{woolcock_2010, aldrich_2019}. One
might expect that municipalities with stronger linking social capital
are less likely to be caretaker regimes, but could result in greater
social welfare, developmental, or middle class regimes, depending on
residents' interests. In addition to the concepts discussed above,
municipalities with higher levels of education and lower levels of
population turnover also tend to build stronger social ties. To date
however, despite the strong likelihood of a connection between social
capital and urban regimes, no study to the author's knowledge has yet
investigated these two concepts together.

\hypertarget{hypotheses}{%
\subsection{2.6 Hypotheses}\label{hypotheses}}

In summary, these four types capture a wide range of urban regime
literature, each with distinct priorities that would lead to \emph{more}
or \emph{less} spending in specific areas. I formalize these
expectations with 3 hypotheses:

\begin{itemize}
\item
  \textbf{H1}: First, I hypothesize that these urban regimes are not
  evenly distributed throughout the country, but rather that some types
  of urban regimes are increasing over time.
\item
  \textbf{H2}: Second, I hypothesize that social welfare regimes,
  compared to other types, have increased over the last two decades of
  climatic hazards, opening up new communities to new changes in the
  social safety net.
\item
  \textbf{H3}: Third, I hypothesize that municipalities with greater
  collective action potential, particularly those with greater bridging
  social capital, were more likely to develop social welfare regimes.
\end{itemize}

Below, I outline set of methods to measure each municipality's
propensity towards these four regimes.

\hypertarget{data}{%
\section{3. Data}\label{data}}

This study aims to describe and characterize the urban regimes of a
large-N sample of municipalities over time, to determine how and under
what conditions these municipalities' regimes have changed. I examine
the case of Japan, tracking the full universe of municipalities (cities,
towns, villages, and Tokyo's special wards) that govern their own
budgetary and administrative affairs, as each is capable of producing an
urban regime that shapes local governance and spending.

\hypertarget{why-japan}{%
\subsection{3.1 Why Japan?}\label{why-japan}}

While the urban regime framework was originally developed in a US
context \citep{stone_1989}, it has been applied widely throughout the
world, with strong followings in the US \citep{kilburn_2004}, UK
\citep{bassett_1996, davies_2017}, Europe
\citep{stoker_and_mossberger_1994, arbaci_2019}, Japan
\citep{hill_fujita_2000, saito_2003, sorensen_et_al_2010, tsukamoto_2012},
China, Hong Kong \citep{lai_and_chui_2014}, South Korea
\citep{shin_et_al_2015}, and comparative settings
\citep{mossberger_and_stoker_2001, ramirez_perez_et_al_2008}. Japan is a
useful test case as an industrialized democracy and the 3rd largest
economy in the world, a useful comparison case for many Global North
states like the US, UK, France, Germany, South Korea, and Taiwan, among
others. Further, Japan faces frequent floods, typhoons, and earthquakes,
with more severe outcomes compared to peer economies; between 2010 and
2020, Japan ranked 10th worldwide in highest deaths per capita and 4th
in highest injuries per capita \citep{ritchie_roser_2021}. Consequently,
Japan's experience gives us a glimpse of what kind of urban regime
transition one might expect in future years due to climate
change-induced disasters in the municipalities of similar industrialized
democracies.

\hypertarget{unit-of-observation}{%
\subsection{3.2 Unit of Observation}\label{unit-of-observation}}

I track the full universe of 1739 municipalities for which spending data
was available between 2000 and 2018, over 19 years. The final sample
narrows into 1738 unique municipalities, which varied over time due to
mergers and new divisions, from 1428 municipalities in 2000 to 1727
municipalities in 2018, dubbed `municipalities' below, totaling 31,493
municipality-year observations. To ensure a comparable sample, this
omits 12 outlier municipalities at times.\footnote{I omitted 11
  municipalities in the Fukushima Exclusion Zone from 2011 onwards, plus
  Yubari, Hokkaido for the full period, totaling 12 municipalities (n =
  107 municipality-years). I omit these because these extremely
  depopulated municipalities face dire social and economic conditions
  quite different from the rest of Japan.} My sample includes urban and
rural municipalities alike, for two reasons. First, Japanese
municipalities, rural \emph{and} urban alike, tend to have much higher
population density than American or European counterparts. Second, while
urban regime theory originally discussed cities, the 4 urban regime
types (developmental, middle-class, social welfare, and caretaker
regimes) I investigate here are not especially population-size dependent
at all; these regimes and the policy decisions they affect could
conceivably appear in municipalities large or small. Several examples of
Japanese municipalities large (Tokyo, Kyoto, Kobe) and small (Minamata,
Iida, Onagawa, Satsumasendai) relevant to urban regime concepts are
referenced in the literature review above.

\hypertarget{urban-regime-indices}{%
\subsection{3.3 Urban Regime Indices}\label{urban-regime-indices}}

To represent urban regimes, this study developed new indices. Clarence
Stone and likeminded scholars sorted cities into 4 types of urban
regimes, including caretaker (status quo), developmental (pro-business),
middle-class (egalitarian), and social-welfare (working-class) governing
coalitions
\citep{stone_1989, stoker_and_mossberger_1994, mossberger_and_stoker_2001, kilburn_2004, de_socio_2007}.
Over time, Stone himself advocated for attention to change over time in
urban regimes, arguing that ``there is little reason to expect a stable
and cohesive governing coalition in today's cities''
\citep{stone_et_al_2015}. For this reason, one might now expect
considerable variation in urban regimes among municipalities, especially
over time. Though the inner-workings of governing coalitions in Japan's
municipalities are black boxes, unobservable without detailed
qualitative study of each, these coalitions can be generally sorted
based on \emph{how strongly each municipality's spending reflects the
interests of a specific urban regime.} This matches Stone's original
conception of urban regimes, about which he wrote: ``If a governing
coalition is to be viable, it must be able to mobilize resources
commensurate with its main policy agenda'' \citep{stone_1993}.

To represent these 4 urban regimes, this study presents 3 new indices,
based on 15 spending indicators, depicting how much a municipality
prioritizes spending types expected in a \textbf{social welfare} (SW),
\textbf{middle class} (MC), or \textbf{developmental} (D) regime
respectively, where low scores among all 3 depicting a
\textbf{caretaker} regime (C). Each regime index reflects the average
(mean) of municipalities' logged spending rates on priorities that
regime typically champions (described further below). I trimmed all
logged rates to the 99\% most common values to protect against outlier
bias, clipping any municipality-years above the 99.5th percentile or
below the 0.5th percentile at those limits.\footnote{I use the mean,
  rather than median, to give each spending priority equal weight; the
  mean better captures variation particularly when one of these
  priorities (eg. social assistance vs.~unemployment) exceeds or lags
  behind others.}

\hypertarget{indicators}{%
\subsubsection{3.3.1 Indicators}\label{indicators}}

Annual spending indicators are logged municipal spending rates, measured
in 1000s of yen per capita to account for population, log-transformed to
account for right-skew common in rates, and inflation-adjusted to the
year 2020. I transformed each indicator into a mean-centered z-scores,
to account for different ranges, and averaged related indicators
together into the 3 indices. To demonstrate their internal validity
below, I introduce each indicator and report their correlation with
their respective index below, using the Pearson's r correlation
coefficient (where -1 shows negative trends, +1 shows positive trends,
and 0 shows neither). Each indicator captures a different aspect of that
urban regime; no regime must invest equally in, for example, each social
welfare indicator to count as such a social welfare regime, so maximal
correlations are unlikely, but positive correlations are a good sign of
internal validity.

Each indicator shows positive correlations with their overall index.
This is a great sign, indicating that an increase in any of the three
indices does generally correspond to a strong increase in its
indicators. Additionally, spending rates produced better internal
consistency than percentages of the budget, likely because each
municipality's share of spending on different issues varies depending on
external factors.

\begin{itemize}
\item
  The \textbf{Social Welfare regime} index combines 6 types of spending
  on working-class interests, which are highly correlated with the final
  index, according to their Pearson's r correlation coefficient. These
  including (1) social welfare assistance for low income residents (r =
  0.65), (2) assistance for children (0.45), (3) assistance for elders
  (0.66), (4) labor expenditures including unemployment relief and
  vocational training (0.3), (5) emergency services like fire
  departments (0.58), and (6) public housing (0.32). Correlations vary
  somewhat, since some social welfare regimes focus more on unemployment
  while others focus more on social welfare for elders and children, for
  example, and so my average takes this variation into account.
\item
  The \textbf{Middle Class regime} index combines spending on 5
  middle-class interests, which are highly correlated with the final
  index. These include (7) education (r = 0.5), (8) social education
  (including lifelong learning and cultural facilities) (0.42), (9)
  health care and public health services (0.59), environmental interests
  like (10) waste and recycling (0.42), and (11) city planning (0.17).
  (Planning has a weaker, but clearly positive linear relationship with
  middle class regimes, and it is an important aspect of municipalities
  focused on quality of life.)
\item
  The \textbf{Developmental regime} index combines spending rates on 4
  economic development interests, which correlate well with the final
  index. These include (12) agriculture, forestry, and fisheries (r =
  0.64), (13) commerce and manufacturing (0.49), large infrastructure
  like (14) roads and bridges (0.69), as well as (15) ordinary
  construction works (0.62).
\end{itemize}

Each index is mean-centered, where 0 represents the average level of
spending nationwide over time on a certain regime's issue areas, and
higher/lower values denote more/less spending rates on that regime's
issue areas, on average. -1 represents one standard deviation lower
spending than average, and +1 represents one standard deviation higher
than average. Their distributions are highlighted in
\textbf{Figure \ref{fig:figure_A1}}.

How well do my indices approximate their indicators? In
\textbf{Figure \ref{fig:lines}}, I visualize the average normalized
spending rate (Z-scores) over time for each index (thick line) and their
corresponding indicators (thin lines). This figure shows how closely
each set of indicators match the rise and fall of their index.
Additionally, using the full sample of 40,062 municipality-years
available for indices, I generated simple multivariate linear models to
how well my indicators predict the overall index. If they closely match,
this indicates strong internal validity. The percentage of variation
explained (\(R^{2}\)) and average error (\(\sigma\)) for each simple
model are presented in each panel. These show that my indicators predict
the index extremely well, explaining between 99.3-99.9\% of the
variation in index scores over time, with an average error of at max
0.045 standard deviations from the mean.\footnote{Details available in
  the replication code.}

\begin{figure}
\includegraphics[width=1\linewidth]{../viz/mean_trends} \caption{Figure \ref{fig:lines}: Indices closely follow Indicator Trends}\label{fig:lines}
\end{figure}

\hypertarget{index-limitations}{%
\subsubsection{3.3.2 Index Limitations}\label{index-limitations}}

One limitation of this measurement strategy is that it does not
\emph{directly} measure caretaker regimes (C) through their spending,
but rather through how they \emph{do not} spend as much per capita on
social welfare, middle class, or developmental regimes interests. There
\emph{could} be additional variation in the remaining fraction of
municipal spending for these caretaker-designated regimes. Future
scholars are encouraged to investigate and measure these
caretaker-designated regimes in further granularity. But for this
study's purposes, a municipality that does not \emph{not} deeply invest
in one of these core 3 spending areas (social welfare, middle class, or
developmental interests) would be maintaining the status quo \emph{in
these 3 core areas}; for this reason, I dub these lower-spending regimes
`caretaker' regime at least in this context.

Fortunately, even if these `caretaker'-designated regimes are further
subdivided in future studies, the analyses below should remain broadly
unaffected. First, my classification analysis in Figure
\textbackslash ref\{fig-area\} and Figure \textbackslash ref\{fig-map\}
discussed below would simply see their caretaker regime categories
further subdivided into separate chunks; the social welfare trend I
describe should not be impacted. Second, my statistical analyses of
correlates of regime indices rely on my 3 indices for social welfare,
middle class, and developmental regime indices, and so are not directly
impacted by caretaker regime measurement, and these models explain
extremely high percentages of variation. Any future index development, I
expect, would only further refine estimates' effect size.

Finally, these indices were built by each taking the \emph{average} of
logged spending rates. I used averages for \emph{clarity}, to provide
clear indexes that are easier for decision-makers to understand and
utilize. There are many alternative strategies for building indices,
including factor analysis and principal component analysis, which are
used to identify latent trends in a series of indicators. Factor
analysis usually distills several indicators that may trend together
(eg. social welfare spending for elders vs.~for children) into one or
more factors; a municipality that invests heavily in both would no
longer receive equal weight for both when combining factors further.
However, I used simple averages here specifically so that each indicator
is \emph{equally weighted}. This means that a city which, for example,
spends a moderate rate on unemployment relief but larger rates on social
welfare for elders than peer municipalities would see their social
welfare regime index rise somewhat, because investment in \emph{any} of
these indicators would demonstrate greater commitment to social welfare
regime priorities. Likewise, greater investment in \emph{all} of these
indicators would increase the index even more. Future studies are
encouraged to apply factor analyses where helpful, particularly in
investigating caretaker regimes.

\hypertarget{classifying-municipalities-by-regime-type}{%
\subsubsection{3.3.2 Classifying Municipalities by Regime
Type}\label{classifying-municipalities-by-regime-type}}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item[1] City-years classified based on three regime scores being above (High) or below (Low) threshold.
\item[2] \% of cases, when using median as threshold; robustness check uses mean as threshold.
\end{TableNotes}
\begin{longtable}[t]{>{\raggedright\arraybackslash}p{3.9cm}>{\raggedright\arraybackslash}p{1.75cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.75cm}>{\raggedleft\arraybackslash}p{1.25cm}>{\raggedleft\arraybackslash}p{1.25cm}}
\caption{\label{tab:regimeclass}\textbf{Table \ref{tab:regimeclass}: \label{tab:regimeclass}{Regime Classifications}}}\\
\toprule
\multicolumn{2}{c}{ } & \multicolumn{3}{c}{Index Scores$^{1}$} & \multicolumn{2}{c}{\makecell[c]{Percentage of Cases\\by Threshold$^{2}$}} \\
\cmidrule(l{3pt}r{3pt}){3-5} \cmidrule(l{3pt}r{3pt}){6-7}
Name & Code & Social Welfare & Middle Class & Developmental & Median & Mean\\
\midrule
\addlinespace[0.10cm]
\multicolumn{7}{l}{\textbf{\makecell[l]{\\Classic Regimes}}}\\
\hspace{1em}\cellcolor[HTML]{ffb000}{\textcolor{black}{Social Welfare}} & SW & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 8.1 & 8.5\\
\hspace{1em}\cellcolor[HTML]{648FFF}{\textcolor{white}{Middle Class}} & MC & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 7.8 & 6.4\\
\hspace{1em}\cellcolor[HTML]{696880}{\textcolor{white}{Developmental}} & D & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 5.9 & 6.9\\
\hspace{1em}\cellcolor[HTML]{ADADC9}{\textcolor{black}{Caretaker}} & C & \cellcolor{white}{Low} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 28.6 & 33.4\\
\addlinespace[0.25cm]
\hline
\multicolumn{7}{l}{\textbf{\makecell[l]{\\Hybrid  Regimes}}}\\
\hspace{1em}\cellcolor[HTML]{DC267F}{\textcolor{white}{Social Welfare Hybrid (1)}} & SW-MC & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 5.6 & 4.4\\
\hspace{1em}\cellcolor[HTML]{ff683b}{\textcolor{white}{Social Welfare Hybrid (2)}} & SW-D & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 7.4 & 8.3\\
\hspace{1em}\cellcolor[HTML]{5542AD}{\textcolor{white}{Hybrid}} & SW-MC-D & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & 29.0 & 25.3\\
\hspace{1em}\cellcolor[HTML]{001FA2}{\textcolor{white}{Middle Class Hybrid}} & MC-D & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & 7.7 & 6.9\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}
\renewcommand{\baselinestretch}{1}\selectfont

\doublespacing

Next, I use these indices to empirically classify municipalities into
urban regime types, using my 3 indices' medians to demarcate 8
classifications, to represent the general range of regimes a
municipality can occupy, including my 4 primary urban regimes and 4
hybrids. \textbf{Table \ref{tab:regimeclass}} lists each combination. If
just 1 index ranked above the median, I classified a municipality as
that type of regime, including Social Welfare (SW = 8.1\%), Middle Class
(MC = 7.8\%), and Developmental regimes (D = 5.9\%). If all 3 indices
ranked below the median, I classified that as a Caretaker regime (C =
28.6\%). \textbf{Hybrids} describe municipalities prioritizes interests
of 2 or more regimes. If 2 indices ranked above the median, I classified
that as either a Social Welfare Hybrid Regime (SW-MC = 5.6\%, SW-D =
7.4\%) or a Middle Class Hybrid Regime (MC-D = 7.7\%). 3 indices above
the median translate to a full hybrid regime (SW-MC-D = 29\%). The more
common hybrids tend to involve Social Welfare traits (and follow the
same increase over time as social welfare regimes). (I repeated this
process using the mean as my cutpoint, showing similar proportions of
cases in each group.)

\hypertarget{change-over-time}{%
\subsection{3.4 Change over Time}\label{change-over-time}}

\begin{figure}
\includegraphics[width=1\linewidth]{../viz/bands} \caption{Figure \ref{fig:bands}: Urban Regime Indices Change Over Time}\label{fig:bands}
\end{figure}

\doublespacing

But are these urban regimes fixed, or fluid? Do municipalities
transition between regime types to accomplish their aims? I examined
this with continuous and categorical analyses below. First, in Figure
\ref{fig:bands}, I examined the changing median score (\textbf{black}
line) over time for my 3 urban regime indices. Surrounding the median,
red bands show the most common 50\% of scores, represented by the
interquartile range (25-75th percentiles), and grey bands show the most
commonly occurring 90\% scores among municipalities (5-95\%
percentiles). This chart shows that while municipalities' status as
developmental and middle class regimes (based on their spending) did not
change especially, the share of municipalities spending more on social
welfare issues sharply increased in the years leading up to and after
2011.

\begin{figure}
\includegraphics[width=1\linewidth]{../viz/percent_area} \caption{Figure \ref{fig-area}\label{fig-area}: Change in Regime Types by Percentage over Time}\label{fig:area}
\end{figure}

\doublespacing

Second, to contextualize this, I measured the changing annual
percentages of regimes based on their urban regime classifications from
\textbf{Table \ref{tab:regimeclass}}; I stack the 4 types of regimes
where social welfare regime indices were above the median. This
highlights the sizable increase in social welfare spending. Social
welfare regimes (yellow) increased from \textgreater1\% in 2000 to 13\%
in 2018, with a max of 14\% in 2012. Including social welfare hybrid
regimes that also focused on middle class (orange) or developmental
spending (red), these increased from 5\% in 2000 to 32\% in 2018,
surging 18\% between 2008 to 2012 to 31\% in 2012. When I include hybrid
regimes that spent above the median on social welfare, middle class, and
developmental interests (purple), the total share spikes considerably.
This combined total represents all municipalities that spent above the
median on social welfare, regardless of their other regime scores.
Starting at 23\% in 2000, the share of municipalities that spent above
the median on social welfare share increased considerably between 2008
and 2012, jumping 33\% from 35\% to 68\%, ending in 2018 at 70\% of the
whole sample. During the same period, the frequency of solely middle
class or developmental regimes declined greatly, from above 10\% each to
below 5\% each, while caretaker regimes surged, then declined, starting
and ending at about a quarter of municipalities.

\begin{figure}
\includegraphics[width=1\linewidth]{../viz/map_categories_3b} \caption{Figure \ref{fig-map}\label{fig-map}: The Spread of Social Welfare Regimes Over Time}\label{fig:map}
\end{figure}

The spread of social welfare regimes is especially evident in Figure
\ref{fig-map}, which uses an Azthumal Equidistant Projection, titled for
readability (North is on the right), to map \emph{when} and \emph{where}
these social welfare-inclined regimes emerged. East, northeast, and
southeast Japan transitioned from caretaker regimes in 2000 to many new
social welfare-related regimes by 2018. While the 2011 tsunami likely
impacted this, the change appears to have preceded the 2011 tsunami,
with many social welfare regimes emerging already by 2010. (Among
others, one contributing factor could be the Democratic Party of Japan's
brief stint in power from 2008 to 2011.) By 2018, a full 20.9\% of
municipalities in Kyushu had become pure Social Welfare regimes, with
similar results in Shikoku (18.9\%) and Chugoku (15.9\%). After
including social welfare hybrids (SW-M \& SW-D), social welfare-related
regimes are even more common in Shikoku (47.4\%), Kyushu (46.5\%),
Kansai (39.6\%), and Chugoku (36.4\%). And after including pure hybrids
(SW-MC-D), this covers almost all municipalities in some regions,
especially frequent in Hokkaido (97.8\% of municipalities), Shikoku
(91.6\%), Kyushu (87.2\%), Chugoku (84.2\%), and Tohoku (84.2\%). These
tallies represent a major change from 2000, when pure social welfare
regimes were most common in Kyushu (2.4\%). (Some places do, however,
seem to host more hybrid regimes over time; hybrid appear very common in
rural regimes in Hokkaido both in 2000 (72.4\%) and in 2018 (97.8\%),
characterized by high per-capita spending on all three types of spending
priorities.)

To summarize, these descriptive investigations show that municipalities
do transition between regime types, and that social welfare regimes have
become considerably more common over time. But perhaps these increases
are merely artifacts of other demographic or political economic changes;
to ensure a more accurate picture, I turn to statistical methods with
controls below.

\hypertarget{methods}{%
\section{4. Methods}\label{methods}}

Next, I turn to statistical models to discern clearer estimates of the
effect of time on urban regimes and of key correlates. Using the social
welfare regime index as my dependent variable, I applied ordinary least
squares models with annual fixed effects, the appropriate technique for
a normally distributed outcome. Annual fixed effects account for
temporal heterogeneity, the appropriate technique for capturing distinct
effects each year. I generated 8 models (see
\textbf{Table \ref{tab:tablea2}}), each with successively more
statistical or design-based controls, to ensure my results are robust to
model specification. (Then, for further validation, I repeated these
models, predicting as my dependent variable the middle class regime
index, in \textbf{Table \ref{tab:tablea3}}, and then the developmental
regime index, in \textbf{Table \ref{tab:tablea4}}).

\hypertarget{basic-covariates}{%
\subsection{4.1 Basic Covariates}\label{basic-covariates}}

I employ 23 statistical controls with annual and prefectural fixed
effects to predict social welfare regime scores. In Model 1, I predicted
social welfare regime scores using annual fixed effects plus basic
demographic controls, including (1) population, (2) inhabitable area in
hectares to account for municipality size, (3) the percentage of
residents over age 65, to account for aging and policy preferences from
elders vs.~working-age adults, and (4) income per capita in 1000s of
yen, to account for wealth. Further, I applied basic revenue controls:
To represent municipalities' spending capacity, I controlled for (5)
revenue per capita in 1000s of yen; (6) the percentage of revenue coming
from national or prefectural government funding, to account for
financial autonomy or lack thereof; and (7) each municipality's real
term budget balance, so as not to overvalue the strength of a regime
whose spending exceeds its means.

In Model 2, I added 5 disaster controls. To account for disaster
conditions, I controlled for (8) disaster deaths and (9) buildings
damaged, each per 100,000 residents, as well as (10) whether each town
was hit by the 2011 tsunami or not (1/0). Further, I controlled for
disaster spending rates per 1,000 residents on (11) recovery, meaning in
this context physical reconstruction, and (12) disaster relief. None of
my urban regime indicators overlap with disaster spending, although one
might expect that social welfare and developmental priorities might
overlap with recovery and relief efforts, so they are important
covariates.

Next, in Model 3, I added controls for the other 2 regime indices not
being predicted; when predicting social welfare, I controlled for (13)
middle class and (14) developmental regime scores, to disentangle their
effects.

Then, in Model 4, I added partisanship and collective action, alongside
necessary controls. To represent support for political parties, I
controlled for the percentage of voters who voted for the winning LDP
candidate (or its coalition partner Komeito, which competes in separate
jurisdiction). This helps account for pork-barrel politics, common among
LDP candidates, where winning candidates reward supporting constituents
with public works funding and construction contracts. I controlled for
this two ways, using votes (15) in the most recent Lower House Election
and (16) in the most recent prefectural election, to account for the
more diverse politics of local elections. These are distinct concepts,
with weak correlations (r = 0.12). These are better controls than, say,
mayoral partisanship, because Japanese mayors often run as nonpartisan
and \emph{must} collaborate across party lines to govern.

In addition to political ties, I also controlled for (17) bonding, (18)
bridging, and (19) linking social capital, using Fraser's annual social
capital indices (2000-2017), which measure each type of social capital
from 0 to 1 by averaging indicators from publicly available proxies.
These indices demonstrated strong internal and external validity in
their validation study \citep{fraser_2021_IJDRR}, predicting known
correlates in public policy on environment, disasters, and health in 9
studies to date
\citep[eg.][]{fraser_et_al_2020, fraser_and_aldrich_2021_SR, fraser_et_al_2021_CRM, fraser_et_al_2022_EIST}.
The \textbf{\emph{bonding index}} averages 7 proxies of in-group ties
that capture how much residents in a community hail from the \emph{same}
social strata using fractionalization metrics, in terms of (17.1)
nationality, (17.2) religion, (17.3) education, (17.4) employment
status, (17.5) employment by gender, (17.6) communication capacity, and
(17.7) age. These homophily measures (not sheer demographics) capture
the density of potential in-group social ties between members of the
same social strata (see \citet{fraser_2021_IJDRR} for extended
literature). The \textbf{\emph{bridging index}} averages 8 measures of
civil society participation, which tend to facilitate encounters and
social ties between members of \emph{different} social strata
\citep{putnam_2000}. These include population-normalized rates of (18.1)
nonprofits, (18.2) religious groups, (18.3) unions, (18.4) community
centers, (18.5) libraries, (18.6) volunteerism, and (18.7) voter turnout
in prefecture and (18.8) lower house elections. (I simplified the
bridging index into equally sized quartiles to avoid collinearity with
regime indicators, while still capturing a 4-point gradation from low to
high.) Finally, the \textbf{\emph{linking index}} averages 6 rates of
access and connection to government officials, including rates per
capita of (19.1) local officials, (19.2) prefectural officials, (19.3)
police, (19.4) prefectural assembly members, and voteshare won by the
winning party in (19.5) prefectural and (19.6) lower house elections.
For additional information, please see the validation study
\citep{fraser_2021_IJDRR}.\footnote{Winning party support is different
  from my controls for partisanship, which only captures the
  LDP/Komeito, excluding the Democratic Party of Japan, which was in
  power from 2009 to 2012). Social capital indices are distinct from
  partisanship controls; Lower House partisanship is only weakly
  correlated with bonding (r = -0.12), bridging (r = \textasciitilde0),
  and linking (r = 0.34); prefectural partisanship is only weakly
  correlated with bonding (r = -0.09), bridging (r = -0.05), and linking
  (r = 0.06).}

Last, I added to Model 4 controls for (20) education, using the share of
college educated adults, (21) the share of unemployed adults in the
labor force, and (21) the total migration rate, reflecting the sum of
any in- or out-migration, which might negatively impact social cohesion
and is an important control.

\hypertarget{robustness-checks}{%
\subsection{4.2 Robustness Checks}\label{robustness-checks}}

Next, I added several further adjustments to ensure robust estimation.
In Model 5, I added prefectural fixed effects, with Hokkaido as the
baseline and modal category, to account for geographic heterogeneity.
Then, in Model 6, I controlled for path dependence using a 1-year lagged
dependent variable; for social welfare, this means controlling for the
preceding year's social welfare score. Then, in Model 7, to guard
against endogeneity bias, I lagged by 1 year all other predictors (aside
from annual and prefectural fixed effects), to predict the \emph{next}
year's urban regime score using the preceding year's data. Lags
constrains the sample in Models 6 onwards to 29755 cases (2001-2018),
but ensures conservative estimates.

Finally, in Model 8, I add a series of standard log, logit, and root
transformations to my predictors to better match their distributions and
capture clear nonlinear trends, adding a small constant where necessary.
Area, income, and migration were logged. Revenue used the square root;
the 10th root was used for Population (to avoid colinearity with
spending), disaster deaths, damages,recovery spending, and relief
spending (since the distributions have frequent, meaningful zeros). Age,
voteshares, social capital, education, and unemployment were logit
transformed, since they are bounded at 0 and 1; the bridging index was
left in quartiles to avoid collinearity with regime indicators.
Descriptive statistics and exact transformation for all predictors are
shown in \textbf{Table \ref{tab:tablea1}}.

These transformations made statistically significant improvements in
log-likelihood compared to Model 7 (p \textless{} 0.001); similarly, the
change in deviance statistic shows statistically significant reductions
in the residual sum of squares after adding new variables to each model,
indicating that Model 8 fit best. F Statistics shows that each model
fits better than an intercept model. No problematic collinearity was
observed, with all variance inflation factor scores below 10, the
threshold for problematic collinearity. Multiple imputation (i = 5) was
used to fill in missing data, representing less than 1\% of data points
(0.3\%).\footnote{Variables with missing data included prefectural votes
  (n = 1299, \textless0.172\%), lower house votes (n = 521,
  \textless0.069\%), income (n = 269, \textless0.036\%), and college (n
  = 46, \textless0.006\%), revenue-derived varaibles (n = 14,
  \textless0.002\%).}

Compared to my first model, my final, fully specified, transformed model
explains 92\% of the variance in social welfare regimes, an extremely
high amount. Further, the sigma statistic (residual standard error) in
\textbf{Table \ref{tab:tablea2}} shows that my final model predicts each
municipality-year's social welfare regime score with an average error of
just 0.18 points, and within a 95\% confidence interval of 0.35 points.
These are extremely favorable accuracy levels, considering that my
outcome has a range of 5.12.

Then, I applied the same analyses to middle class and developmental
indices, repeating Models 1-8 from \textbf{Table \ref{tab:tablea2}} as
developmental models 9-16 in \textbf{Table \ref{tab:tablea3}} and
middle-class regime Models 17-24 in \textbf{Tables A4}, as alternative
perspectives. However, my main analysis focuses on social welfare
regimes, to distinguish the drivers behind the rise of this regime over
time. My best models (Models 8, 16, and 24) explain extremely high
shares of variation in social welfare (R2 = 92\%,
\textbf{Table \ref{tab:tablea2}}), developmental (R2 = 93\%,
\textbf{Table \ref{tab:tablea3}}), and middle class regime scores (R2 =
83\%, \textbf{Table \ref{tab:tablea4}}).

\hypertarget{hypothesis-testing}{%
\subsection{4.3 Hypothesis Testing}\label{hypothesis-testing}}

Finally, having applied a large set of controls to account for
alternative explanations, I formally test my hypotheses on my models
using the following strategies. To test my first and second hypotheses,
that (\textbf{H1}) regimes scores are changing over time and that
(\textbf{H2}) social welfare regimes are changing more than other
regimes, I used linear hypothesis tests in
\textbf{Table  \ref{tab:linearhyp}}. Linear hypothesis tests
\citep{hothorn_et_al_2008, bretz_et_al_2016} can compare two model
coefficients within the same model to evaluate whether one coefficient
is greater than the other, as well as whether that difference is
\emph{statistically significant}.

Using the annual fixed effects from the fully specified models for each
index (Models 8, 16, \& 24), I evaluated whether, for example, the
effect of 2002 was significantly different from the benchmark compared
to the benchmark year of 2001 (ie. whether the coefficient was
significantly different from zero). Then, I evaluated average annual
effect across all years \emph{before} the 2011 disaster (2002-2010), and
the average annual effect \emph{after} the 2011 disaster (2011-2018).
This allowed me to compute the average treatment effect of the
post-disaster period compared to the pre-disaster period. Should these
effects be significant, it would indicate that urban regimes have, on
average, changed greatly over time, even accounting for all other model
covariates. Then, to test my second hypothesis, I compare average
treatment effects across different regime types, also in
\textbf{Table \ref{tab:linearhyp}}. If social welfare regimes saw a
significant average treatment effect, but developmental and middle class
regimes did not, this would indicate social welfare regimes were
disproportionately impacted by this sea-change in urban regimes.

Finally, to test my third hypothesis, that collective action potential
is associated with municipalities' transition to social welfare regimes,
I investigated the effects bonding, bridging, and linking social capital
on each regime index, by interpreting the beta coefficients from my
fully specified models (Models 8, 16, \& 24).

\hypertarget{results}{%
\section{5. Results}\label{results}}

This study set out to examine (\textbf{H1}) \emph{whether} urban regimes
in Japanese have changed measurably in terms of spending priorities over
the last 20 years, (\textbf{H2}) whether social welfare regime in
particular have grown more common, after accounting for alternative
explanations with statistical controls, and (\textbf{H3}) whether
collective action potential is related to the hypothesized rise in
social welfare regimes. Below, I outline my findings, focusing
especially on my fully specified Model 8.\footnote{In Model 8, the
  median municipality-year evaluated has the following covariate traits:
  This municipality has a population of 24,750 residents, spans 4,170
  hectares of inhabitable land, hosts an income per capita of 1,199,190
  yen per capita (\textasciitilde\$9,183 USD), with 28\% of residents
  over age 65. The median municipality in Japan during this period also
  has low rates of adults with some college education (25\%), moderately
  high unemployment (4.6\%), and shares of high total migration (6\%).
  It received 503,740 yen per capita in revenue last year, 16\% of which
  came from national or prefectural government, and has a real term
  budget balance of +4.7. The municipality voted for winning LDP/Komeito
  candidate in moderate-to-high rates, at 51\% in Lower House elections
  and 32\% in prefectural elections. Further, I assume median levels of
  bonding (0.71), bridging (0.32 \textasciitilde{} 2nd quartile), and
  linking social capital (0.25).}

\singlespacing
\newpage
\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{8}{10}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. Based on annual fixed effects from Models 8, 16, \& 24 in Tables A2, A3, \& A4, respectively.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{2.25cm}>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.5cm}>{}l>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.5cm}>{}l>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.5cm}>{}l}
\caption{\label{tab:linearhyp}\textbf{Table \ref{tab:linearhyp}: Linear Hypothesis Tests of Temporal Effects}}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{\makecell[c]{Social Welfare\\Regime}} & \multicolumn{3}{c}{\makecell[c]{Developmental\\Regime}} & \multicolumn{3}{c}{\makecell[c]{Middle Class\\Regime}} \\
\cmidrule(l{3pt}r{3pt}){2-4} \cmidrule(l{3pt}r{3pt}){5-7} \cmidrule(l{3pt}r{3pt}){8-10}
Year & Estimate & SE & 95\% CI & Estimate  & SE  & 95\% CI  & Estimate   & SE   & 95\% CI  \\
\midrule
\addlinespace[0.3em]
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Pre-Disaster}}}\\
\hspace{1em}\cellcolor{gray!6}{2002} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45445a454aaf.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45444a982231.pdf} & \cellcolor{gray!6}{+0.01} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544a4f4d33.pdf}\\
\hspace{1em}2003 & -0.02. & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45445f7f1b20.pdf} & -0.08*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454465857111.pdf} & -0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454452ee5f45.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2004} & \cellcolor{gray!6}{+0.03**} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544302a1ecf.pdf} & \cellcolor{gray!6}{-0.06***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45443bed42da.pdf} & \cellcolor{gray!6}{-0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544445517d8.pdf}\\
\hspace{1em}2005 & +0.04*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45446f98438f.pdf} & -0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454444a7508a.pdf} & -0.01 & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454471412848.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2006} & \cellcolor{gray!6}{+0.02*} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45441b56203.pdf} & \cellcolor{gray!6}{-0.09***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454464765ed2.pdf} & \cellcolor{gray!6}{-0.03***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454466f34ec2.pdf}\\
\hspace{1em}2007 & +0.03*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447f8c316c.pdf} & -0.1*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45444cd33922.pdf} & -0.06*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45443a336ca1.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2008} & \cellcolor{gray!6}{+0.01} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544550d2dbf.pdf} & \cellcolor{gray!6}{-0.07***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454437ed6307.pdf} & \cellcolor{gray!6}{-0.05***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544659556f7.pdf}\\
\hspace{1em}2009 & +0.1*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45446c0d23fb.pdf} & +0.11*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454425ef73b6.pdf} & +0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45445cfb1569.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2010} & \cellcolor{gray!6}{+0.15***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454488e58b9.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447f814fe9.pdf} & \cellcolor{gray!6}{+0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447a5b341.pdf}\\
\cellcolor[HTML]{D3D3D3}{\textbf{\hspace{1em}Mean Pre}} & \cellcolor[HTML]{D3D3D3}{\textbf{+0.04***}} & \cellcolor[HTML]{D3D3D3}{\textbf{0.01}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45443a417d04.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{-0.05***}} & \cellcolor[HTML]{D3D3D3}{\textbf{0.01}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544419135e9.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{-0.01.}} & \cellcolor[HTML]{D3D3D3}{\textbf{0.01}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454427c26be.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Post-Disaster}}}\\
\hspace{1em}\cellcolor{gray!6}{2011} & \cellcolor{gray!6}{+0.18***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544749656c.pdf} & \cellcolor{gray!6}{-0.06***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454416534fec.pdf} & \cellcolor{gray!6}{+0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45446a9952ae.pdf}\\
\hspace{1em}2012 & +0.13*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454434423756.pdf} & -0.06*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447f8640a2.pdf} & -0.02. & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45443428663f.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2013} & \cellcolor{gray!6}{+0.16***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45444d8296.pdf} & \cellcolor{gray!6}{+0.03**} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454475fa5e0b.pdf} & \cellcolor{gray!6}{+0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45441b583f13.pdf}\\
\hspace{1em}2014 & +0.18*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544559e6d40.pdf} & -0.03** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544224fe8b.pdf} & +0 & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454463bd7192.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2015} & \cellcolor{gray!6}{+0.09***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45443d30fba.pdf} & \cellcolor{gray!6}{-0.02} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454412ff7c40.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454475d31b84.pdf}\\
\hspace{1em}2016 & +0.15*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447d86f16.pdf} & -0.09*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544139f1293.pdf} & -0.03** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45442c8864df.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2017} & \cellcolor{gray!6}{+0.13***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454442814f9f.pdf} & \cellcolor{gray!6}{-0.02*} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45449617a0d.pdf} & \cellcolor{gray!6}{-0.02} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45441bfb2dd.pdf}\\
\hspace{1em}2018 & +0.12*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45442ee669b2.pdf} & -0.08*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454478de66d.pdf} & -0.05*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454435847152.pdf}\\
\cellcolor[HTML]{D3D3D3}{\textbf{\hspace{1em}\cellcolor{gray!6}{Mean Post}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{+0.14***}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454448542d0.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{-0.04***}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454419124af7.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{-0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45446cf4563d.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Average Treatment Effect}}}\\
\cellcolor[HTML]{D3D3D3}{\textbf{\hspace{1em}Post - Pre}} & \cellcolor[HTML]{D3D3D3}{\textbf{+0.1***}} & \cellcolor[HTML]{D3D3D3}{\textbf{0}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45445b11cf0.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{+0}} & \cellcolor[HTML]{D3D3D3}{\textbf{0}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454417a8490e.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{+0}} & \cellcolor[HTML]{D3D3D3}{\textbf{0}} & \cellcolor[HTML]{D3D3D3}{\textbf{\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_4544431e439d.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Net Gain over Time}}}\\
\cellcolor[HTML]{D3D3D3}{\textbf{\hspace{1em}\cellcolor{gray!6}{2018 - 2002}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{+0.12***}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_45447cbd301a.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{-0.04***}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454472786d05.pdf}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{-0.06***}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor[HTML]{D3D3D3}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/pointrange_454459964b86.pdf}}}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\newpage
\renewcommand{\arraystretch}{1}
\doublespacing

\hypertarget{testing-temporal-effects}{%
\subsection{5.1 Testing Temporal
Effects}\label{testing-temporal-effects}}

First, I hypothesized that (\textbf{H1}) urban regimes have changed
measurably over the last 2 decades. My linear hypothesis tests presented
in \textbf{Table \ref{tab:linearhyp}} reveal consistent evidence that
urban regime scores changed over time. After controlling for numerous
alternative explanations listed in the Methods, time had a positive,
statistically significant impact on social welfare scores: the annual
impact in 2018 was +0.12 standard deviations greater than in 2002 (p
\textless{} 0.01), and when comparing annual effects post-disaster to
annual effects pre-disaster, municipalities saw their social welfare
scores rise each year an average of +0.1 standard deviations more
post-disaster than they did pre-disaster (p \textless{} 0.001). Indeed,
each consecutive year from 2004 onwards yielded increases in social
welfare regime scores. (14 years saw increases significant of at least
the p \textless{} 0.05 level.) These findings also complement the
descriptive evidence of considerable changes in social welfare regimes
presented in Figures \ref{fig:bands} and \ref{fig:map}.

Second, I hypothesized that (\textbf{H2}) social welfare regimes
increased annually \emph{moreso} than did other urban regimes. Indeed,
my fully specified models project that, independent of other traits,
between 2002 and 2018, a municipality's social welfare regime score was
expected to increase +0.12 standard deviations (p \textless{} 0.01),
while their developmental and middle-class regime scores were expected
to decrease by -0.04 (p \textless{} 0.01) and -0.06 (p \textless{} 0.01)
standard deviations, respectively. Further, comparing the pre- and
post-disaster periods, an average year post-disaster saw a +0.1 standard
deviation increase in their social welfare score (p \textless{} 0.001),
but their developmental and middle-class regime scores saw no
substantive or statistically insignificant changes.

\#\# 5.2 Collective Action Effects

Third, I hypothesized that (\textbf{H3}) municipalities with greater
collective action potential, as measured by types of social capital, saw
greater increases in their social welfare regime scores. Indeed,
communities with greater bridging social capital indices saw higher
social welfare index scores (+0.01, p \textless{} 0.01, Model 8,
\textbf{Table \ref{tab:tablea2}}); this positive significant association
was shared consistently across all in which models they were included
(Models 4 to 8).

Interestingly, social welfare-related spending tended to be negatively
related to bonding social capital (-0.07, p \textless{} 0.001, Model 8)
and linking social capital (-0.01, p \textless{} 0.10, Model 8),
contrasting the positive relationship with bridging social capital. This
divergence is not unexpected, and speaks towards the Janus-faced nature
of social capital, where bonding (in-group) and linking (vertical ties)
may help residents accomplish their political goals, but those goals
might not be supporting a social welfare agenda \citep{aldrich_2012}. In
contrast, the inter-group trust, reciprocity, and mutual aid that
bridging social capital imparts in a community are extremely compatible
with social-welfare policy; bridging social ties could plausibly help
neighbors band together to confront equity issues by pressuring city
hall or town hall to prioritize more social welfare spending.

Is this association unique to social welfare regimes? In my models of
developmental and middle-class regime scores, I find that greater
bridging social capital is related to increases in development-related
spending priorities (+0.01, p \textless{} 0.001, Model 16,
\textbf{Table \ref{tab:tablea3}}), as well as middle-class spending
priorities (+0.01, Model 24, \textbf{Table \ref{tab:tablea4}}). Bonding
social capital tends to maintain a negative relationship with
development (-0.04, p \textless{} 0.01, Model 16) and
middle-class-regime scores as well (-0.03, p \textless{} 0.05, Model
24). Meanwhile, linking social capital has weaker, positive, but less
significant associations (p \textgreater{} 0.10) with development and
middle-class spending.

In other words, it appears that collective action potential is related
to changes in urban regimes, but this impact is limited to bonding and
bridging social capital. Bonding social capital appears to be negatively
related to these spending indices, implying that strong in-group ties
tend to draw municipalities closer to caretaker regimes. In contrast,
bridging social capital appears to be positively related to each type of
spending change, pushing municipalities further away from caretaker
regimes; one possible explanation is that these bridging ties and the
collective action they enable help residents push municipal officials in
towards whichever style of regime these highly-networked residents
support, but further study is needed to confirm these suspicions. What I
can conclude from this analysis is that collective action potential,
specifically bridging social capital, is positively related to the
increase in each of my three archetypal urban regimes.

\hypertarget{discussion}{%
\section{6. Discussion}\label{discussion}}

\doublespacing

This study measured municipalities' proclivities towards each of 4 types
of urban regimes, commonly discussed in urban policy in the US or Japan
\citep{stone_1989, stoker_and_mossberger_1994, bassett_1996, hill_fujita_2000, kilburn_2004, ramirez_perez_et_al_2008, sorensen_2011}.
These included regimes that focus on promoting (1) \textbf{economic
development} in their municipality (helpful for accelerating renewable
energy booms, but perhaps not for ensuring equitable development with
public support); regimes that focus on promoting (2) \textbf{progressive
middle class interests} like health care, education, and
environmentalism (helpful for renewable energy, but not as common in
less prosperous communities); and regimes that focus on increasing (3)
\textbf{opportunity through social welfare policies}; and regimes that
aim to maintain the (4) \textbf{status quo} in their municipality
(rather undesirable for disaster-prone municipalities where disaster
resilience initiatives are deeply needed). Below, I summarize several
contributions this study makes to the literature on urban regimes, to
expand scholars' understanding of these 4 regime archetypes.

This study made several contributions to the literature, in terms of (1)
evaluating regime change over time in the case of Japan, (2) integrating
social capital and urban regime theory, (3) Large-N methods for urban
regime analysis, and (4) tools for updating case studies.

\hypertarget{contributions-to-the-literature}{%
\subsection{6.1 Contributions to the
Literature}\label{contributions-to-the-literature}}

\hypertarget{evaluating-urban-regime-change-in-japan}{%
\subsubsection{6.1.1 Evaluating Urban Regime Change in
Japan}\label{evaluating-urban-regime-change-in-japan}}

First, this study extended a diverse literature on urban regimes and
governance by formally measuring change over time, using the case of
Japan. This builds on two decades of studies that highlight the depth
and breath of grassroots activism and politics in Japanese urban policy
\citep[eg.][]{leblanc_1999, funck_2007, leblanc_2009, avenell_2010, aldrich_and_fraser_2017},
but formalizes it in the context of urban regime theory
\citep{stone_1989}. In the cases examined in Japan, municipalities with
social-welfare oriented regimes tended to be deeply interested in
disaster resilience, where municipal officials were deeply concerned
with residents' vulnerability during crisis
\citep{maly_2012, aldrich_2012, dimmer_and_lindenberg_2014, matthews_2017, aldrich_2019, cheek_2020, ji_and_imai_2022, abeysinghe_2022}.

Yet, as I show above in the results of this study, some municipalities'
governing coalitions are spending more on redistributive policies than
others municipalities. This is critical, considering that my findings
show \emph{social welfare regimes} are becoming increasingly common in
Japan, and are often mid-size or rural communities, where great changes
in social welfare are not generally expected (due to lower tax base and
many LDP-dominated legislatures, compared to metropolitan areas).

\hypertarget{integrated-analysis-of-urban-regimes-and-social-capital}{%
\subsubsection{6.1.2 Integrated Analysis of Urban Regimes and Social
Capital}\label{integrated-analysis-of-urban-regimes-and-social-capital}}

Second, this study integrated two schools of thought, social capital
\citep{putnam_2000, woolcock_2010, aldrich_2012, alcorta_et_al_2020, fraser_2021_IJDRR}
and urban regime theory \citep{stone_1993, stoker_and_mossberger_1994},
which, while extremely compatible as networked perspectives on
governance, are only rarely examined together \citep{fraser_et_al_2020}.
Specifically, this study analyzed how much municipalities' urban regimes
relate to their social capital indicators after controlling for
alternative sociodeomographic indicators.

My models showed that residents' collective action potential, as
measured by their bridging social ties, correlates consistently with
municipalities' transition away from caretaker regimes and towards their
desired alternative regime, while greater bonding, in-group social ties
correlates with stagnation as a caretaker regime. This highlights that
municipalities, specifically Japanese municipalities, can and do show
feature of specific urban regimes, that these regimes are frequently
transitioning towards social welfare policies, and that collective
action potential is closely related to municipalities' capacity to
change their urban regime.

\hypertarget{a-template-for-large-n-urban-regime-analysis}{%
\subsubsection{6.1.3 A Template for Large-N Urban Regime
Analysis}\label{a-template-for-large-n-urban-regime-analysis}}

This study makes several contributions to the literature. First, it
builds on decades of in-depth small-N
\citep{munoz_and_henry_1986, stone_1989, whelan_et_al_1994, yeum_2002, gendron_and_domhoff_2018}
and medium-N analyses of urban regimes
\citep{kilburn_2004, thompson_2005, de_socio_2007} by providing a
template for rigorous large-N approximations of urban regimes, meant to
expand the scope of comparisons much like recent large-N analyses of
mayors
\citep{ramirez_perez_et_al_2008, debenedictis_kessner_and_warshaw_2016, einstein_and_glick_2018, murphy_2019}.

Naturally, approximating the complexity of an urban regime into a single
number is fraught with potential missteps, but by deriving indices from
municipalities' spending priorities, this study has aimed to at least
begin to fill the existing gap in metrics for approximating urban regime
types. Future scholars are encouraged to use, adapt, and improve these
metrics, and I hope that spending-based metrics may be helpful for
approximating urban regime shift in other industrialized democracies,
like the US, Germany, South Korea, and Taiwan, among others.

\singlespacing

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item[1] SW = Social Welfare. MC = Middle Class. D = Developental. C = Caretaker.
\item[2] Numbers rank city-year as a percentile (0-100) compared to all other city-years.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{2.5cm}>{\raggedright\arraybackslash}p{1.7cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedright\arraybackslash}p{1.7cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}}
\caption{\label{tab:keycities}Table \ref{tab:keycities}: \label{tab:keycities}{Regime Change in Past Case Studies}}\\
\toprule
\multicolumn{3}{c}{ } & \multicolumn{4}{c}{Regime in 2000} & \multicolumn{4}{c}{Regime in 2018} \\
\cmidrule(l{3pt}r{3pt}){4-7} \cmidrule(l{3pt}r{3pt}){8-11}
Prefecture & Municipality & Literature & Type & SW & MC & D & Type  & SW  & MC  & D \\
\midrule
\cellcolor{gray!6}{Tokyo} & \cellcolor{gray!6}{Mitaka} & \cellcolor{gray!6}{Steiner 1957; Fukushima \& Yamaguchi 1997; Ohashi \& Phelps 2021} & \cellcolor{gray!6}{C} & \cellcolor{gray!6}{25} & \cellcolor{gray!6}{26} & \cellcolor{gray!6}{2} & \cellcolor{gray!6}{C} & \cellcolor{gray!6}{51} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{2}\\
\addlinespace
Fukushima & Fukushima & Otsuki et al. 2016; Abeysinghe et al. 2022 & D & 8 & 27 & 53 & C & 44 & 36 & 35\\
\addlinespace
\cellcolor{gray!6}{Miyagi} & \cellcolor{gray!6}{Sendai} & \cellcolor{gray!6}{Morris 2012; Tsuji 2017} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{14} & \cellcolor{gray!6}{68} & \cellcolor{gray!6}{48} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{48} & \cellcolor{gray!6}{58} & \cellcolor{gray!6}{33}\\
\addlinespace
Miyagi & Ishinomaki & Dimmer \& Lindenberg 2014; Matthews 2017; Ji \& Imai 2022 & MC & 4 & 53 & 22 & SW-MC-D & 85 & 81 & 87\\
\addlinespace
\cellcolor{gray!6}{Hyogo} & \cellcolor{gray!6}{Kobe} & \cellcolor{gray!6}{Nunokawa 2007; Funck 2007; Yasui 2007; Edgington 2010; Aldrich 2012; Maly et al. 2012} & \cellcolor{gray!6}{MC-D} & \cellcolor{gray!6}{42} & \cellcolor{gray!6}{74} & \cellcolor{gray!6}{65} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{68} & \cellcolor{gray!6}{49} & \cellcolor{gray!6}{11}\\
\addlinespace
Hokkaido & Muroran & Edgington 2013 & SW & 54 & 46 & 37 & SW-MC & 70 & 64 & 38\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\doublespacing

\hypertarget{a-diagnostic-resource-for-updating-case-studies}{%
\subsubsection{6.1.4 A Diagnostic Resource for Updating Case
Studies}\label{a-diagnostic-resource-for-updating-case-studies}}

Further, this study's measures also provide a resource for scholars
building new theories of urban politics. After a wealth of investigation
of urban politics in Japan over the last 30 years, some case studies may
no longer be representative of the current state of their municipality.
Until now, the field has lacked a tool for systematically identifying
\emph{which} municipalities need re-investigation.
\textbf{Table \ref{tab:keycities}} demonstrates an example of how
scholars can utilize these new indices to evaluate commonly cited case
studies whose urban regime type may have since changed.

\textbf{Table \ref{tab:keycities}} lists several notable municipalities,
selected for their relevance to the literature. For each municipality,
columns report (1) the citing literature, (2) this study's numeric and
categorical regime classifications for each municipality in 2000,
compared with (3) their classifications in 2018. Each municipality's
index scores are represented as relative percentiles (0-100\%), showing
\emph{how much} they lean towards that given regime.

On the one hand, these indices also point to the intractability of
regimes in some municipalities. For example, several municipalities have
retained their classification. Mitaka, an affluent suburb of Tokyo,
remains a caretaker regime
\citep{steiner_1957, fukuchi_and_yamaguchi_1997, ohashi_and_phelps_2021},
insulated from economic decline in other suburbs. Sendai, the
metropolitan hub of the Tohoku region, remains a middle-class,
progressive regime, with stable, continuity in leadership even after
substantial impacts of the 2011 triple disaster
\citep{morris_2012, tsuji_2017}. Finally, the rustbelt city of Muroran
\citep{edgington_2013} continues to focus strongly on social welfare
even after 20 years, albeit with some change towards a hybrid regime.

On the other hand, some municipalities have changed greatly, and may
merit renewed investigation from scholars. Fukushima City originally
ranked as a developmental regime, but has since transitioned to a
caretaker regime, as the city has had to balance competing interests
from national government, local families, weakened agriculture, and
decontamination efforts \citep{otsuki_2016, abeysinghe_2022}, each
aiming to stem out-migration through different means \citep{zhang_2014}.

Ishinomaki City, formerly a middle-class regime, has become a hybrid
regime, adding considerable spending relative to its peers on social
welfare and economic development to attempt to recover after the tsunami
devastated its local industry, agriculture, and tourism businesses
\citep{dimmer_and_lindenberg_2014, matthews_2017, ji_and_imai_2022}.
Such findings raise questions for other Tohoku municipalities
investigated after the disaster \citep{aldrich_2019, cheek_2020}.

Similarly, Kobe transitioned from a 2000-era focus on middle-class
interests and economic development \citep{nunokawa_2007, funck_2007} to
a new focus on social welfare and middle-class interests; much has
written about Kobe's less-than-ideal recovery policies from the 1994
disaster, where developers gentrified many low-income neighborhoods and
displaced families from housing
\citep{yasui_2007, edgington_2010, aldrich_2012, maly_2012}. This shift
away from developmental-approaches raises exciting questions about what
has changed in Kobe since their early-recovery period. The author hopes
that this table might provide a spotlight for municipalities in need of
further study.

\hypertarget{limitations}{%
\subsection{6.2 Limitations}\label{limitations}}

Finally, this study does come with several limitations, in additions to
the index discussions in our Data section. In addition to the
aforementioned challenges of approximating urban regime shifts using
spending as a proxy measure, some scholarship has highlighted cases
where urban regimes are more difficult to characterize
\citep{deleon_1992, shin_et_al_2015, davies_and_blanco_2017, russo_and_scarnato_2018}.
Depending on the country, urban governance and levels of local autonomy
may vary due to institutional differences, laws, and tax structure
\citep{sellers_2002, sorensen_2011}. Some municipalities lack stable
governing coalitions, dubbed `non-regimes' \citep{mossberger_2009}. In
practice, these either would not spend consistently on the same
priorities, or would spend little on any new priorities, resembling a
caretaker regime.

Another important factor that might influence spending spendings, but
was not explored in this study, is women's representation in public
office (eg. city council). This study did not explore this variable due
to data collection challenges; municipal electoral data is quite
difficult to collect for multi-decade duration of the study period, and
the full range of municipalities. Recent studies have tried to resolve
this gap; a recent study examined municipal level gender representation
in 764 cities from 2007 to 2012 \citep{suzuki_and_avellaneda_2018};
future studies could attempt to expand this to our full range of over
1700 municipalities from 2000 to 2018. Also, gender representation can
be endogenously related to collective action potential, in that
communities with greater collective action potential might be more
likely to overturn male incumbents and vote in greater shares of women
in public office, reshaping spending patterns. Future scholars are
strongly encouraged to investigate the independent effects of women's
representation in politics on urban regime type.

Neighborhood organizations, nonprofits, and labor movements can also
motivate and structure these municipalities' regimes
\citep{logan_and_rabrenovic_1990, nissen_1995, takao_2006, camou_2014, stone_et_al_2015}
as can higher levels of government
\citep{sellers_2002, tsukamoto_2012, shin_et_al_2015}. These limitations
aside, urban regimes, even amidst varying governance conditions, remain
a useful way to characterize that development remains so prioritized in
some municipalities, while opportunity-expanding policies remain
prioritized in others \citep{funck_2007, ji_and_imai_2022}. This study's
measurement using developmental, opportunist, and progressive regime
indices helps achieve that aim.

\singlespacing

\newpage

\hypertarget{appendix}{%
\section*{Appendix}\label{appendix}}
\addcontentsline{toc}{section}{Appendix}

\large
\doublespacing

\textbf{Table of Contents}

\large

\begin{itemize}
\item
  Figure \ref{fig:figure_A1}: Distributions of Urban Regime Indices
\item
  Table \ref{tab:tablea1}: Descriptive Statistics
\item
  Table \ref{tab:tablea2}: OLS Models 1-8 (Outcome: Social Welfare
  Regime Index)
\item
  Table \ref{tab:tablea3}: OLS Models 9-16 (Outcome: Developmental
  Regime Index)
\item
  Table \ref{tab:tablea4}: OLS Models 17-24 (Outcome: Middle-Class
  Regime Index)
\end{itemize}

\singlespacing

\newpage

\begin{landscape}

\setcounter{table}{0}
\renewcommand{\thetable}{A\arabic{table}}
\setcounter{figure}{0}
\renewcommand{\thefigure}{A\arabic{figure}}

\begin{figure}
\includegraphics[width=1\linewidth]{../viz/distribution} \caption{Figure \ref{fig:figure_A1}: \label{fig:figure_A1}{Distributions of Urban Regime Indices}}\label{fig:figure_A1}
\end{figure}

\end{landscape}

\newpage
\begin{landscape}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Categorical Variables include Year$^{a}$, Prefecture$^{b}$, and Tsunami$^{c}$. Models use multiple imputation with 5 imputations to account for missing data.
\item[a] Years range from 2000 (n = 1428 cities) to 2018 (n = 1727). Mode is 2010 (n = 1732). In models, baseline year is 2000. Some municipalities consolidated over time, while others split. Dataset omits outliers including Fukushima Exclusion Zone cities from 2011-2018 and Yubari 2000-2018.
\item[b] 47 Prefectures. Modal prefecture is Hokkaido, with 178 cities (10\%, n = 1,738) and 3,327 city-years (10\%, n = 31,493). In models, the baseline prefecture is Hokkaido.
\item[c] Tsunami hit 85 municipalities in 2011; cities labeled 2011-2018 as tsunami-affected (n = 680).
\item[1] Spending measured in 1,000s of yen.
\item[2] Disaster deaths and damages (\# of buildings damaged) measured per 100,000 persons.
\item[3] Zeros from unaffected cities in disaster variable distributions omitted to show nonzero values clearly.
\end{TableNotes}
\begin{longtable}[t]{>{\raggedright\arraybackslash}p{4cm}lllllrr>{}l>{}ll}
\caption{\label{tab:tablea1}\textbf{Table \ref{tab:tablea1}: \label{tab:tablea1}{Descriptive Statistics}} \newline \normalsize 40043 Japanese city-years (2000-2018)}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{5}{c}{Statistics} & \multicolumn{2}{c}{Observations} \\
\cmidrule(l{3pt}r{3pt}){2-6} \cmidrule(l{3pt}r{3pt}){7-8}
Variable & Mean & SD & Min & Median & Max & N & \% Missing & Distribution$^{3}$ & Transformed$^{3}$ & Transformation\\
\midrule
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Urban Regime Indices}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Regime} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.63} & \cellcolor{gray!6}{-2.04} & \cellcolor{gray!6}{-0.05} & \cellcolor{gray!6}{3.05} & \cellcolor{gray!6}{40029} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45441c3d42bf.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45444d874f73.pdf} & \cellcolor{gray!6}{x}\\
\hspace{1em}Middle Class Regime & 0 & 0.53 & -2.07 & -0.09 & 3.06 & 40029 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544708f3de1.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45443aa97947.pdf} & x\\
\hspace{1em}\cellcolor{gray!6}{Developmental Regime} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.85} & \cellcolor{gray!6}{-2.11} & \cellcolor{gray!6}{-0.05} & \cellcolor{gray!6}{2.84} & \cellcolor{gray!6}{40029} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45446da97991.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45442b1f22a9.pdf} & \cellcolor{gray!6}{x}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}Population & 60866 & 169234 & 178 & 17299 & 3724844 & 40043 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454450d4127b.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45447adc27ba.pdf} & x$^{1/10}$\\
\hspace{1em}\cellcolor{gray!6}{Inhabitable Area (ha)} & \cellcolor{gray!6}{5736.24} & \cellcolor{gray!6}{6716.1} & \cellcolor{gray!6}{74} & \cellcolor{gray!6}{3402} & \cellcolor{gray!6}{80524} & \cellcolor{gray!6}{40043} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45446fd0757b.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454466384ccc.pdf} & \cellcolor{gray!6}{log(x)}\\
\hspace{1em}\% Over Age 65 & 0.28 & 0.08 & 0.08 & 0.28 & 0.6 & 40043 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45444175220d.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45444eda4216.pdf} & logit(x)\\
\hspace{1em}\cellcolor{gray!6}{Income per capita$^{1}$} & \cellcolor{gray!6}{1207.26} & \cellcolor{gray!6}{338.49} & \cellcolor{gray!6}{263.9} & \cellcolor{gray!6}{1174.82} & \cellcolor{gray!6}{9058.48} & \cellcolor{gray!6}{39773} & \cellcolor{gray!6}{0.7} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544599b7105.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454447dcfab.pdf} & \cellcolor{gray!6}{log(x)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}Revenue per capita$^{1}$ & 696.22 & 570.52 & 120.52 & 521.21 & 14123.27 & 40029 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45445c383380.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45442d2a7dad.pdf} & sqrt(x)\\
\hspace{1em}\cellcolor{gray!6}{\% National \& Prefectural Funding} & \cellcolor{gray!6}{0.16} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.15} & \cellcolor{gray!6}{0.84} & \cellcolor{gray!6}{40029} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45442bc83e1a.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45444a2b4cbd.pdf} & \cellcolor{gray!6}{logit(x)}\\
\hspace{1em}Real Term Budget Balance (+/-) & 5.38 & 4.45 & -50.7 & 4.7 & 113.4 & 40029 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454456f23461.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454453a452b7.pdf} & x\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Deaths$^{2}$} & \cellcolor{gray!6}{11.32} & \cellcolor{gray!6}{238.48} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{9077.99} & \cellcolor{gray!6}{40043} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544968288a.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454438d94f9c.pdf} & \cellcolor{gray!6}{x$^{1/10}$}\\
\hspace{1em}Disaster Damage$^{2}$ & 187.91 & 1328.48 & 0 & 0 & 23774.73 & 40043 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454440f6363.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544ff5ed0.pdf} & x$^{1/10}$\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate$^{1}$} & \cellcolor{gray!6}{8.74} & \cellcolor{gray!6}{44.65} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.44} & \cellcolor{gray!6}{3388.75} & \cellcolor{gray!6}{40029} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454460606889.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454421ab2886.pdf} & \cellcolor{gray!6}{x$^{1/10}$}\\
\hspace{1em}Disaster Relief Spending Rate$^{1}$ & 1.89 & 33.04 & 0 & 0 & 1910.01 & 40029 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544230eadb.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544581e7778.pdf} & x$^{1/10}$\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Prefecture} & \cellcolor{gray!6}{0.31} & \cellcolor{gray!6}{0.26} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.31} & \cellcolor{gray!6}{0.97} & \cellcolor{gray!6}{34964} & \cellcolor{gray!6}{12.7} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454461e8252e.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454414fe16db.pdf} & \cellcolor{gray!6}{logit(x + 0.01)}\\
\hspace{1em}Bonding Social Capital & 0.7 & 0.05 & 0.39 & 0.71 & 0.81 & 35011 & 12.6 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45441024b43.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454432f47c92.pdf} & logit(x)\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bridging Social Capital} & \cellcolor{gray!6}{0.32} & \cellcolor{gray!6}{0.08} & \cellcolor{gray!6}{0.09} & \cellcolor{gray!6}{0.32} & \cellcolor{gray!6}{0.57} & \cellcolor{gray!6}{35011} & \cellcolor{gray!6}{12.6} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45444b0f6f6.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454436413a2.pdf} & \cellcolor{gray!6}{quartiles(x)}\\
\hspace{1em}Linking Social Capital & 0.26 & 0.08 & 0.06 & 0.25 & 0.55 & 35011 & 12.6 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544691275b7.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454470a27ae6.pdf} & logit(x)\\
\hspace{1em}\cellcolor{gray!6}{\% Some College} & \cellcolor{gray!6}{0.24} & \cellcolor{gray!6}{0.08} & \cellcolor{gray!6}{0.05} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{0.88} & \cellcolor{gray!6}{39961} & \cellcolor{gray!6}{0.2} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45447d365a3e.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45441c76c04.pdf} & \cellcolor{gray!6}{logit(x)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% Unemployed & 0.05 & 0.02 & 0 & 0.04 & 0.23 & 40043 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_454464f9767b.pdf} & \includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45443322e9f.pdf} & logit(x)\\
\hspace{1em}\cellcolor{gray!6}{Total Migration per capita} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.04} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.06} & \cellcolor{gray!6}{0.62} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{21.4} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_4544669041cc.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{C:/Users/tmf77/OneDrive - Cornell University/Documents/rstudio/urban_regimes/revision/revision_files/figure-latex/hist_45442b51bce.pdf} & \cellcolor{gray!6}{log(x)}\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\newpage

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 5. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 6-8, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 7-8 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 8, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 7 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{Table \ref{tab:tablea2}: \label{tab:tablea2}{\textbf{OLS Models of Social Welfare Regimes.}} \newline \normalsize 
        \textit{Dependent Variable}: Social Welfare Regime Index (Z-score). 
        \newline \normalsize 
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 1} & \multicolumn{1}{c}{Model 2} & \multicolumn{1}{c}{Model 3} & \multicolumn{1}{c}{Model 4} & \multicolumn{1}{c}{Model 5} & \multicolumn{1}{c}{Model 6} & \multicolumn{1}{c}{Model 7} & \multicolumn{1}{c}{Model 8} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.04*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & 0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & -0.00    (0.00) & 0.00    (0.00) & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{3.40*** (0.04)}} & \textbf{\cellcolor{gray!6}{3.39*** (0.04)}} & \textbf{\cellcolor{gray!6}{2.41*** (0.04)}} & \textbf{\cellcolor{gray!6}{2.38*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.87*** (0.05)}} & \textbf{\cellcolor{gray!6}{0.43*** (0.03)}} & \textbf{\cellcolor{gray!6}{0.47*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.01)}}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{0.00*   (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*   (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.09*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{0.42*** (0.03)} & \textbf{0.72*** (0.04)} & \textbf{0.90*** (0.03)} & \textbf{0.78*** (0.03)} & \textbf{0.41*** (0.04)} & \textbf{0.23*** (0.02)} & \textbf{0.06**  (0.02)} & 0.01.   (0.00)\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & 0.00.   (0.00) & \textbf{0.00*** (0.00)} & -0.00.   (0.00) & \textbf{-0.00**  (0.00)} & \textbf{-0.00*** (0.00)} & 0.00    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.01*   (0.00)}}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & 0.01    (0.01) & 0.00    (0.01) & -0.01    (0.01) & \textbf{0.11*** (0.01)} & \textbf{0.03**  (0.01)} & \textbf{0.03**  (0.01)} & \textbf{0.02*   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.01*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Middle Class Regime Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.16*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.15*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.12*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.04*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.02*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}Developmental Regime Index &  &  & \textbf{0.23*** (0.00)} & \textbf{0.20*** (0.00)} & \textbf{0.23*** (0.00)} & \textbf{0.07*** (0.00)} & \textbf{0.02*** (0.00)} & -0.00    (0.00)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.03*   (0.01)}} & \cellcolor{gray!6}{0.03.   (0.01)} & \cellcolor{gray!6}{0.01    (0.01)} & \cellcolor{gray!6}{0.00    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & 0.01.   (0.01) & \textbf{0.04*** (0.01)} & \textbf{0.02*** (0.00)} & \textbf{0.02*** (0.00)} & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.77*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.97*** (0.08)}} & \textbf{\cellcolor{gray!6}{-0.28*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.32*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{0.02*** (0.00)} & \textbf{0.04*** (0.00)} & \textbf{0.01**  (0.00)} & \textbf{0.01*** (0.00)} & \textbf{0.01**  (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.29*** (0.03)}} & \cellcolor{gray!6}{-0.05    (0.06)} & \textbf{\cellcolor{gray!6}{-0.14*** (0.04)}} & \textbf{\cellcolor{gray!6}{-0.10**  (0.04)}} & \cellcolor{gray!6}{-0.01.   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{-0.67*** (0.03)} & \textbf{-0.38*** (0.04)} & 0.01    (0.02) & \textbf{-0.13*** (0.03)} & -0.01    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{2.03*** (0.14)}} & \textbf{\cellcolor{gray!6}{0.66*** (0.09)}} & \textbf{\cellcolor{gray!6}{-0.45*** (0.10)}} & \textbf{\cellcolor{gray!6}{-0.04*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{1.29*** (0.07)} & \textbf{0.44*** (0.07)} & 0.08.   (0.04) & \textbf{0.13**  (0.05)} & 0.00    (0.00)\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.73*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.79*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.78*** (0.00)}}\\
\hspace{1em}Constant & \textbf{-1.47*** (0.02)} & \textbf{-1.54*** (0.02)} & \textbf{-1.21*** (0.02)} & \textbf{-0.81*** (0.04)} & \textbf{-0.37*** (0.07)} & -0.09.   (0.05) & \textbf{0.12*   (0.05)} & \textbf{0.52*** (0.07)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 4.36 & 5.16 & 8.12 & 8.16 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \textbf{\cellcolor{gray!6}{3011.7***    (25)}} & \textbf{\cellcolor{gray!6}{2619.8***    (30)}} & \textbf{\cellcolor{gray!6}{3182.5***    (32)}} & \textbf{\cellcolor{gray!6}{2769.3***    (39)}} & \textbf{\cellcolor{gray!6}{1590.6***    (86)}} & \textbf{\cellcolor{gray!6}{4105.5***    (86)}} & \textbf{\cellcolor{gray!6}{3803.8***    (86)}} & \textbf{\cellcolor{gray!6}{3834.3***    (86)}}\\
\hspace{1em}Change in Deviance (df) & - & \textbf{-113.1***     (5)} & \textbf{-636.5***     (2)} & \textbf{-133.4***     (7)} & \textbf{-495.4***    (47)} & \textbf{-1298.9***     (1)} & \textbf{-1410.5***     (1)} & \textbf{-38.5***    (17)}\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.35} & \cellcolor{gray!6}{0.34} & \cellcolor{gray!6}{0.31} & \cellcolor{gray!6}{0.30} & \cellcolor{gray!6}{0.28} & \cellcolor{gray!6}{0.18} & \cellcolor{gray!6}{0.18} & \cellcolor{gray!6}{0.18}\\
\hspace{1em}R$^{2}$ & 0.71 & 0.71 & 0.76 & 0.77 & 0.81 & 0.92 & 0.92 & 0.92\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\newpage
\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 13. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 14-16, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 15-16 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 16, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 15 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{Table \ref{tab:tablea3}: \label{tab:tablea3}{\textbf{OLS Models of Developmental Regimes.}} \newline \normalsize 
        \textit{Dependent Variable}: Developmental Regime Index (Z-score). 
        \newline \normalsize 
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 9} & \multicolumn{1}{c}{Model 10} & \multicolumn{1}{c}{Model 11} & \multicolumn{1}{c}{Model 12} & \multicolumn{1}{c}{Model 13} & \multicolumn{1}{c}{Model 14} & \multicolumn{1}{c}{Model 15} & \multicolumn{1}{c}{Model 16} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.12*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.05*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{3.38*** (0.05)}} & \textbf{\cellcolor{gray!6}{3.32*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.66*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.88*** (0.06)}} & \textbf{\cellcolor{gray!6}{2.02*** (0.06)}} & \textbf{\cellcolor{gray!6}{0.46*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.48*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.01)}}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.12*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{-0.91*** (0.05)} & \textbf{-0.41*** (0.05)} & \textbf{-0.51*** (0.04)} & 0.04    (0.04) & \textbf{0.23*** (0.04)} & \textbf{0.52*** (0.03)} & \textbf{-0.41*** (0.03)} & \textbf{-0.04*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{0.05*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00**  (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & \textbf{0.05*   (0.02)} & \textbf{0.05**  (0.02)} & \textbf{0.11*** (0.02)} & \textbf{0.05**  (0.02)} & -0.00    (0.01) & \textbf{0.03*   (0.01)} & 0.00    (0.01)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.01*   (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.38*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.31*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.33*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.11*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.05*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.02*** (0.00)}}\\
\hspace{1em}Middle Class Regime Index &  &  & \textbf{0.31*** (0.01)} & \textbf{0.27*** (0.01)} & \textbf{0.25*** (0.01)} & \textbf{0.11*** (0.00)} & \textbf{-0.01*   (0.00)} & \textbf{-0.02*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0.01    (0.01)} & \cellcolor{gray!6}{-0.00    (0.02)} & \cellcolor{gray!6}{-0.00    (0.01)} & \cellcolor{gray!6}{0.02    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & -0.01    (0.01) & \textbf{0.02*   (0.01)} & -0.00    (0.01) & 0.01    (0.01) & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.55*** (0.06)}} & \textbf{\cellcolor{gray!6}{-0.21*   (0.09)}} & \textbf{\cellcolor{gray!6}{-0.13*   (0.06)}} & \textbf{\cellcolor{gray!6}{-0.16*   (0.07)}} & \textbf{\cellcolor{gray!6}{-0.04**  (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{0.07*** (0.00)} & \textbf{0.05*** (0.00)} & 0.01.   (0.00) & \textbf{0.02*** (0.00)} & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.18*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.24*** (0.07)}} & \cellcolor{gray!6}{0.04    (0.04)} & \cellcolor{gray!6}{0.05    (0.05)} & \cellcolor{gray!6}{0.01.   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{-1.70*** (0.04)} & \textbf{-1.34*** (0.04)} & \textbf{-0.23*** (0.03)} & \textbf{-0.23*** (0.03)} & \textbf{-0.01*   (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-5.60*** (0.15)}} & \textbf{\cellcolor{gray!6}{-6.55*** (0.17)}} & \textbf{\cellcolor{gray!6}{-1.65*** (0.11)}} & \textbf{\cellcolor{gray!6}{-1.92*** (0.12)}} & \textbf{\cellcolor{gray!6}{-0.09*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{0.42*** (0.08)} & \textbf{0.19*   (0.08)} & -0.07    (0.05) & \textbf{0.31*** (0.06)} & \textbf{0.04*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.72*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.81*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.77*** (0.00)}}\\
\hspace{1em}Constant & \textbf{-0.68*** (0.03)} & \textbf{-0.82*** (0.02)} & 0.02    (0.02) & \textbf{-0.26*** (0.06)} & 0.05    (0.09) & 0.03    (0.06) & \textbf{0.13*   (0.06)} & \textbf{0.31*** (0.08)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 3.86 & 4.92 & 8.12 & 8.17 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \textbf{\cellcolor{gray!6}{3146.4***    (25)}} & \textbf{\cellcolor{gray!6}{2893.6***    (30)}} & \textbf{\cellcolor{gray!6}{3718.3***    (32)}} & \textbf{\cellcolor{gray!6}{3720.6***    (40)}} & \textbf{\cellcolor{gray!6}{2128.6***    (86)}} & \textbf{\cellcolor{gray!6}{5488***              (86)}} & \textbf{\cellcolor{gray!6}{4723.9***    (86)}} & \textbf{\cellcolor{gray!6}{4808.6***    (86)}}\\
\hspace{1em}Change in Deviance (df) & - & \textbf{-458.6***     (5)} & \textbf{-1323.9***     (2)} & \textbf{-805.5***     (8)} & \textbf{-651.8***    (46)} & \textbf{-1923***              (1)} & \textbf{-2127***              (1)} & \textbf{-99.4***    (17)}\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.46} & \cellcolor{gray!6}{0.44} & \cellcolor{gray!6}{0.39} & \cellcolor{gray!6}{0.36} & \cellcolor{gray!6}{0.33} & \cellcolor{gray!6}{0.21} & \cellcolor{gray!6}{0.22} & \cellcolor{gray!6}{0.22}\\
\hspace{1em}R$^{2}$ & 0.71 & 0.73 & 0.79 & 0.83 & 0.85 & 0.94 & 0.93 & 0.93\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\newpage

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 21. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 22-24, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 23-24 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 24, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 23 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{Table \ref{tab:tablea4}: \label{tab:tablea4}{\textbf{OLS Models of Middle Class Regimes.}} \newline \normalsize 
        \textit{Dependent Variable}: Middle Class Regime Index (Z-score). 
        \newline \normalsize 
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 17} & \multicolumn{1}{c}{Model 18} & \multicolumn{1}{c}{Model 19} & \multicolumn{1}{c}{Model 20} & \multicolumn{1}{c}{Model 21} & \multicolumn{1}{c}{Model 22} & \multicolumn{1}{c}{Model 23} & \multicolumn{1}{c}{Model 24} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & 0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.03*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{1.26*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.24*** (0.04)}} & \textbf{\cellcolor{gray!6}{-0.44*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.44*** (0.06)}} & \cellcolor{gray!6}{0.11    (0.07)} & \textbf{\cellcolor{gray!6}{-0.15*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.14**  (0.04)}} & \cellcolor{gray!6}{0.00    (0.01)}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & -0.00.   (0.00) & \textbf{-0.04*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{-0.86*** (0.04)} & \textbf{-0.53*** (0.04)} & \textbf{-0.59*** (0.04)} & \textbf{-0.63*** (0.04)} & \textbf{-0.58*** (0.05)} & \textbf{0.07*   (0.03)} & \textbf{-0.27*** (0.03)} & \textbf{-0.04*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*   (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00    (0.00) & -0.00.   (0.00) & 0.00    (0.00) & 0.00    (0.00) & \textbf{0.03**  (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{-0.00.   (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \cellcolor{gray!6}{-0.00    (0.00)}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & -0.01    (0.02) & -0.03.   (0.02) & \textbf{-0.03*   (0.02)} & -0.02    (0.02) & -0.02.   (0.01) & 0.01    (0.01) & 0.00    (0.01)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00.   (0.00) & -0.00    (0.00) & 0.00    (0.00) & \textbf{0.00**  (0.00)} & 0.01.   (0.00)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.23*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.23*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.19*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.04*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.03*** (0.00)}}\\
\hspace{1em}Developmental Regime Index &  &  & \textbf{0.27*** (0.01)} & \textbf{0.27*** (0.01)} & \textbf{0.28*** (0.01)} & \textbf{0.11*** (0.00)} & 0.00    (0.00) & \textbf{-0.02*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0.03.   (0.02)} & \cellcolor{gray!6}{0.02    (0.02)} & \cellcolor{gray!6}{0.00    (0.01)} & \cellcolor{gray!6}{-0.00    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & \textbf{-0.02*   (0.01)} & -0.01    (0.01) & -0.00    (0.01) & 0.01    (0.01) & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.53*** (0.07)}} & \textbf{\cellcolor{gray!6}{0.25**  (0.10)}} & \cellcolor{gray!6}{0.04    (0.06)} & \cellcolor{gray!6}{-0.11    (0.07)} & \textbf{\cellcolor{gray!6}{-0.03*   (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{-0.01*** (0.00)} & \textbf{0.02*** (0.00)} & 0.00    (0.00) & \textbf{0.02*** (0.00)} & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.15*** (0.04)}} & \cellcolor{gray!6}{0.10    (0.07)} & \cellcolor{gray!6}{-0.00    (0.05)} & \cellcolor{gray!6}{-0.01    (0.05)} & \cellcolor{gray!6}{0.00    (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{0.25*** (0.04)} & 0.09.   (0.05) & \textbf{0.16*** (0.03)} & \textbf{-0.08*   (0.03)} & 0.00    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-1.50*** (0.16)}} & \textbf{\cellcolor{gray!6}{-1.27*** (0.18)}} & \cellcolor{gray!6}{-0.01    (0.12)} & \textbf{\cellcolor{gray!6}{-1.18*** (0.12)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{1.02*** (0.08)} & \textbf{1.33*** (0.08)} & \textbf{0.21*** (0.06)} & \textbf{0.33*** (0.06)} & \textbf{0.02*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.75*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.80*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.80*** (0.00)}}\\
\hspace{1em}Constant & \textbf{-0.74*** (0.02)} & \textbf{-0.82*** (0.02)} & \textbf{-0.24*** (0.02)} & \textbf{0.19**  (0.07)} & \textbf{-0.45*** (0.09)} & -0.09    (0.06) & \textbf{0.13*   (0.06)} & -0.01    (0.08)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 4.38 & 5.32 & 8.12 & 8.16 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \textbf{\cellcolor{gray!6}{1039.7***    (25)}} & \textbf{\cellcolor{gray!6}{921.8***    (30)}} & \textbf{\cellcolor{gray!6}{1242***              (32)}} & \textbf{\cellcolor{gray!6}{1016.3***    (40)}} & \textbf{\cellcolor{gray!6}{552***              (86)}} & \textbf{\cellcolor{gray!6}{1872.4***    (86)}} & \textbf{\cellcolor{gray!6}{1715.6***    (86)}} & \textbf{\cellcolor{gray!6}{1727.8***    (86)}}\\
\hspace{1em}Change in Deviance (df) & - & \textbf{-148***              (5)} & \textbf{-867.7***     (2)} & \textbf{-54***              (8)} & \textbf{-365.3***    (46)} & \textbf{-2177.3***     (1)} & \textbf{-2337***              (1)} & \textbf{-29.7***    (17)}\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.41} & \cellcolor{gray!6}{0.40} & \cellcolor{gray!6}{0.37} & \cellcolor{gray!6}{0.36} & \cellcolor{gray!6}{0.35} & \cellcolor{gray!6}{0.22} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{0.23}\\
\hspace{1em}R$^{2}$ & 0.45 & 0.47 & 0.56 & 0.56 & 0.60 & 0.84 & 0.83 & 0.83\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}
\end{landscape}

\newpage

\renewcommand\refname{References}
\bibliography{mybibfile.bib}


\end{document}
