\documentclass[preprint, 3p,
authoryear]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%

\usepackage[hyphens]{url}

  \journal{Journal} % Sets Journal name

\usepackage{lineno} % add
  \linenumbers % turns line numbering on

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
    \setmainfont{Times New Roman}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\usepackage[]{natbib}
\bibliographystyle{plainnat}

\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Big Spenders: Large-N Measures of Urban Regimes},
            colorlinks=true,
            urlcolor=blue,
            linkcolor=blue,
            pdfborder={0 0 0}}

\setcounter{secnumdepth}{0}
% Pandoc toggle for numbering sections (defaults to be off)
\setcounter{secnumdepth}{0}


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


% Pandoc citation processing
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage{caption}
\usepackage{setspace}\doublespacing
\usepackage{lscape}
\newcommand{\blandscape}{\begin{landscape}}
\newcommand{\elandscape}{\end{landscape}}
\usepackage{colortbl}
\usepackage{xcolor}
\usepackage{makecell}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}



\begin{document}


\begin{frontmatter}

  \title{Big Spenders: Large-N Measures of Urban Regimes}
    \author[Department of Political Science, Northeastern
University]{Timothy Fraser%
  \corref{cor1}%
  \fnref{1}}
   \ead{timothy.fraser.1@gmail.com} 
      \affiliation[PhD Candidate, Political Science, Northeastern
University]{Department of Political Science, Northeastern University}
    \cortext[cor1]{Corresponding author}
    \fntext[1]{This is the first author footnote.}
  
  \begin{abstract}
  This is the abstract. It consists of two paragraphs.
  \end{abstract}
    \begin{keyword}
    urban regime \sep cities \sep policy \sep social welfare \sep social
capital \sep 
    Japan
  \end{keyword}
  
 \end{frontmatter}

\captionsetup[table]{labelformat=empty}
\captionsetup[figure]{labelformat=empty}
\captionsetup{font=large}

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Who governs? As cities face increasing threats from climate change and
climatic hazards, the coalitions and interests of power brokers who
govern our cities are likely changing. Since Dahl's
\citeyearpar{dahl_1961} case study of New Haven's mayor posed the famous
question, ``Who Governs?'', scholars have puzzled over the governance of
cities: Much attention has been paid to different types of coalitions
\citep{munoz_and_henry_1986, stone_1989, stoker_and_mossberger_1994, gilliam_1996, davies_2017, russo_and_scarnato_2018},
mayors
\citep{ramirez_perez_et_al_2008, debenedictis_kessner_and_warshaw_2016, freier_and_thomasius_2016, einstein_and_glick_2018},
and interest groups
\citep{logan_and_rabrenovic_1990, mossberger_and_stoker_2001, cooper_et_al_2005, portney_and_berry_2016, anzia_2019}
that govern city politics. Urban regime scholars argue that the
powerbrokers together constitute an ``urban regime'' \citep{stone_1993},
coined in Clarence Stone's \citeyearpar{stone_1989} study of Atlanta
politics. ``Urban regime'' refers to elected officials and unelected
powerbrokers alike, such as influential firms, NGOs, or citizens groups,
who determine what policy actions a city can and cannot take
\citep{mossberger_and_stoker_2001}. As cities experience more disasters,
migration, and social change in the face of storms, floods, fires,
hurricanes, and other disasters, we would naturally expect these urban
regimes to change. But to date, these changes have been difficult to
detect systematically, with most work on urban regimes focusing on
single city case studies; to date, the largest samples of cities
systematically classified by urban regime has been De Socio's
\citeyearpar{de_socio_2007} 24-city sample and Kilburn's
\citeyearpar{kilburn_2004} 14-city sample, using Stone's
\citeyearpar{stone_1993} 4 regime type classification.

This study aims to fill that gap, introducing a framework for measuring
city's propensity towards each of 4 common urban regime types, and
evaluating the change in frequencies of urban regimes over time. I
employ Stone's \citeyearpar{stone_1993} 4-regime classification, which
includes (1) caretaker, (2) developmental, (3) middle-class, and (4)
social welfare regimes, discussed in the literature review.

These categories raise natural questions in the face of climate change:
In the face of crisis, have social welfare regimes become more common,
compared to regimes prioritizing business or middle-class interests? Or,
have city politics stagnated with a rise in caretaker regimes that
simply maintain the status quo? To answer these questions, I apply this
framework to a Large-N sample of 1741 Japanese municipalities over 20
years from 2000 to 2020. The Japan Statistical Bureau reports
considerable annual data for each municipality, allowing scholars to
approximate the basic contours of cities' urban regimes by a simple,
publicly available proxy of each cities' governance priorities:
\emph{spending rates.} While spending cannot tell us specific actors
that govern, it can broadly approximate which of Stone's
\citeyearpar{stone_1993} 4 types of regimes are driving city policy.
Generally speaking, a true developmental regime would spend more city
funs in support of business needs; similarly, a true social welfare
regime would spend more in support of social welfare needs. Not to
replace, but to aid qualitative investigations of urban regimes, this
study designs a method to make Large-N comparisons among thousands of
cities at a time. I posit that we can detect measurable differences
among cities in terms of their spending rates.

As a preview of my results, I find that even after accounting for
population and inflation, city spending rates vary substantially over
time, with certain urban regimes' spending priorities becoming more
common with each passing year while others become less common. In
particular, I document the 20-year rise of the social welfare regime as
the most common type of urban regime, growing from just XX\% of cities
in 2000 to YY\% of cities in 2020. I also detect geographic patterns,
with coastal areas investing more heavily in social welfare regime
priorities over time. These are exciting and heartening findings,
because they indicate that while national-level governance on climate
has made progress with starts and stops, our cities are not unilaterally
gridlocked, stuck in caretaker, status quo regimes. Instead, many cities
are transitioning to social welfare regimes, increasing their spending
on social welfare issues like food security, housing, and disaster
recovery above the median level nationwide.

\hypertarget{literature-review}{%
\section{Literature Review}\label{literature-review}}

\hypertarget{urban-regime-theory}{%
\subsection{Urban Regime Theory}\label{urban-regime-theory}}

Since Stone's \citeyearpar{stone_1989} examination of urban regimes in
Atlanta, dozens of case studies have detailed different urban regimes
and governance arrangements throughout the world
\citep{stoker_and_mossberger_1994, mossberger_and_stoker_2001, de_socio_2007, camou_2014, davies_and_blanco_2017, rosol_et_al_2017, russo_and_scarnato_2018}.
Over 30 years since the term's coining, urban regimes received praise
\citep{kilburn_2004, davies_and_imbroscio_2009} and criticism
\citep{sites_1997, davies_2003, imbroscio_2003, imbroscio_2004} for how
easily it can be applied to understand city politics.

Many regimes once thought to be long-standing have come undone and
changed quickly in recent years \citep{stone_2015, stone_et_al_2015},
making the field awash in related terms like ``urban governance''
\citep{pierre_2014, da_cruz_et_al_2019}, governance networks
\citep{gissendanner_2003, davidson_et_al_2019}, policy networks
\citep{bulkeley_and_betsill_2013, hawkins_et_al_2016, wukich_2022},
public-private partnerships
\citep{stoker_1998, davies_2017, guo_and_ho_2019}, and multi-tiered
political orders \citep{stone_2015, weaver_2022}, or a just, socially
equitable city \citep{campbell_1996, fainstein_2010}. Others extended
definitions of urban regimes, applying versions of it to social welfare
crisis in the face of mass displacement and other social crises
\citep{lambelet_2019}.

Nomenclature aside, these frameworks all generally aim to explain ``who
governs,'' but systematic categorizations of many cities at once have
been rarer, usually confined to small-to-medium-N analyses
\citep{sellers_2002, kilburn_2004, stone_et_al_2015, davies_and_blanco_2017}.
Below, I synthesize a basic typology of urban regimes for measurement
from the extended literature, and outline the argument for why it
matters `who governs' cities in the face of climate change.

\hypertarget{redistributive-politics}{%
\subsection{Redistributive Politics}\label{redistributive-politics}}

For the purposes of this study, urban regimes also are an effective,
local level tool for thinking about the broader class of politics that
climate resilience initiatives exemplify: redistributive policies, a
familiar, long-standing, and particularly pernicious policy challenge
for cities
\citep{meltzer_and_scott_1981, pierson_1994, hacker_2004, iversen_and_soskice_2006, mettler_2011, rueda_and_stemueller_2019}.
National, regional, and city governments each work with redistributive
policies, aiming to provide en masse specific public goods that are
particularly difficult for residents to obtain individually, especially
for vulnerable residents.

Previous literature dealt with electoral (Meltzer \& Richards; Iversen
\& Soskice 2006), institutional
\citep{pierson_1994, hacker_2004, mettler_2011}, or street-level
implementation \citep{lipsky_1980, hupe_and_hill_2007} explanations for
the success and continuity of redistributive policies. However, these
studies dealt less with the community resources available to cities,
like partnerships with businesses
\citep{stone_1989, mossberger_and_stoker_2001}, civil society advocacy
groups \citep{portney_and_berry_2016}, neighborhood associations
\citep{logan_and_rabrenovic_1990}, and local networks
\citep{aldrich_and_meyer_2015}. These often overlooked community
resources can play important roles in redistributing resources to
residents in need \citep{aldrich_and_kioyta_2017, klinenberg_2018}.

What kinds of redistributive policies, then, were past scholars writing
about? The classic example of redistributive policy is social welfare
support for low-income families and unemployment insurance
\citep{pierson_1994, hacker_2004}, to abate the health and economic
challenges of entrenched poverty
\citep{ahammer_packham_2020, berkowitz_and_basu_2021}. In addition to
these, governments have tackled many redistributive policy issues in the
past. These include, for example:

\begin{itemize}
\item
  Social security policies aimed to eliminate poverty among the elderly,
  by redistributing the resources of other age groups (Titmus 1965,
  Conde-Ruiz \& Profeta 2007).
\item
  Universal health care, or market solutions, both aim to eliminate loss
  of life and financial ruin due to medical expenses, by redistributing
  the costs of health care issues to the entire population
  \citep{mettler_2011}.
\item
  Public education sought to remedy lack of access of education and
  opportunity in working class families by publicly funding education
  through the taxbase \citep{mettler_2005}.
\item
  Highway systems
  \citep{congleton_and_bennett_1995, zhu_and_brown_2013},
  electrification \citep{baker_and_phillips_2019, breetz_et_al_2018},
  and public transportation \citep{hood_2006} seek to connect citizens
  and expand economic development, important to everyone, but are
  challenging for any one city or company to pay for
  \citep{boarnet_and_haughwout_2000}.
\end{itemize}

These redistributive programs frequently develop policy constituencies
if the group benefitting from them is sizable enough
\citep{meltzer_and_richard_1981, campbell_2012}; in some states, these
programs' continuation is conditional, becoming political currency for
pork-barrel politics \citep{fukui_and_fukai_1996, catalinac_et_al_2020},
while in others, they become permanent fixtures in national policy
\citep{pierson_1994}.

However, moving beyond these federal- or state-level examples, in fact,
cities have been tackling redistributive issues for generations
\citep{peterson_1981, saiz_1999, tonkiss_2020}. Cities use
redistributive policies to remedy unequal access to employment in
neighborhoods by funding public transit for all
\citep{frankena_1973, asensio_et_al_2003, glaeser_et_al_2009, fearnley_and_aarhaug_2019, wiesel_and_liu_2021}.
They may support local businesses that might struggle to secure
consistent customers by providing public venues or markets
\citep{tangires_1997}. Cities may use public funds to free up real
estate and housing available in various neighborhoods
\citep{detter_and_folster_2017}, or, in the shameful history of many
cities, cities can be complicit in redlining and illegally restricting
access to housing \citep{rothstein_2017}. Lately, cities' efforts at
improving health equity are especially visible, as cities conduct and
manage public health campaigns, like current city efforts to rollout
testing and vaccination during the COVID-19 pandemic
\citep{berkowitz_and_basu_2021}. Some national governments lean on
cities to provide services that legitimize their state
\citep{wallace_2013}. And in many countries, cities play a key role in
the disbursement and coordination of social welfare distribution
\citep{katz_and_allen_2001, weir_and_kind_2021}, and must secure the
necessary funding for these projects \citep{payson_2022}.

Climate resilience initiatives, on the other hand, are a new form of
redistributive policy. These initiatives extend critical benefits to
society, but often struggle to achieve electoral support because their
benefits are diffuse, except to the most vulnerable in society who need
them. However, not all types of urban regimes prioritize redistributive
policies like social welfare support; indeed, three out of the four
regime types discussed below specifically prioritize other needs. Social
welfare's relevance to climate resilience makes it especially important
to identify whether social welfare-oriented regimes are increasing or
declining.

\hypertarget{types-of-urban-regimes}{%
\subsection{Types of Urban Regimes}\label{types-of-urban-regimes}}

As discussed above, Clarence Stone \citeyearpar{stone_1993} and later
comparative studies \citep{kilburn_2004, de_socio_2007} primarily relied
on 4 main types of urban regimes, including (1) caretaker, (2)
developmental, (3) middle-class, and (4) social welfare regimes. Over 30
years, scholars have created numerous other types of urban regimes,
sometimes conflicting or concept stretching, as some have argued
\citep{mossberger_and_stoker_2001}; however, these original 4 regime
types are still arguably the main types at play today. I outline in
Table \ref{tab:regimelit} a basic typology.

\newpage
\begin{landscape}

\begin{table}

\caption{Table \ref{tab:regimelit}\label{tab:regimelit}: Typology of Urban Regimes}
\centering
\begin{tabu} to \linewidth {>{\raggedright\arraybackslash}p{2cm}>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X}
\toprule
Regime & Definition & Examples & Related & Japanese Examples\\
\midrule
Caretaker & maintains status quo, traditional municipal service provision & New Orleans (Whelan et al. 1994) & Maintenance/Status Quo (Stone 1989)
                 

                 Bystander (Portz 1990)
                 

\cellcolor{gray!6}{                 Austerity (Davies \& Blanco 2017)} & \cellcolor{gray!6}{-}\\
Developmental & promotes economic growth while preventing economic decline & Atlanta (Stone 1989) & Entrepreneurial Regimes (Euchner 1993)
                 

                 Public-Private Partnerships (Davies 2017)
                 

                 Player (Portz 1990)
                 

                 Castle Towns (Funabashi 2006; Hill \& Fujita 1993) & Tokyo (Saito 2003; Tsukamoto 2012; Sorensen et al. 2010)
    

    Kitakyushu (Yeum 2002)
    

    Minamata (Funabashi 2006)
    

    Kobe Post-1995 (Edgington 2010)\\
Middle-Class & promotes egalitarian policies in education, health, environment, and city planning & Santa Cruz (Gendron \& Domhoff 2018) & Progressive (Stone 1989)
                

                'Anti-Regime' (DeLeon 1992) & Mitaka (Takao 2006)
                           

                           Kyoto (Sugiyama \& Takeuchi 2008)
                           

\cellcolor{gray!6}{                           Iida (Fraser et al. 2020)}\\
Social Welfare & improves conditions for working class, expands social safety net & Early Toronto (Mahon 2007 & Opportunist (Stone 1989)
                 

                 Activist (Clark 2001)
                 

                 Stewardship Regimes (Nissen 1995) & Yokohama (Hayashi 2013)
                           
Mikura Ward, Kobe (Yasui 2007)\\
\bottomrule
\end{tabu}
\end{table}

\end{landscape}
\newpage

The first type is (1) \emph{caretaker regimes}. In these cities, the
incumbent regime seeks to maintain a city's status quo
\citep{turner_1992, whelan_et_al_1994}. The municipality provides basic
services, but avoids expanding. Past studies labeled the city of New
Orleans, pre-Katrina, as a good example. Other terms capture the same
approximate meaning, including maintenance regimes \citep{stone_1989} or
bystander regimes \citep{portz_1990}, which refer to regimes that played
no major role when industrial firms closed shop in the US rustbelt.
Relatedly, some cities have also organized under austerity regimes,
focused on cutting expenses, rather than expanding policies; this
subtype lies somewhere between caretaker regimes and developmental
regimes, as they usually cut expenditures on social welfare or
progressive causes, but not necessarily economic interests
\citep{davies_and_blanco_2017}. To the author's knowledge, few studies
have tracked caretaker regimes in Japan; this study aims to help remedy
that.

The second type is (2) \emph{developmental regimes.} These regimes
prioritize economic development and business interests, while preventing
economic decline
\citep{stone_1989, austrian_and_rosentraub_2002, de_socio_2007}. A
robust literature has covered these, starting with archetypes like
Stone's \citeyearpar{stone_1989} Atlanta. Scholars have proposed several
subtypes over the years that group well under developmental regimes,
including entrepreneurial regimes, describing regimes' enticement with
sports industries \citep{euchner_1993}, tourism-focused regimes
\citep{russo_and_scarnato_2018}, public private partnerships
\citep{davies_2017}, and player cities, describing those which advocate
intensely to bring in or keep industry \citep{portz_1990}. A related
concept in the Japanese literature is ``castle towns,'' referring to
cities where the entire city government and economy is closely
structured around one industry \citep{hill_and_fujita_1993}. Famous
examples include Minamata, which suffered considerable environmental
pollution due to the Chisso corporation in the 1950s
\citep{funabashi_2006}; more recent examples of castle towns are nuclear
power plant host communities \citep{aldrich_and_fraser_2017}.

Developmental regimes and related types have received considerable
attention in Japan, with studies emphasizing the neoliberal,
developmental priorities of property development in post-Bubble Tokyo
\citep{saito_2003, tsukamoto_2012, sorensen_et_al_2010}, developmental
priorities in reconstruction plans from the Kobe Earthquake
\citep{edgington_2010}, and early efforts to reduce air pollution in
industrial cities like Kitakyushu \citep{yeum_2002}.

The third common type is (3) \emph{middle-class regimes} (a.k.a.
progressive regimes\^{}{[}Usually called progressive regimes, I term
these `middle-class' regimes to avoid confusion with the next type,
which support progressive, redistributive policies.{]}). These regimes
support middle-class, progressive interests like environmentalism,
health care, education, and quality city planning
\citep{deleon_1992, gendron_and_domhoff_2018, rosdil_2016}. Past
examples include politically left-wing city politics in Santa Cruz, San
Francisco, and Seattle, among others \citep{gendron_and_domhoff_2018}.
These regimes focus on a specific type of progressivism, namely
egalitarian ideals, such as environmental conservation and
sustainability \citep{rosol_et_al_2017}, but these regimes tend to
support middle-class interests, rather than working class interests
\citep{kilburn_2004}.

Famous Japanese examples include Mitaka City, a Tokyo suburb known for
progressive environmental policy, quality of life, and citizen
engagement \citep{takao_2006}. Similarly, large cities like Kyoto
\citep{sugiyama_and_takeuchi_2008} and smaller cities like Iida in
Nagano Prefecture \citep{fraser_et_al_2020} have both received attention
for their cities' emphasis and leadership on environmentalism.

Finally, the fourth type refers to (4) \emph{social welfare regimes}
(a.k.a. opportunist regimes\emph{\^{}{[}*Sometimes called
``opportunist'' regimes, referring to aims to expand the social safety
net, this study re-terms this category `social welfare regimes', to more
respectfully characterize these policies.{]})}*. These regimes
prioritize social welfare support for the working class and related
redistributive policies, such as unemployment insurance, public housing,
and financial support for families in need, eg. after crisis
\citep{stone_1993, thompson_2005, camou_2014, lai_and_chui_2014, arbaci_2019}.Related
monikers include `opportunist regimes,' as in those aiming to expand the
social safety net \citep{stone_1989}, activist regimes
\citep{clark_2001}, which use neighborhood coalitions and activist
groups to push for social equity \citep{thompson_2005}, labor coalitions
\citep{camou_2014}, and stewardship regimes \citep{nissen_1995}, which
negotiate with businesses for fair treatment of workers. While the shape
of social welfare policy varies by city and country, Canadian and UK
cities are particularly known for efforts to expand social safety nets
\citep{saraceno_2002}, like Toronto's early work expanding childcare
\citep{mahon_2007}, although Toronto has shifted over time to a
developmental/progressive regime. Japanese urban studies research has
highlighted Yokohama for its particularly expansive support for the
homeless \citep{hayashi_2013}, as well as specific city wards like the
working class neighborhood of Mikura in Kobe for its robust advocacy for
social equity in the reconstruction process after the 1995 Kobe
Earthquake \citep{yasui_2007}.

\hypertarget{correlates-of-urban-regimes}{%
\subsection{Correlates of Urban
Regimes}\label{correlates-of-urban-regimes}}

Given how useful social welfare regimes can be in the era of climate
change, what kinds of cities develop social welfare regimes, and which
do not? While little literature directly tackles this question, past
studies summarized below suggest several likely correlates.

\hypertarget{demographic-and-financial-correlates-of-urban-regimes}{%
\subsubsection{Demographic and Financial Correlates of Urban
Regimes}\label{demographic-and-financial-correlates-of-urban-regimes}}

First, we expect some cities are predisposed towards certain types of
urban regimes. Highly populated cities, cities with higher income per
capita, cities with more revenue per capita, and cities with better
balanced budgets have more funds and other resources to spend on
advancing a social welfare regime (or a developmental or middle-class
regime, for that matter). But cities who receive a larger share of their
annual budget from the national or prefectural government may face more
pressure to conform with national or prefectural objectives, which often
come in the shape of economic development policy. Such cities might
invest \emph{less} in social welfare.

\hypertarget{partisanship-and-urban-regimes}{%
\subsubsection{Partisanship and Urban
Regimes}\label{partisanship-and-urban-regimes}}

Second, party interests may push some cities towards or against social
welfare spending. The Liberal Democratic Party is, despite its name,
Japan's long-time conservative party, and traditionally promotes
business interests and economic development. Past studies explains that
when the LDP accepts social welfare policies, it usually does so to
counter any competitive advantage that policy gives left-leaning
opposition parties prior to elections, as was the case in universal
health care legislation. Cities where the Liberal Democratic Party
performed well in recently elections thus likely have little incentive
to adopt social welfare policies; their local officials and prefectural
party machine are more likely to push for developmental policies.

\hypertarget{social-capital-and-urban-regimes}{%
\subsubsection{Social Capital and Urban
Regimes}\label{social-capital-and-urban-regimes}}

However, cities with greater collective action potential might be more
likely to adopt social welfare regimes, if local residents have strong
social capital. Past literature highlights that social capital, the
social ties that bind residents \citep{putnam_2000, woolcock_2010}, come
in three different forms with distinct impacts on public participation
and policymaking: bonding, bridging, and linking social capital
\citep{aldrich_and_meyer_2015}.

\hypertarget{bonding-social-capital}{%
\paragraph{Bonding Social Capital}\label{bonding-social-capital}}

Bonding social capital refers to strong in-group ties between members of
the same social strata (eg. race, ethnicity, age, gender, income)
\citep{mcpherson_et_al_2001, mouw_2006}. We might expect bonding social
ties to help residents petition for more middle class interests, which
benefit a broad swath of residents, but fail to organize broad,
cross-community coalitions to support social welfare
\citep{tsai_2007, cox_2011, alcorta_et_al_2020}.

\hypertarget{bridging-social-capital}{%
\paragraph{Bridging Social Capital}\label{bridging-social-capital}}

In contrast, bridging social capital refers to strong inter-group ties
connecting members of different social strata (eg. members of different
racial, ethnic, age, gender, or income backgrounds)
\citep{putnam_2000, aldrich_2019}. A vast literature suggests that
stronger bridging social ties help residents organize to improve access
to public goods for the \emph{entire} community, because they build
strong inter-group trust and reciprocity that encourages folks to
mobilize, vote, and participate in civil society.

\hypertarget{linking-social-capital}{%
\paragraph{Linking Social Capital}\label{linking-social-capital}}

Finally, linking social capital refers to vertical ties connecting
residents to local officials \citep{woolcock_2010, aldrich_2019}. We
might expect that cities with stronger linking social capital are less
likely to be caretaker regimes, but could result in greater social
welfare, developmental, or middle class regimes, depending on residents'
interests. In addition to the concepts discussed above, cities with
higher levels of education and lower levels of population turnover also
tend to build stronger social ties. To date however, despite the strong
likelihood of a connection between social capital and urban regimes, no
study to the author's knowledge has yet investigated these two concepts
together.

\hypertarget{timing-and-path-dependence}{%
\subsection{Timing and Path
Dependence}\label{timing-and-path-dependence}}

Finally, timing matters. First, social welfare regimes (and spending in
general) is notoriously path dependent, where once governments
institutionalize certain spending programs, they tend to stick around.
Second, regimes may shift according to the social constraints of the
time. After the 2011 triple disaster, a surge of disaster recovery
spending occurred in the Tohoku region; we might expect this disaster
pushed some cities towards social welfare regimes in order to provide
better for vulnerable families and elders in the aftermath. Conversely,
some cities rebuild primarily according to central government
instructions, spending primarily on infrastructure while neglecting
community spending; as a result, the impact of the disaster on social
welfare regime evolution is currently unclear.

Similarly, local and national rhetoric on spending has changed over
time; concepts like the 1980s' Washington Consensus, the 1992 economic
bubble burst in Japan, the 1995 Kobe Earthquake, the 2008 Great
Recession, and the 2011 disaster each greatly shifted the conversation
on spending; some governments post-recession advocated austerity, while
the 2011 disaster highlighted great need and vulnerability of residents
to crisis, both in Tohoku and elsewhere, leading to the 2015 Sendai
Framework, which advocated a need for investment in local communities to
`build back better' after crisis so as not to leave communities
vulnerable again. Each of these influences could propel or hinder the
growth of social welfare regimes, begging the question, which direction
have Japanese cities moved over time?

\hypertarget{hypotheses}{%
\subsection{Hypotheses}\label{hypotheses}}

In summary, these four types capture a wide range of urban regime
literature, each with distinct priorities that would lead to \emph{more}
or \emph{less} spending in specific areas. I expect that these urban
regimes are not evenly distributed throughout the country, but rather
that some types of urban regimes are increasing over time. I hypothesize
that social welfare regimes, compared to other types, have increased
over the last two decades of climatic hazards, opening up new
communities to new changes in the social safety net. Below, I outline
set of methods to measure each cities' propensity towards these four
regimes.

\hypertarget{data}{%
\section{Data}\label{data}}

This study aims to describe and characterize the urban regimes of a
large-N sample of cities over time, to determine how and under what
conditions these cities' regimes have changed. I examine the case of
Japan, tracking the full universe of municipalities (cities, towns,
villages, and Tokyo's special wards) that govern their own budgetary and
administrative affairs, each capable of producing an urban regime that
shapes local governance and spending.

\hypertarget{why-japan}{%
\subsection{Why Japan?}\label{why-japan}}

While the urban regime framework was originally developed in a US
context \citep{stone_1989}, it has been applied widely throughout the
world, with strong followings in the US \citep{kilburn_2004}, UK
\citep{bassett_1996, davies_2017}, Europe
\citep{stoker_and_mossberger_1994, arbaci_2019}, Japan
\citep{hill_fujita_2000, saito_2003, sorensen_et_al_2010, tsukamoto_2012},
China, Hong Kong \citep{lai_and_chui_2014}, South Korea
\citep{shin_et_al_2015}, and comparative settings
\citep{mossberger_and_stoker_2001, ramirez_perez_et_al_2008}. Japan is a
useful test case as an industrialized democracy and the 3rd largest
economy in the world, a useful comparison case for many Global North
states like the US, UK, France, Germany, South Korea, and Taiwan, among
others. Facing frequent floods, typhoons, and earthquakes compared to
peer economies, Japan's experience gives us a glimpse of what kind of
urban regime transition we might expect in future years due to climate
change in the cities of similar industrialized democracies.

\hypertarget{unit-of-observation}{%
\subsection{Unit of Observation}\label{unit-of-observation}}

I track the full universe of 1739 municipalities for which spending data
was available between 2000 and 2018, over 19 years. The final sample
narrows into 1738 unique municipalities, which varied over time due to
mergers and new divisions, from 1428 cities in 2000 to 1727 cities in
2018, dubbed `cities' below, totaling 31,493 city-year observations. To
ensure a comparable sample, this omits 12 outlier cities at
times.\footnote{I omitted 11 cities in the Fukushima Exclusion Zone from
  2011 onwards, plus Yubari, Hokkaido for the full period, totaling 12
  cities (n = 107 city-years). I omit these because these extremely
  depopulated cities face dire social and economic conditions quite
  different from the rest of Japan.}

\hypertarget{urban-regime-indices}{%
\subsection{Urban Regime Indices}\label{urban-regime-indices}}

To represent urban regimes, this study developed new indices. Clarence
Stone and likeminded scholars sorted cities into four types of urban
regimes, including caretaker (status quo), developmental (pro-business),
middle-class (egalitarian), and social-welfare (working-class) governing
coalitions
\citep{stone_1989, stoker_and_mossberger_1994, mossberger_and_stoker_2001, kilburn_2004, de_socio_2007}.
Over time, Stone himself advocated for attention to change over time in
urban regimes, arguing that ``there is little reason to expect a stable
and cohesive governing coalition in today's cities''
\citep{stone_et_al_2015}. For this reason, one might now expect
considerable variation in urban regimes among cities, especially over
time. Though the inner-workings of governing coalitions in Japan's
municipalities are black boxes, unobservable without detailed
qualitative study of each, these coalitions can be generally sorted
based on \emph{how strongly each city's spending reflects the interests
of a specific urban regime.} This matches Stone's original conception of
urban regimes, about which he wrote: ``If a governing coalition is to be
viable, it must be able to mobilize resources commensurate with its main
policy agenda'' \citep{stone_1993}.

To represent these 4 urban regimes, this study presents 3 new indices,
based on 15 spending indicators, depicting how much a city prioritizes
spending types expected in a \textbf{social welfare} (SW),
\textbf{middle class} (MC), or \textbf{developmental} (D) regime
respectively, where low scores among all 3 depicting a
\textbf{caretaker} regime (C). Each regime index reflects the average
(mean) of cities logged spending rates on priorities that regime
typically champions (described further below). I trimmed all logged
rates to the 99\% most common values to protect against outlier bias,
clipping any city-years above the 99.5th percentile or below the 0.5th
percentile at those limits.\footnote{I use the mean, rather than median,
  to give each spending priority equal weight; the mean better captures
  variation particularly when one of these priorities (eg. social
  assistance vs.~unemployment) exceeds or lags behind others.}

\hypertarget{indicators}{%
\subsubsection{Indicators}\label{indicators}}

Annual spending indicators are logged municipal spending rates, measured
in 1000s of yen per capita to account for population, log-transformed to
account for right-skew common in rates, and inflation-adjusted to the
year 2020. I transformed each indicator into a mean-centered z-scores,
to account for different ranges, and averaged related indicators
together into the 3 indices. To demonstrate their internal validity
below, I introduce each indicator and report their correlation with
their respective index below, using the Pearson's r correlation
coefficient (where -1 shows negative trends, +1 shows positive trends,
and 0 shows neither). Each indicator captures a different aspect of that
urban regime; no regime must invest equally in, for example, each social
welfare indicator to count as such a social welfare regime, so maximal
correlations are unlikely, but positive correlations are a good sign of
internal validity.

Each indicator shows positive correlations with their overall index.
This is a great sign, indicating that an increase in any of the three
indices does generally correspond to a strong increase in its
indicators. Additionally, spending rates produced better internal
consistency than percentages of the budget, likely because each city's
share of spending on different issues varies depending on external
factors.

\begin{itemize}
\item
  The \textbf{Social Welfare regime} index combines 6 types of spending
  on working-class interests, which are highly correlated with the final
  index, according to their Pearson's r correlation coefficient. These
  including (1) social welfare assistance for low income residents (r =
  0.68), (2) assistance for children (0.45), (3) assistance for elders
  (0.68), (4) labor expenditures including unemployment relief and
  vocational training (0.3), (5) emergency services like fire
  departments (0.59), and (6) public housing (0.31). Correlations vary
  somewhat, since some social welfare regimes focus more on unemployment
  while others focus more on social welfare for elders and children, for
  example, and so our average takes this variation into account.
\item
  The \textbf{Middle Class regime} index combines spending on 5
  middle-class interests, which are highly correlated with the final
  index. These include (7) education (r = 0.51), (8) social education
  (including lifelong learning and cultural facilities) (0.5), (9)
  health care and public health services (0.6), environmental interests
  like (10) waste and recycling (0.43), and (11) city planning (0.17).
  (Planning has a weaker, but clearly positive linear relationship with
  middle class regimes, and it is an important aspect of cities focused
  on quality of life.)
\item
  The \textbf{Developmental regime} index combines spending rates on 4
  economic development interests, which correlate well with the final
  index. These include (12) agriculture, forestry, and fisheries (r =
  0.61), (13) commerce and manufacturing (0.5), large infrastructure
  like (14) roads and bridges (0.69), as well as (15) ordinary
  construction works (0.59).
\end{itemize}

Each index is mean-centered, where 0 represents the average level of
spending nationwide over time on a certain regime's issue areas, and
higher/lower values denote more/less spending rates on that regime's
issue areas, on average. -1 represents one standard deviation lower
spending than average, and +1 represents one standard deviation higher
than average. Their distributions are highlighted in Figure A1.

\hypertarget{classifying-cities-by-regime-type}{%
\subsubsection{Classifying Cities by Regime
Type}\label{classifying-cities-by-regime-type}}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item[1] City-years classified based on three regime scores being above (High) or below (Low) threshold.
\item[2] \% of cases, when using median as threshold; robustness check uses mean as threshold.
\end{TableNotes}
\begin{longtable}[t]{>{\raggedright\arraybackslash}p{3.9cm}>{\raggedright\arraybackslash}p{1.75cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.75cm}>{\raggedleft\arraybackslash}p{1.25cm}>{\raggedleft\arraybackslash}p{1.25cm}}
\caption{\label{tab:regimeclass}Table \ref{tab:regimeclass}\label{tab:regimeclass}: \textbf{Regime Classifications}}\\
\toprule
\multicolumn{2}{c}{ } & \multicolumn{3}{c}{Index Scores$^{1}$} & \multicolumn{2}{c}{\makecell[c]{Percentage of Cases\\by Threshold$^{2}$}} \\
\cmidrule(l{3pt}r{3pt}){3-5} \cmidrule(l{3pt}r{3pt}){6-7}
Name & Code & Social Welfare & Middle Class & Developmental & Median & Mean\\
\midrule
\addlinespace[0.10cm]
\multicolumn{7}{l}{\textbf{\makecell[l]{\\Classic Regimes}}}\\
\hspace{1em}\cellcolor[HTML]{ffb000}{\textcolor{black}{Social Welfare}} & SW & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 7.3 & 7.9\\
\hspace{1em}\cellcolor[HTML]{648FFF}{\textcolor{white}{Middle Class}} & MC & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 7.8 & 6.0\\
\hspace{1em}\cellcolor[HTML]{696880}{\textcolor{white}{Developmental}} & D & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 5.1 & 5.9\\
\hspace{1em}\cellcolor[HTML]{ADADC9}{\textcolor{black}{Caretaker}} & C & \cellcolor{white}{Low} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 30.1 & 35.7\\
\addlinespace[0.25cm]
\hline
\multicolumn{7}{l}{\textbf{\makecell[l]{\\Hybrid  Regimes}}}\\
\hspace{1em}\cellcolor[HTML]{DC267F}{\textcolor{white}{Social Welfare Hybrid (1)}} & SW-MC & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & 4.8 & 3.6\\
\hspace{1em}\cellcolor[HTML]{ff683b}{\textcolor{white}{Social Welfare Hybrid (2)}} & SW-D & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor{white}{Low} & \cellcolor{white}{Low} & 7.5 & 8.4\\
\hspace{1em}\cellcolor[HTML]{5542AD}{\textcolor{white}{Hybrid}} & SW-MC-D & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & 30.4 & 26.6\\
\hspace{1em}\cellcolor[HTML]{001FA2}{\textcolor{white}{Middle Class Hybrid}} & MC-D & \cellcolor{white}{Low} & \cellcolor[HTML]{C5C6D0}{High} & \cellcolor[HTML]{C5C6D0}{High} & 7.0 & 5.9\\
\bottomrule
\insertTableNotes
\end{longtable}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}
\renewcommand{\baselinestretch}{1}\selectfont

Further, we use these indices to empirically classify cities into urban
regime types, using our 3 indices' medians to demarcate 8
classifications, to represent the general range of regimes a city can
occupy, including our 4 primary urban regimes and 4 hybrids. Table
\ref{tab:regimeclass} lists each combination. If just 1 index ranked
above the median, I classified a city as that type of regime, including
Social Welfare (SW = 7.3\%), Middle Class (MC = 7.8\%), and
Developmental regimes (D = 5.1\%). If all 3 indices ranked below the
median, I classified that as a Caretaker regime (C = 30.1\%).
\textbf{Hybrids} describe cities prioritizes interests of 2 or more
regimes. If 2 indices ranked above the median, I classified that as
either a Social Welfare Hybrid Regime (SW-MC = 4.8\%, SW-D = 7.5\%) or a
Middle Class Hybrid Regime (MC-D = 7\%). 3 indices above the median
translate to a full hybrid regime (SW-MC-D = 30.4\%). The more common
hybrids tend to involve Social Welfare traits (and follow the same
increase over time as social welfare regimes). (I repeated this process
using the mean as our cutpoint, showing similar proportions of cases in
each group.)

\hypertarget{change-over-time}{%
\subsection{Change over Time}\label{change-over-time}}

\begin{figure}
\includegraphics[width=1\linewidth]{/cloud/project/viz/bands} \caption{Figure \ref{fig:bands}\label{fig:bands}: Indices Change Over Time}\label{fig:bands}
\end{figure}

But are these urban regimes fixed, or fluid? Do cities transition
between regime types to accomplish their aims? I examined this with
continuous and categorical analyses below. First, in Figure
\ref{fig:bands}, I examined the changing median score (black line) over
time for my 3 urban regime indices. Surrounding the median, red bands
show the most common 50\% of scores, represented by the interquartile
range (25-75th percentiles), and grey bands show the most commonly
occurring 90\% scores among cities (5-95\% percentiles). This chart
shows that while cities' status as developmental and middle class
regimes (based on their spending) did not change especially, the share
of cities spending more on social welfare issues sharply increased in
the years leading up to and after 2011.

\begin{figure}
\includegraphics[width=1\linewidth]{/cloud/project/viz/percent_area} \caption{Figure \ref{fig-area}\label{fig-area}: Change in Regime Types by Percentage over Time}\label{fig:area}
\end{figure}

Second, to contextualize this, I measured the changing annual
percentages of regimes based on their urban regime classifications from
Table \ref{tab:regimeclass}; I stack the 4 types of regimes where social
welfare regime indices were above the median. This highlights the
sizable increase in social welfare spending. Social welfare regimes
(yellow) increased from \textgreater1\% in 2000 to 13\% in 2018, with a
max of 14\% in 2012. Including social welfare hybrid regimes that also
focused on middle class (orange) or developmental spending (red), these
increased from 5\% in 2000 to 32\% in 2018, surging 18\% between 2008 to
2012 to 31\% in 2012. When we include hybrid regimes that spent above
the median on social welfare, middle class, and developmental interests
(purple), the total share spikes considerably. This combined total
represents all cities that spent above the median on social welfare,
regardless of their other regime scores. Starting at 23\% in 2000, the
share of cities that spent above the median on social welfare share
increased considerably between 2008 and 2012, jumping 33\% from 35\% to
68\%, ending in 2018 at 70\% of the whole sample. During the same
period, the frequency of solely middle class or developmental regimes
declined greatly, from above 10\% each to below 5\% each, while
caretaker regimes surged, then declined, starting and ending at about a
quarter of cities.

\begin{figure}
\includegraphics[width=1\linewidth]{/cloud/project/viz/map_categories_3} \caption{Figure \ref{fig-map}\label{fig-map}: The Spread of Social Welfare Regimes Over Time}\label{fig:map}
\end{figure}

The spread of social welfare regimes is especially evident in Figure
\textbackslash ref\{fig-map\}, which uses an Azthumal Equidistant
Projection, titled for readability (North is on the right), to map
\emph{when} and \emph{where} these social welfare-inclined regimes
emerged. East, northeast, and southeast Japan transitioned from
caretaker regimes in 2000 to many new social welfare-related regimes by
2018. While the 2011 tsunami likely impacted this, the change appears to
have preceded the 2011 tsunami, with many social welfare regimes
emerging already by 2010. By 2018, a full 20.9\% of cities in Kyushu had
become pure Social Welfare regimes, with similar results in Shikoku
(18.9\%) and Chugoku (15.9\%). After including social welfare hybrids
(SW-M \& SW-D), social welfare-related regimes are even more common in
Shikoku (47.4\%), Kyushu (46.5\%), Kansai (39.6\%), and Chugoku
(36.4\%). And after including pure hybrids (SW-MC-D), this covers almost
all cities in some regions, especially frequent in Hokkaido (97.8\% of
cities), Shikoku (91.6\%), Kyushu (87.2\%), Chugoku (84.2\%), and Tohoku
(84.2\%). These tallies represent a major change from 2000, when pure
social welfare regimes were most common in Kyushu (2.4\%). (Some places
do, however, seem to host more hybrid regimes over time; hybrid appear
very common in rural regimes in Hokkaido both in 2000 (72.4\%) and in
2018 (97.8\%), characterized by high per-capita spending on all three
types of spending priorities.)

To summarize, these descriptive investigations show that cities do
transition between regime types, and that social welfare regimes have
become considerably more common over time. But perhaps these increases
are merely artifacts of other demographic or political economic changes;
to ensure a more accurate picture, I turn to statistical methods with
controls below.

\hypertarget{methods}{%
\section{Methods}\label{methods}}

Next, I turn to statistical models to discern clearer estimates of the
effect of time on urban regimes and of key correlates. Using the social
welfare regime index as my dependent variable, I applied ordinary least
squares models with annual fixed effects, the appropriate technique for
a normally distributed outcome. Annual fixed effects account for
temporal heterogeneity, the appropriate technique for capturing distinct
effects each year. I generated 8 models (see Table A2), each with
successively more statistical or design-based controls, to ensure our
results are robust to model specification. (Then, for further
validation, I repeated these models, predicting as my dependent variable
the middle class regime index, in Table A3, and then the developmental
regime index, in Table A4).

\hypertarget{basic-covariates}{%
\subsection{Basic Covariates}\label{basic-covariates}}

I employ XX statistical controls to predict social welfare regime
scores. In Model 1, I predicted social welfare regime scores using
annual fixed effects plus basic demographic controls, including (1)
population, (2) inhabitable area in hectares to account for city size,
(3) the percentage of residents over age 65, to account for aging and
policy preferences from elders vs.~working-age adults, and (4) income
per capita in 1000s of yen, to account for wealth. Further, I applied
basic revenue controls: To represent cities' spending capacity, I
controlled for (5) revenue per capita in 1000s of yen; (6) the
percentage of revenue coming from national or prefectural government
funding, to account for financial autonomy or lack thereof; and (7) each
city's real term budget balance, so as not to overvalue the strength of
a regime whose spending exceeds its means.

In Model 2, I added 5 disaster controls. To account for disaster
conditions, I controlled for (8) disaster deaths and (9) buildings
damaged, each per 100,000 residents, as well as (10) whether each town
was hit by the 2011 tsunami or not (1/0). Further, I controlled for
disaster spending rates per 1,000 residents on (11) recovery, meaning in
this context physical reconstruction, and (12) disaster relief. None of
my urban regime indicators overlap with disaster spending, although we
might expect that social welfare and developmental priorities might
overlap with recovery and relief efforts, so they are important
covariates.

Next, in Model 3, I added controls for the other 2 regime indices not
being predicted; when predicting social welfare, I controlled for (13)
middle class and (14) developmental regime scores, to disentangle their
effects.

Then, in Model 4, I added partisanship and collective action, alongside
necessary controls. To represent support for political parties, I
controlled for the percentage of voters who voted for the winning LDP
candidate (or its coalition partner Komeito, which competes in separate
jurisdiction). This helps account for pork-barrel politics, common among
LDP candidates, where winning candidates reward supporting constituents
with public works funding and construction contracts. I controlled for
this two way, using votes (15) in the most recent Lower House Election
and (16) in the most recent prefectural election, to account for the
more diverse politics of local elections. These are better controls
than, say, mayoral partisanship, because Japanese mayors often run as
nonpartisan and \emph{must} collaborate across party lines to govern.

In addition to political ties, I also controlled for bonding, bridging,
and linking social capital, using Fraser's annual social capital indices
(2000-2017), which measure each type of social capital from 0 to 1 by
averaging indicators from publicly available proxies. These indices
demonstrated strong internal and external validity in their validation
study \citep{fraser_2021_IJDRR}, predicting known correlates in public
policy on environment, disasters, and health in 9 studies to date
\citep[eg.][]{fraser_et_al_2020, fraser_and_aldrich_2021_SR, fraser_et_al_2021_CRM, fraser_et_al_2022_EIST}.
The \emph{bonding index} averages 7 proxies of in-group ties that
capture much residents in a community hail from the \emph{same} social
strata, in terms of nationality, religion, education, employment status,
employment by gender, communication capacity, and age. These homophily
measures (not sheer demographics) capture the density of potential
in-group social ties between members of the same social strata (see
\citet{fraser_2021_IJDRR} for extended literature). The \emph{bridging
index} averages 8 measures of civil society participation, which tend to
facilitate encounters and social ties between members of
\emph{different} social strata \citep{putnam_2000}, including
population-normalized rates of nonprofits, religious groups, unions,
community centers, libraries, volunteerism, and voter turnout in
prefecture and lower house elections. Finally, the \emph{linking index}
averages 6 rates of access and connection to government officials,
including local officials, prefectural officials, police, prefectural
assembly members, and voteshare won by the winning party in prefectural
and lower house elections.\footnote{To be clear, my control for
  partisanship (votes for the LDP/Komeito) and the linking subindicator
  (votes for the winning party in power) are \emph{not} the same; the
  Democratic Party of Japan was the winning party from 2009 to 2012.
  These measures are not even especially correlated with each other. The
  Linking index has just a weak positive correlation with LDP/Komeito
  votes in the Lower House (r = 0.34) and prefectural elections (r =
  0.06), indicating that they cover distinct concepts.}

\hypertarget{political-collective-action-controls}{%
\subsection{Political \& Collective Action
Controls}\label{political-collective-action-controls}}

In Model 4, I added

I controlled for population.

\hypertarget{simulating-the-median-city}{%
\subsection{Simulating the Median
City}\label{simulating-the-median-city}}

Max VIF shows highest variance inflation factor in model; all scores
below 10, the threshold for problematic collinearity. F Statistic shows
whether model fits better than an intercept model. All models do. Sigma
shows on average, how much do model predictions vary from the observed
values. Change in Deviance shows the change in the model's sum of
squared residuals due to the additional of new variables not present in
the preceding model. Tested by a linear hypothesis test.\footnote{Multiple
  imputation (i = 5) filled in missing data, representing less than 1\%
  of data points (0.3\%). Variables with missing data included
  prefectural votes (n = 1299, \textless0.172\%), lower house votes (n =
  521, \textless0.069\%), income (n = 269, \textless0.036\%), and
  college (n = 46, \textless0.006\%), revenue-derived varaibles (n = 14,
  \textless0.002\%).}

\hypertarget{time}{%
\subsection{Time}\label{time}}

\newpage
\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. Based on annual fixed effects from Model 8 in Tables 3, A1, and A2.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{2.25cm}>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.9cm}>{}l>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.9cm}>{}l>{\raggedright\arraybackslash}p{1.35cm}>{\raggedright\arraybackslash}p{0.9cm}>{}l}
\caption{\label{tab:unnamed-chunk-6}Table 4: \textbf{Linear Hypothesis Tests of Temporal Effects}}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{3}{c}{\makecell[c]{Social Welfare\\Regime}} & \multicolumn{3}{c}{\makecell[c]{Developmental\\Regime}} & \multicolumn{3}{c}{\makecell[c]{Middle Class\\Regime}} \\
\cmidrule(l{3pt}r{3pt}){2-4} \cmidrule(l{3pt}r{3pt}){5-7} \cmidrule(l{3pt}r{3pt}){8-10}
Year & Estimate & SE & 95\% CI & Estimate  & SE  & 95\% CI  & Estimate   & SE   & 95\% CI  \\
\midrule
\addlinespace[0.3em]
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Pre-Disaster}}}\\
\hspace{1em}\cellcolor{gray!6}{2002} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f844f1f2ae.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8454d5bcd.pdf} & \cellcolor{gray!6}{+0.01} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f859dd28d9.pdf}\\
\hspace{1em}2003 & -0.02. & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8470682a5.pdf} & -0.08*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85911f370.pdf} & -0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81d9fa7f9.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2004} & \cellcolor{gray!6}{+0.03**} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f86545c7c9.pdf} & \cellcolor{gray!6}{-0.06***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f84ad1c703.pdf} & \cellcolor{gray!6}{-0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f84bd7d419.pdf}\\
\hspace{1em}2005 & +0.04*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85956d2e2.pdf} & -0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f86297b492.pdf} & -0.01 & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f849854f8d.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2006} & \cellcolor{gray!6}{+0.02*} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f86c0cdc5a.pdf} & \cellcolor{gray!6}{-0.09***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f86a61011d.pdf} & \cellcolor{gray!6}{-0.03***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8692874f8.pdf}\\
\hspace{1em}2007 & +0.03*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f87948c81c.pdf} & -0.1*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81b4d26dd.pdf} & -0.06*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f87cb15d90.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2008} & \cellcolor{gray!6}{+0.01} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85d8139b9.pdf} & \cellcolor{gray!6}{-0.07***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85e12e6d.pdf} & \cellcolor{gray!6}{-0.05***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f846ab0011.pdf}\\
\hspace{1em}2009 & +0.1*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f858fc2f25.pdf} & +0.11*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f825119cbd.pdf} & +0.07*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f878140d1e.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2010} & \cellcolor{gray!6}{+0.15***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85362c669.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8399a873a.pdf} & \cellcolor{gray!6}{+0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f84edd37a1.pdf}\\
\cellcolor{grey}{\textbf{\hspace{1em}Mean Pre}} & \cellcolor{grey}{\textbf{+0.04***}} & \cellcolor{grey}{\textbf{0.01}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f84e2e14bb.pdf}}} & \cellcolor{grey}{\textbf{-0.05***}} & \cellcolor{grey}{\textbf{0.01}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f847179bf1.pdf}}} & \cellcolor{grey}{\textbf{-0.01.}} & \cellcolor{grey}{\textbf{0.01}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f82fac335e.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Post-Disaster}}}\\
\hspace{1em}\cellcolor{gray!6}{2011} & \cellcolor{gray!6}{+0.18***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8c0d8f35.pdf} & \cellcolor{gray!6}{-0.06***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8350d69dd.pdf} & \cellcolor{gray!6}{+0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f829765874.pdf}\\
\hspace{1em}2012 & +0.13*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8370a11be.pdf} & -0.06*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8314886f5.pdf} & -0.02. & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f83903fa41.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2013} & \cellcolor{gray!6}{+0.16***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8711dfa22.pdf} & \cellcolor{gray!6}{+0.03**} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f871b206e2.pdf} & \cellcolor{gray!6}{+0.02.} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81ea97516.pdf}\\
\hspace{1em}2014 & +0.18*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81537205f.pdf} & -0.03** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f83479f653.pdf} & +0 & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f83f50ca0e.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2015} & \cellcolor{gray!6}{+0.09***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f82584ed38.pdf} & \cellcolor{gray!6}{-0.02} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8760a77c4.pdf} & \cellcolor{gray!6}{-0.04***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f83f872521.pdf}\\
\hspace{1em}2016 & +0.15*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f85853be8b.pdf} & -0.09*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8488a6798.pdf} & -0.03** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f825c55c2d.pdf}\\
\hspace{1em}\cellcolor{gray!6}{2017} & \cellcolor{gray!6}{+0.13***} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f822aa5194.pdf} & \cellcolor{gray!6}{-0.02*} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81215bd5a.pdf} & \cellcolor{gray!6}{-0.02} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81aeea639.pdf}\\
\hspace{1em}2018 & +0.12*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8130adcca.pdf} & -0.08*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f859a15e84.pdf} & -0.05*** & 0.01 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f818531392.pdf}\\
\cellcolor{grey}{\textbf{\hspace{1em}\cellcolor{gray!6}{Mean Post}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{+0.14***}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f82c5a8a3a.pdf}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{-0.04***}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f84e1114e1.pdf}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{-0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f81a9f335a.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Average Treatment Effect}}}\\
\cellcolor{grey}{\textbf{\hspace{1em}Post - Pre}} & \cellcolor{grey}{\textbf{+0.1***}} & \cellcolor{grey}{\textbf{0}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f86ec7cc4c.pdf}}} & \cellcolor{grey}{\textbf{+0}} & \cellcolor{grey}{\textbf{0}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f875e7601c.pdf}}} & \cellcolor{grey}{\textbf{+0}} & \cellcolor{grey}{\textbf{0}} & \cellcolor{grey}{\textbf{\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f879b5ea5c.pdf}}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{10}{l}{\textbf{\makecell[l]{\\Net Gain over Time}}}\\
\cellcolor{grey}{\textbf{\hspace{1em}\cellcolor{gray!6}{2018 - 2002}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{+0.12***}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8d46a7.pdf}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{-0.04***}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f82ade56de.pdf}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{-0.06***}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{0.01}}} & \cellcolor{grey}{\textbf{\cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//pointrange_2f8606b1c89.pdf}}}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\newpage

\renewcommand{\arraystretch}{1}

\hypertarget{political-drivers}{%
\subsection{Political Drivers}\label{political-drivers}}

\hypertarget{discussion}{%
\section{Discussion}\label{discussion}}

This study measured cities' proclivities towards each of 4 types of
urban regimes, commonly discussed in urban policy in the US or Japan
(Stone 1989, Kilburn 2004, Basset 1996, Stoker \& Mossberger 1994, Hill
\& Fujita 2000, Sorensen 2010, Ramirez-Perez et al.~2010, Mossberger \&
Stoker 2001). These included regimes that aim to maintain the (1) status
quo in their city (rather undesirable for climate resilience
initiatives); regimes that focus on promoting (2) economic development
in their city (helpful for accelerating renewable energy booms, but
perhaps not for ensuring equitable development with public support);
regimes that focus on promoting (3) progressive middle class interests
like health care, education, and environmentalism (helpful for renewable
energy, but not as common in less prosperous communities); and regimes
that focus on increasing (4) opportunity through social welfare
policies. In the cases examined in Japan, cities with this last regime
type tended to be deeply interested in disaster resilience, where city
officials were deeply concerned with residents' vulnerability during
crisis.

Yet, as I show in the results of this study, some cities' governing
coalitions are overcoming these collective action barriers and spending
more on redistributive policies than others. This is critical,
considering that my findings show \emph{social welfare regimes} are
becoming increasingly common in Japan, and are often mid-size or rural
communities where great changes in social welfare are not generally
expected.

\hypertarget{contributions-to-literature}{%
\subsection{Contributions to
Literature}\label{contributions-to-literature}}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item[1] SW = Social Welfare. MC = Middle Class. D = Developental. C = Caretaker.
\item[2] Numbers rank city-year as a percentile (0-100) compared to all other city-years.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{1.5cm}>{\raggedright\arraybackslash}p{2.5cm}>{\raggedright\arraybackslash}p{1.7cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedright\arraybackslash}p{1.7cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}>{\raggedleft\arraybackslash}p{0.3cm}}
\caption{\label{tab:unnamed-chunk-8}Table 2: \textbf{Urban Regime Change in Key Cities from Literature}}\\
\toprule
\multicolumn{3}{c}{ } & \multicolumn{4}{c}{Regime in 2000} & \multicolumn{4}{c}{Regime in 2018} \\
\cmidrule(l{3pt}r{3pt}){4-7} \cmidrule(l{3pt}r{3pt}){8-11}
Prefecture & Municipality & Literature & Type & SW & MC & D & Type  & SW  & MC  & D \\
\midrule
\cellcolor{gray!6}{Tokyo} & \cellcolor{gray!6}{Mitaka} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{C} & \cellcolor{gray!6}{14} & \cellcolor{gray!6}{30} & \cellcolor{gray!6}{3} & \cellcolor{gray!6}{C} & \cellcolor{gray!6}{30} & \cellcolor{gray!6}{12} & \cellcolor{gray!6}{3}\\
\addlinespace
Kagoshima & Kagoshima &  & C & 14 & 48 & 47 & SW & 49 & 32 & 15\\
\addlinespace
\cellcolor{gray!6}{Nagano} & \cellcolor{gray!6}{Iida} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{D} & \cellcolor{gray!6}{10} & \cellcolor{gray!6}{48} & \cellcolor{gray!6}{74} & \cellcolor{gray!6}{SW-D} & \cellcolor{gray!6}{57} & \cellcolor{gray!6}{32} & \cellcolor{gray!6}{65}\\
\addlinespace
Fukushima & Fukushima &  & D & 7 & 29 & 54 & C & 36 & 42 & 49\\
\addlinespace
\cellcolor{gray!6}{Saga} & \cellcolor{gray!6}{Genkai} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{D} & \cellcolor{gray!6}{40} & \cellcolor{gray!6}{43} & \cellcolor{gray!6}{88} & \cellcolor{gray!6}{SW-MC-D} & \cellcolor{gray!6}{94} & \cellcolor{gray!6}{81} & \cellcolor{gray!6}{92}\\
\addlinespace
Fukui & Fukui &  & D & 11 & 39 & 59 & SW & 50 & 21 & 26\\
\addlinespace
\cellcolor{gray!6}{Miyagi} & \cellcolor{gray!6}{Sendai} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{14} & \cellcolor{gray!6}{62} & \cellcolor{gray!6}{45} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{45} & \cellcolor{gray!6}{62} & \cellcolor{gray!6}{30}\\
\addlinespace
Aichi & Nagoya &  & MC & 44 & 67 & 50 & SW-MC & 66 & 75 & 29\\
\addlinespace
\cellcolor{gray!6}{Tokyo} & \cellcolor{gray!6}{Shinjuku} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{6} & \cellcolor{gray!6}{56} & \cellcolor{gray!6}{3} & \cellcolor{gray!6}{C} & \cellcolor{gray!6}{31} & \cellcolor{gray!6}{35} & \cellcolor{gray!6}{4}\\
\addlinespace
Kanagawa & Yokohama &  & MC & 23 & 64 & 33 & SW-MC & 52 & 53 & 15\\
\addlinespace
\cellcolor{gray!6}{Hokkaido} & \cellcolor{gray!6}{Sapporo} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{26} & \cellcolor{gray!6}{65} & \cellcolor{gray!6}{53} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{55} & \cellcolor{gray!6}{51} & \cellcolor{gray!6}{32}\\
\addlinespace
Miyagi & Ishinomaki &  & MC & 3 & 60 & 33 & SW-MC-D & 92 & 82 & 87\\
\addlinespace
\cellcolor{gray!6}{Tokyo} & \cellcolor{gray!6}{Minato} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{19} & \cellcolor{gray!6}{66} & \cellcolor{gray!6}{6} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{94} & \cellcolor{gray!6}{63} & \cellcolor{gray!6}{13}\\
\addlinespace
Tokyo & Musashino &  & MC & 13 & 61 & 15 & SW-MC & 61 & 60 & 4\\
\addlinespace
\cellcolor{gray!6}{Hyogo} & \cellcolor{gray!6}{Kobe} & \cellcolor{gray!6}{Nunokawa 2007; Funck 2007; Edgington 2010} & \cellcolor{gray!6}{MC-D} & \cellcolor{gray!6}{45} & \cellcolor{gray!6}{78} & \cellcolor{gray!6}{72} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{69} & \cellcolor{gray!6}{61} & \cellcolor{gray!6}{16}\\
\addlinespace
Fukuoka & Fukuoka &  & MC-D & 25 & 79 & 75 & SW-MC & 53 & 66 & 47\\
\addlinespace
\cellcolor{gray!6}{Hiroshima} & \cellcolor{gray!6}{Hiroshima} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{MC-D} & \cellcolor{gray!6}{31} & \cellcolor{gray!6}{80} & \cellcolor{gray!6}{67} & \cellcolor{gray!6}{MC} & \cellcolor{gray!6}{45} & \cellcolor{gray!6}{77} & \cellcolor{gray!6}{30}\\
\addlinespace
Hokkaido & Muroran & Edgington 2013 & SW & 52 & 49 & 41 & SW-MC & 70 & 55 & 43\\
\addlinespace
\cellcolor{gray!6}{Kyoto} & \cellcolor{gray!6}{Kyoto} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{62} & \cellcolor{gray!6}{69} & \cellcolor{gray!6}{40} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{71} & \cellcolor{gray!6}{69} & \cellcolor{gray!6}{30}\\
\addlinespace
Hokkaido & Tomakomai &  & SW-MC & 57 & 55 & 36 & SW & 67 & 48 & 28\\
\addlinespace
\cellcolor{gray!6}{Osaka} & \cellcolor{gray!6}{Osaka} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{SW-MC-D} & \cellcolor{gray!6}{82} & \cellcolor{gray!6}{87} & \cellcolor{gray!6}{58} & \cellcolor{gray!6}{SW-MC} & \cellcolor{gray!6}{76} & \cellcolor{gray!6}{59} & \cellcolor{gray!6}{18}\\
\addlinespace
Fukuoka & Kitakyushu &  & SW-MC-D & 62 & 67 & 81 & SW-MC & 70 & 62 & 47\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\hypertarget{limitations}{%
\subsection{Limitations}\label{limitations}}

Recent scholarship has highlighted cases where urban regimes are more
difficult to characterize. Depending on the country, urban governance
and levels of local autonomy may vary due to institutional differences,
laws, and tax structure.62-63 Some cities lack stable governing
coalitions, dubbed `non-regimes.'64 In practice, these either would not
spend consistently on the same priorities, or would spend little on any
new priorities, resembling a caretaker regime. Neighborhood
organizations, nonprofits, and labor movements can also motivate and
structure these cities' regimes,65 as can higher levels of government.66
These limitations aside, urban regimes, even amidst varying governance
conditions, remain a useful way to characterize that development remains
so prioritized in some cities, while opportunity-expanding policies
remain prioritized in others.67 This study's measurement using
developmental, opportunist, and progressive regime indices helps achieve
that aim.

\singlespacing

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{0}{0}
\end{CSLReferences}

\hypertarget{appendix-appendix}{%
\section*{(APPENDIX) Appendix}\label{appendix-appendix}}
\addcontentsline{toc}{section}{(APPENDIX) Appendix}

\hypertarget{table-of-contents}{%
\subsection{Table of Contents}\label{table-of-contents}}

\newpage

\hypertarget{figure_A1}{%
\subsection{Figure A1}\label{figure_A1}}

\begin{figure}
\includegraphics[width=1\linewidth]{/cloud/project/viz/distribution} \caption{Figure A1: Distributions of Urban Regime Indices}\label{fig:figure_A1}
\end{figure}

\newpage

\hypertarget{table-a1-descriptives}{%
\subsection{Table A1: Descriptives}\label{table-a1-descriptives}}

\newpage
\begin{landscape}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{9}{11}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Categorical Variables include Year$^{a}$, Prefecture$^{b}$, and Tsunami$^{c}$. Models use multiple imputation with 5 imputations to account for missing data.
\item[a] Years range from 2000 (n = 1428 cities) to 2018 (n = 1727). Mode is 2010 (n = 1732). In models, baseline year is 2000. Some municipalities consolidated over time, while others split. Dataset omits outliers including Fukushima Exclusion Zone cities from 2011-2018 and Yubari 2000-2018.
\item[b] 47 Prefectures. Modal prefecture is Hokkaido, with 178 cities (10\%, n = 1,738) and 3,327 city-years (10\%, n = 31,493). In models, the baseline prefecture is Hokkaido.
\item[c] Tsunami hit 85 municipalities in 2011; cities labeled 2011-2018 as tsunami-affected (n = 680).
\item[1] Spending measured in 1,000s of yen.
\item[2] Disaster deaths and damages (\# of buildings damaged) measured per 100,000 persons.
\item[3] Zeros from unaffected cities in disaster variable distributions omitted to show nonzero values clearly.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{4cm}>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedright}X>{\raggedleft}X>{\raggedleft}X>{}l>{}l>{\raggedright}X}
\caption{\label{tab:unnamed-chunk-10}Table A1: \textbf{Descriptive Statistics} \newline \normalsize31493 Japanese city-years (2000-2018)}\\
\toprule
\multicolumn{1}{c}{ } & \multicolumn{5}{c}{Statistics} & \multicolumn{2}{c}{Observations} \\
\cmidrule(l{3pt}r{3pt}){2-6} \cmidrule(l{3pt}r{3pt}){7-8}
Variable & Mean & Std. Dev. & Min & Median & Max & N & \% Missing & Distribution$^{3}$ & Transformed$^{3}$ & Transformation\\
\midrule
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Urban Regime Indices}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Regime} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.79} & \cellcolor{gray!6}{-1.99} & \cellcolor{gray!6}{-0.12} & \cellcolor{gray!6}{3.13} & \cellcolor{gray!6}{31479} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f846b3641.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f89b952f0.pdf} & \cellcolor{gray!6}{x}\\
\hspace{1em}Middle Class Regime & 0 & 0.55 & -2.15 & -0.1 & 3 & 31479 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f84b0f833a.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8536b4b11.pdf} & x\\
\hspace{1em}\cellcolor{gray!6}{Developmental Regime} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.87} & \cellcolor{gray!6}{-2.03} & \cellcolor{gray!6}{-0.05} & \cellcolor{gray!6}{2.91} & \cellcolor{gray!6}{31479} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f813a93714.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8266b34e5.pdf} & \cellcolor{gray!6}{x}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}Population & 73009 & 186658 & 178 & 24750 & 3724844 & 31493 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f830f945ad.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f86a3465f8.pdf} & x$^{1/10}$\\
\hspace{1em}\cellcolor{gray!6}{Inhabitable Area (ha)} & \cellcolor{gray!6}{6577.63} & \cellcolor{gray!6}{7195.38} & \cellcolor{gray!6}{105} & \cellcolor{gray!6}{4170} & \cellcolor{gray!6}{80524} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8b288c9e.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f84e2641ce.pdf} & \cellcolor{gray!6}{log(x)}\\
\hspace{1em}\% Over Age 65 & 0.29 & 0.08 & 0.08 & 0.28 & 0.6 & 31493 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f846e3815e.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8587dc1a9.pdf} & logit(x)\\
\hspace{1em}\cellcolor{gray!6}{Income per capita$^{1}$} & \cellcolor{gray!6}{1233.67} & \cellcolor{gray!6}{355.93} & \cellcolor{gray!6}{263.9} & \cellcolor{gray!6}{1199.19} & \cellcolor{gray!6}{9058.48} & \cellcolor{gray!6}{31224} & \cellcolor{gray!6}{0.9} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f85a7930a8.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f871e6f59.pdf} & \cellcolor{gray!6}{log(x)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}Revenue per capita$^{1}$ & 691.25 & 597.44 & 120.52 & 503.74 & 14123.27 & 31479 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f86413ffbb.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f894860cb.pdf} & sqrt(x)\\
\hspace{1em}\cellcolor{gray!6}{\% National \& Prefectural Funding} & \cellcolor{gray!6}{0.17} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.16} & \cellcolor{gray!6}{0.84} & \cellcolor{gray!6}{31479} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8300de1b1.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f855df7501.pdf} & \cellcolor{gray!6}{logit(x)}\\
\hspace{1em}Real Term Budget Balance (+/-) & 5.35 & 4.53 & -27.7 & 4.7 & 113.4 & 31479 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f85c2e5133.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f874dae175.pdf} & x\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Deaths$^{2}$} & \cellcolor{gray!6}{14.4} & \cellcolor{gray!6}{268.83} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{9077.99} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f85e3f766c.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f813a7bd06.pdf} & \cellcolor{gray!6}{x$^{1/10}$}\\
\hspace{1em}Disaster Damage$^{2}$ & 237.33 & 1488.81 & 0 & 0 & 23774.73 & 31493 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f84e74bd5e.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f86a6b1ff3.pdf} & x$^{1/10}$\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate$^{1}$} & \cellcolor{gray!6}{8.47} & \cellcolor{gray!6}{46.88} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.37} & \cellcolor{gray!6}{3388.75} & \cellcolor{gray!6}{31479} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f84c4b837c.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f83c4a2a5b.pdf} & \cellcolor{gray!6}{x$^{1/10}$}\\
\hspace{1em}Disaster Relief Spending Rate$^{1}$ & 2.34 & 37.04 & 0 & 0 & 1910.01 & 31479 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f865c0af8f.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f82f2eb299.pdf} & x$^{1/10}$\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{0.5} & \cellcolor{gray!6}{0.15} & \cellcolor{gray!6}{0} & \cellcolor{gray!6}{0.51} & \cellcolor{gray!6}{0.96} & \cellcolor{gray!6}{30972} & \cellcolor{gray!6}{1.7} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f82fa12fd.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f85d55d5b4.pdf} & \cellcolor{gray!6}{logit(x + 0.01)}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture & 0.32 & 0.26 & 0 & 0.32 & 0.97 & 30194 & 4.1 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f864be13dc.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f842eb840a.pdf} & logit(x + 0.01)\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital} & \cellcolor{gray!6}{0.7} & \cellcolor{gray!6}{0.05} & \cellcolor{gray!6}{0.39} & \cellcolor{gray!6}{0.71} & \cellcolor{gray!6}{0.81} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f859e308e9.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f836bc3df8.pdf} & \cellcolor{gray!6}{logit(x)}\\
\hspace{1em}Bridging Social Capital & 0.32 & 0.08 & 0.09 & 0.32 & 0.57 & 31493 & 0.0 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f83546d7f3.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f854dc7b4f.pdf} & quartiles(x)\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital} & \cellcolor{gray!6}{0.25} & \cellcolor{gray!6}{0.08} & \cellcolor{gray!6}{0.06} & \cellcolor{gray!6}{0.25} & \cellcolor{gray!6}{0.55} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f833e11491.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f819cffbdf.pdf} & \cellcolor{gray!6}{logit(x)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{11}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated & 0.1 & 0.05 & 0.01 & 0.09 & 0.46 & 31450 & 0.1 & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f81fdeec28.pdf} & \includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f85fc0f8f7.pdf} & logit(x)\\
\hspace{1em}\cellcolor{gray!6}{Total Migration per capita} & \cellcolor{gray!6}{0.07} & \cellcolor{gray!6}{0.04} & \cellcolor{gray!6}{0.01} & \cellcolor{gray!6}{0.06} & \cellcolor{gray!6}{0.62} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{0.0} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8568a2d5b.pdf} & \cellcolor{gray!6}{}\includegraphics[width=0.67in, height=0.17in]{paper_files/figure-latex//hist_2f8784bdab.pdf} & \cellcolor{gray!6}{log(x)}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\end{landscape}
\newpage

\hypertarget{table-a2-models-of-social-welfare-regime-scores}{%
\subsection{Table A2: Models of Social Welfare Regime
Scores}\label{table-a2-models-of-social-welfare-regime-scores}}

\begin{landscape}
\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 5. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 6-8, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 7-8 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 8, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 7 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{\label{tab:unnamed-chunk-12}Table A2: \textbf{OLS Models of Social Welfare Regimes.}
        \newline \normalsize
        \textit{Dependent Variable}: Social Welfare Regime Index (Z-score). 
        \newline \normalsize
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 1} & \multicolumn{1}{c}{Model 2} & \multicolumn{1}{c}{Model 3} & \multicolumn{1}{c}{Model 4} & \multicolumn{1}{c}{Model 5} & \multicolumn{1}{c}{Model 6} & \multicolumn{1}{c}{Model 7} & \multicolumn{1}{c}{Model 8} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.04*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & 0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & -0.00    (0.00) & 0.00    (0.00) & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{3.40*** (0.04)}} & \textbf{\cellcolor{gray!6}{3.39*** (0.04)}} & \textbf{\cellcolor{gray!6}{2.41*** (0.04)}} & \textbf{\cellcolor{gray!6}{2.38*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.87*** (0.05)}} & \textbf{\cellcolor{gray!6}{0.43*** (0.03)}} & \textbf{\cellcolor{gray!6}{0.47*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.01)}}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{0.00*   (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*   (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.09*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{0.42*** (0.03)} & \textbf{0.72*** (0.04)} & \textbf{0.90*** (0.03)} & \textbf{0.78*** (0.03)} & \textbf{0.41*** (0.04)} & \textbf{0.23*** (0.02)} & \textbf{0.06**  (0.02)} & 0.01.   (0.00)\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & 0.00.   (0.00) & \textbf{0.00*** (0.00)} & -0.00.   (0.00) & \textbf{-0.00**  (0.00)} & \textbf{-0.00*** (0.00)} & 0.00    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.01*   (0.00)}}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & 0.01    (0.01) & 0.00    (0.01) & -0.01    (0.01) & \textbf{0.11*** (0.01)} & \textbf{0.03**  (0.01)} & \textbf{0.03**  (0.01)} & \textbf{0.02*   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.01*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Middle Class Regime Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.16*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.15*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.12*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.04*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.02*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}Developmental Regime Index &  &  & \textbf{0.23*** (0.00)} & \textbf{0.20*** (0.00)} & \textbf{0.23*** (0.00)} & \textbf{0.07*** (0.00)} & \textbf{0.02*** (0.00)} & -0.00    (0.00)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.03*   (0.01)}} & \cellcolor{gray!6}{0.03.   (0.01)} & \cellcolor{gray!6}{0.01    (0.01)} & \cellcolor{gray!6}{0.00    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & 0.01.   (0.01) & \textbf{0.04*** (0.01)} & \textbf{0.02*** (0.00)} & \textbf{0.02*** (0.00)} & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.77*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.97*** (0.08)}} & \textbf{\cellcolor{gray!6}{-0.28*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.32*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{0.02*** (0.00)} & \textbf{0.04*** (0.00)} & \textbf{0.01**  (0.00)} & \textbf{0.01*** (0.00)} & \textbf{0.01**  (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.29*** (0.03)}} & \cellcolor{gray!6}{-0.05    (0.06)} & \textbf{\cellcolor{gray!6}{-0.14*** (0.04)}} & \textbf{\cellcolor{gray!6}{-0.10**  (0.04)}} & \cellcolor{gray!6}{-0.01.   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{-0.67*** (0.03)} & \textbf{-0.38*** (0.04)} & 0.01    (0.02) & \textbf{-0.13*** (0.03)} & -0.01    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{2.03*** (0.14)}} & \textbf{\cellcolor{gray!6}{0.66*** (0.09)}} & \textbf{\cellcolor{gray!6}{-0.45*** (0.10)}} & \textbf{\cellcolor{gray!6}{-0.04*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{1.29*** (0.07)} & \textbf{0.44*** (0.07)} & 0.08.   (0.04) & \textbf{0.13**  (0.05)} & 0.00    (0.00)\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.73*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.79*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.78*** (0.00)}}\\
\hspace{1em}Constant & -1.47*** (0.02) & -1.54*** (0.02) & -1.21*** (0.02) & -0.81*** (0.04) & -0.37*** (0.07) & -0.09.   (0.05) & 0.12*   (0.05) & 0.52*** (0.07)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 4.36 & 5.16 & 8.12 & 8.16 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \cellcolor{gray!6}{3011.7***    (25)} & \cellcolor{gray!6}{2619.8***    (30)} & \cellcolor{gray!6}{3182.5***    (32)} & \cellcolor{gray!6}{2769.3***    (39)} & \cellcolor{gray!6}{1590.6***    (86)} & \cellcolor{gray!6}{4105.5***    (86)} & \cellcolor{gray!6}{3803.8***    (86)} & \cellcolor{gray!6}{3834.3***    (86)}\\
\hspace{1em}Change in Deviance (df) & - & -113.1***     (5) & -636.5***     (2) & -133.4***     (7) & -495.4***    (47) & -1298.9***     (1) & -1410.5***     (1) & -38.5***    (17)\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.35} & \cellcolor{gray!6}{0.34} & \cellcolor{gray!6}{0.31} & \cellcolor{gray!6}{0.30} & \cellcolor{gray!6}{0.28} & \cellcolor{gray!6}{0.18} & \cellcolor{gray!6}{0.18} & \cellcolor{gray!6}{0.18}\\
\hspace{1em}R$^{2}$ & \textbf{0.71} & \textbf{0.71} & \textbf{0.76} & \textbf{0.77} & \textbf{0.81} & 0.92 & 0.92 & \textbf{0.92}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\end{landscape}
\newpage

\hypertarget{table-a3-models-of-developmental-regime-scores}{%
\subsection{Table A3: Models of Developmental Regime
Scores}\label{table-a3-models-of-developmental-regime-scores}}

\begin{landscape}
\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 5. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 6-8, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 7-8 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 8, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 7 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{\label{tab:unnamed-chunk-13}Table A3: \textbf{OLS Models of Developmental Regimes.}
        \newline \normalsize
        \textit{Dependent Variable}: Developmental Regime Index (Z-score). 
        \newline \normalsize
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 1} & \multicolumn{1}{c}{Model 2} & \multicolumn{1}{c}{Model 3} & \multicolumn{1}{c}{Model 4} & \multicolumn{1}{c}{Model 5} & \multicolumn{1}{c}{Model 6} & \multicolumn{1}{c}{Model 7} & \multicolumn{1}{c}{Model 8} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.12*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.05*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{3.38*** (0.05)}} & \textbf{\cellcolor{gray!6}{3.32*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.66*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.88*** (0.06)}} & \textbf{\cellcolor{gray!6}{2.02*** (0.06)}} & \textbf{\cellcolor{gray!6}{0.46*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.48*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.01)}}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.12*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{-0.91*** (0.05)} & \textbf{-0.41*** (0.05)} & \textbf{-0.51*** (0.04)} & 0.04    (0.04) & \textbf{0.23*** (0.04)} & \textbf{0.52*** (0.03)} & \textbf{-0.41*** (0.03)} & \textbf{-0.04*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & \textbf{0.05*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00**  (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & \textbf{0.05*   (0.02)} & \textbf{0.05**  (0.02)} & \textbf{0.11*** (0.02)} & \textbf{0.05**  (0.02)} & -0.00    (0.01) & \textbf{0.03*   (0.01)} & 0.00    (0.01)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.01*** (0.00)}}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{-0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.01*   (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.38*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.31*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.33*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.11*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.05*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.02*** (0.00)}}\\
\hspace{1em}Middle Class Regime Index &  &  & \textbf{0.31*** (0.01)} & \textbf{0.27*** (0.01)} & \textbf{0.25*** (0.01)} & \textbf{0.11*** (0.00)} & \textbf{-0.01*   (0.00)} & \textbf{-0.02*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0.01    (0.01)} & \cellcolor{gray!6}{-0.00    (0.02)} & \cellcolor{gray!6}{-0.00    (0.01)} & \cellcolor{gray!6}{0.02    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & -0.01    (0.01) & \textbf{0.02*   (0.01)} & -0.00    (0.01) & 0.01    (0.01) & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.55*** (0.06)}} & \textbf{\cellcolor{gray!6}{-0.21*   (0.09)}} & \textbf{\cellcolor{gray!6}{-0.13*   (0.06)}} & \textbf{\cellcolor{gray!6}{-0.16*   (0.07)}} & \textbf{\cellcolor{gray!6}{-0.04**  (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{0.07*** (0.00)} & \textbf{0.05*** (0.00)} & 0.01.   (0.00) & \textbf{0.02*** (0.00)} & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.18*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.24*** (0.07)}} & \cellcolor{gray!6}{0.04    (0.04)} & \cellcolor{gray!6}{0.05    (0.05)} & \cellcolor{gray!6}{0.01.   (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{-1.70*** (0.04)} & \textbf{-1.34*** (0.04)} & \textbf{-0.23*** (0.03)} & \textbf{-0.23*** (0.03)} & \textbf{-0.01*   (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-5.60*** (0.15)}} & \textbf{\cellcolor{gray!6}{-6.55*** (0.17)}} & \textbf{\cellcolor{gray!6}{-1.65*** (0.11)}} & \textbf{\cellcolor{gray!6}{-1.92*** (0.12)}} & \textbf{\cellcolor{gray!6}{-0.09*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{0.42*** (0.08)} & \textbf{0.19*   (0.08)} & -0.07    (0.05) & \textbf{0.31*** (0.06)} & \textbf{0.04*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.72*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.81*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.77*** (0.00)}}\\
\hspace{1em}Constant & -0.68*** (0.03) & -0.82*** (0.02) & 0.02    (0.02) & -0.26*** (0.06) & 0.05    (0.09) & 0.03    (0.06) & 0.13*   (0.06) & 0.31*** (0.08)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 3.86 & 4.92 & 8.12 & 8.17 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \cellcolor{gray!6}{3146.4***    (25)} & \cellcolor{gray!6}{2893.6***    (30)} & \cellcolor{gray!6}{3718.3***    (32)} & \cellcolor{gray!6}{3720.6***    (40)} & \cellcolor{gray!6}{2128.6***    (86)} & \cellcolor{gray!6}{5488***              (86)} & \cellcolor{gray!6}{4723.9***    (86)} & \cellcolor{gray!6}{4808.6***    (86)}\\
\hspace{1em}Change in Deviance (df) & - & -458.6***     (5) & -1323.9***     (2) & -805.5***     (8) & -651.8***    (46) & -1923***              (1) & -2127***              (1) & -99.4***    (17)\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.46} & \cellcolor{gray!6}{0.44} & \cellcolor{gray!6}{0.39} & \cellcolor{gray!6}{0.36} & \cellcolor{gray!6}{0.33} & \cellcolor{gray!6}{0.21} & \cellcolor{gray!6}{0.22} & \cellcolor{gray!6}{0.22}\\
\hspace{1em}R$^{2}$ & \textbf{0.71} & \textbf{0.73} & \textbf{0.79} & \textbf{0.83} & \textbf{0.85} & 0.94 & 0.93 & \textbf{0.93}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\end{landscape}
\newpage

\newpage
\begin{landscape}

\hypertarget{table-a4-models-of-middle-class-regime-scores}{%
\subsection{Table A4: Models of Middle Class Regime
Scores}\label{table-a4-models-of-middle-class-regime-scores}}

\renewcommand{\baselinestretch}{0.5}\selectfont
\renewcommand{\arraystretch}{1.5}

\begingroup\fontsize{10}{12}\selectfont

\begin{ThreePartTable}
\begin{TableNotes}
\item \textit{Note: } 
\item Statistical Significance: *** p < 0.001, ** p < 0.01, * p < 0.05, . p < 0.10. All p-values and asterisks reflect two-tailed hypothesis tests. (F-statistic is one-tailed by default.)
\item[1] Annual Fixed Effects included in every model. Prefectural effects added starting in Model 5. Excluded from table to conserve space.
\item[2] Lagged Outcome by 1 year in Models 6-8, to control for path dependence and any temporal correlation. Constrains final models to 2001-2018.
\item[3] Lagged Controls: All other numeric predictors lagged by 1 year in Models 7-8 to avoid endogeneity bias. Despite the 1\% drop in R$^{2}$, lagging controls ensures more conservative estimates.
\item[4] Transformations: In Model 8, predictors were log-, logit-, or root-transformed to fit their distribution and nonlinear trends, adding a small constant where necessary. These made statistically significant improvements in log-likelihood compared to Model 7 (p < 0.001). Area, income, and migration were logged. Revenue used the square root; the 10th root was used for Population (to avoid colinearity with spending), disaster deaths, damages, recovery spending, and relief spending (since the distributions have frequent, meaningful zeros). Age, voteshares, social capital, education, and unemployment were logit tranformed, since they are bounded at 0 and 1. Bridging social capital was split into quartiles, to avoid collinearity with regime indicators.
\end{TableNotes}
\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}>{\raggedright\arraybackslash}p{1.6cm}}
\caption{\label{tab:unnamed-chunk-14}Table A4: \textbf{OLS Models of Middle Class Regimes.}
        \newline \normalsize
        \textit{Dependent Variable}: Middle Class Regime Index (Z-score). 
        \newline \normalsize
        \textit{Unit of Observation}: 31493 Japanese municipality-years (2000-2018), with annual fixed effects.}\\
\toprule
\multicolumn{8}{c}{ } & \multicolumn{1}{c}{Best Model} \\
\cmidrule(l{3pt}r{3pt}){9-9}
\multicolumn{1}{c}{ } & \multicolumn{1}{c}{Model 1} & \multicolumn{1}{c}{Model 2} & \multicolumn{1}{c}{Model 3} & \multicolumn{1}{c}{Model 4} & \multicolumn{1}{c}{Model 5} & \multicolumn{1}{c}{Model 6} & \multicolumn{1}{c}{Model 7} & \multicolumn{1}{c}{Model 8} \\
\cmidrule(l{3pt}r{3pt}){2-2} \cmidrule(l{3pt}r{3pt}){3-3} \cmidrule(l{3pt}r{3pt}){4-4} \cmidrule(l{3pt}r{3pt}){5-5} \cmidrule(l{3pt}r{3pt}){6-6} \cmidrule(l{3pt}r{3pt}){7-7} \cmidrule(l{3pt}r{3pt}){8-8} \cmidrule(l{3pt}r{3pt}){9-9}
 & Basic Controls & Disaster Controls & Other Regimes & Collective Action & Prefecture Effects$^{1}$ & Lagged Outcome$^{2}$ & Lagged Controls$^{3}$ & Transformed$^{4}$\\
\midrule
\addlinespace[0.3em]
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Demographics}}}\\
\hspace{1em}\cellcolor{gray!6}{Population} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Inhabitable Area (ha) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & 0.00    (0.00) & \textbf{0.00*** (0.00)} & \textbf{0.03*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{\% Over Age 65} & \textbf{\cellcolor{gray!6}{1.26*** (0.05)}} & \textbf{\cellcolor{gray!6}{1.24*** (0.04)}} & \textbf{\cellcolor{gray!6}{-0.44*** (0.05)}} & \textbf{\cellcolor{gray!6}{-0.44*** (0.06)}} & \cellcolor{gray!6}{0.11    (0.07)} & \textbf{\cellcolor{gray!6}{-0.15*** (0.04)}} & \textbf{\cellcolor{gray!6}{0.14**  (0.04)}} & \cellcolor{gray!6}{0.00    (0.01)}\\
\hspace{1em}Income per capita (1000s of yen) & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & \textbf{0.00*** (0.00)} & -0.00.   (0.00) & \textbf{-0.04*** (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Revenue}}}\\
\hspace{1em}\cellcolor{gray!6}{Revenue per capita (1000s of yen)} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*** (0.00)}}\\
\hspace{1em}\% National \& Prefectural Funding & \textbf{-0.86*** (0.04)} & \textbf{-0.53*** (0.04)} & \textbf{-0.59*** (0.04)} & \textbf{-0.63*** (0.04)} & \textbf{-0.58*** (0.05)} & \textbf{0.07*   (0.03)} & \textbf{-0.27*** (0.03)} & \textbf{-0.04*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Real Term Budget Balance (+/-)} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.01*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \textbf{\cellcolor{gray!6}{0.00*   (0.00)}} & \cellcolor{gray!6}{0.00    (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Conditions}}}\\
\hspace{1em}Disaster Deaths (per 100,000) &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00    (0.00) & -0.00.   (0.00) & 0.00    (0.00) & 0.00    (0.00) & \textbf{0.03**  (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Damage (per 100,000)} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \textbf{\cellcolor{gray!6}{-0.00**  (0.00)}} & \cellcolor{gray!6}{-0.00.   (0.00)} & \cellcolor{gray!6}{0.00    (0.00)} & \cellcolor{gray!6}{-0.00    (0.00)}\\
\hspace{1em}Hit by 2011 tsunami (1/0) &  & -0.01    (0.02) & -0.03.   (0.02) & \textbf{-0.03*   (0.02)} & -0.02    (0.02) & -0.02.   (0.01) & 0.01    (0.01) & 0.00    (0.01)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Disaster Spending}}}\\
\hspace{1em}\cellcolor{gray!6}{Disaster Recovery Spending Rate} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*** (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \textbf{\cellcolor{gray!6}{-0.00*   (0.00)}} & \cellcolor{gray!6}{-0.00    (0.00)} & \cellcolor{gray!6}{0.00    (0.00)}\\
\hspace{1em}Disaster Relief Spending Rate &  & \textbf{-0.00*** (0.00)} & \textbf{-0.00**  (0.00)} & -0.00.   (0.00) & -0.00    (0.00) & 0.00    (0.00) & \textbf{0.00**  (0.00)} & 0.01.   (0.00)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Other Urban Regimes}}}\\
\hspace{1em}\cellcolor{gray!6}{Social Welfare Index} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.23*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.23*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.19*** (0.01)}} & \textbf{\cellcolor{gray!6}{0.06*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.04*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.03*** (0.00)}}\\
\hspace{1em}Developmental Regime Index &  &  & \textbf{0.27*** (0.01)} & \textbf{0.27*** (0.01)} & \textbf{0.28*** (0.01)} & \textbf{0.11*** (0.00)} & 0.00    (0.00) & \textbf{-0.02*** (0.00)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Political Parties}}}\\
\hspace{1em}\cellcolor{gray!6}{\% LDP Coalition Votes: Lower House} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{0.03.   (0.02)} & \cellcolor{gray!6}{0.02    (0.02)} & \cellcolor{gray!6}{0.00    (0.01)} & \cellcolor{gray!6}{-0.00    (0.01)} & \cellcolor{gray!6}{}\\
\hspace{1em}\% LDP Coalition Votes: Prefecture &  &  &  & \textbf{-0.02*   (0.01)} & -0.01    (0.01) & -0.00    (0.01) & 0.01    (0.01) & \\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Collective Action}}}\\
\hspace{1em}\cellcolor{gray!6}{Bonding Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-0.53*** (0.07)}} & \textbf{\cellcolor{gray!6}{0.25**  (0.10)}} & \cellcolor{gray!6}{0.04    (0.06)} & \cellcolor{gray!6}{-0.11    (0.07)} & \textbf{\cellcolor{gray!6}{-0.03*   (0.01)}}\\
\hspace{1em}Bridging Social Capital (Quartiles) &  &  &  & \textbf{-0.01*** (0.00)} & \textbf{0.02*** (0.00)} & 0.00    (0.00) & \textbf{0.02*** (0.00)} & \textbf{0.01*** (0.00)}\\
\hspace{1em}\cellcolor{gray!6}{Linking Social Capital (0-1)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.15*** (0.04)}} & \cellcolor{gray!6}{0.10    (0.07)} & \cellcolor{gray!6}{-0.00    (0.05)} & \cellcolor{gray!6}{-0.01    (0.05)} & \cellcolor{gray!6}{0.00    (0.01)}\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Extra Controls}}}\\
\hspace{1em}\% College Educated &  &  &  & \textbf{0.25*** (0.04)} & 0.09.   (0.05) & \textbf{0.16*** (0.03)} & \textbf{-0.08*   (0.03)} & 0.00    (0.01)\\
\hspace{1em}\cellcolor{gray!6}{\% Unemployed} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{-1.50*** (0.16)}} & \textbf{\cellcolor{gray!6}{-1.27*** (0.18)}} & \cellcolor{gray!6}{-0.01    (0.12)} & \textbf{\cellcolor{gray!6}{-1.18*** (0.12)}} & \textbf{\cellcolor{gray!6}{-0.07*** (0.01)}}\\
\hspace{1em}Total Migration (per capita) &  &  &  & \textbf{1.02*** (0.08)} & \textbf{1.33*** (0.08)} & \textbf{0.21*** (0.06)} & \textbf{0.33*** (0.06)} & \textbf{0.02*** (0.01)}\\
\hspace{1em}\cellcolor{gray!6}{Lagged Outcome (1 year prior)} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \cellcolor{gray!6}{} & \textbf{\cellcolor{gray!6}{0.75*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.80*** (0.00)}} & \textbf{\cellcolor{gray!6}{0.80*** (0.00)}}\\
\hspace{1em}Constant & -0.74*** (0.02) & -0.82*** (0.02) & -0.24*** (0.02) & 0.19**  (0.07) & -0.45*** (0.09) & -0.09    (0.06) & 0.13*   (0.06) & -0.01    (0.08)\\
\addlinespace[0.25cm]
\hline
\multicolumn{9}{l}{\textbf{\makecell[l]{\\Model Fit}}}\\
\hspace{1em}\cellcolor{gray!6}{N (city-years)} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{31493} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755} & \cellcolor{gray!6}{29755}\\
\hspace{1em}Max VIF & 2.30 & 2.33 & 4.38 & 5.32 & 8.12 & 8.16 & 8.06 & 8.40\\
\hspace{1em}\cellcolor{gray!6}{F-statistic (df)} & \cellcolor{gray!6}{1039.7***    (25)} & \cellcolor{gray!6}{921.8***    (30)} & \cellcolor{gray!6}{1242***              (32)} & \cellcolor{gray!6}{1016.3***    (40)} & \cellcolor{gray!6}{552***              (86)} & \cellcolor{gray!6}{1872.4***    (86)} & \cellcolor{gray!6}{1715.6***    (86)} & \cellcolor{gray!6}{1727.8***    (86)}\\
\hspace{1em}Change in Deviance (df) & - & -148***              (5) & -867.7***     (2) & -54***              (8) & -365.3***    (46) & -2177.3***     (1) & -2337***              (1) & -29.7***    (17)\\
\hspace{1em}\cellcolor{gray!6}{Sigma (Avg. Error)} & \cellcolor{gray!6}{0.41} & \cellcolor{gray!6}{0.40} & \cellcolor{gray!6}{0.37} & \cellcolor{gray!6}{0.36} & \cellcolor{gray!6}{0.35} & \cellcolor{gray!6}{0.22} & \cellcolor{gray!6}{0.23} & \cellcolor{gray!6}{0.23}\\
\hspace{1em}R$^{2}$ & \textbf{0.45} & \textbf{0.47} & \textbf{0.56} & \textbf{0.56} & \textbf{0.60} & \textbf{0.84} & \textbf{0.83} & \textbf{0.83}\\
\bottomrule
\insertTableNotes
\end{longtabu}
\end{ThreePartTable}
\endgroup{}

\renewcommand{\arraystretch}{1}

\end{landscape}

\bibliography{mybibfile.bib}


\end{document}
